### ISSUE TITLE
Corp - CA - XML doesn't contain refund

### ISSUE THREAD

**Issue by TaxwareSupport** [TaxwareSupport/Issue-Reports#1]
**Client Name:** Kathy

**Client ID:** 610-86

**Description:** C-Corp not putting refund amounts on XML for CA returns.

**Reproduce:** Use Data Provided. Has 1200 CA Refund, but on XML there is no refund amounts.

**Data Location:** R:\Matt\CACorpRefund || [IssueData.zip](https://github.com/TaxwareSupport/Issue-Reports/files/2077089/IssueData.zip)

**Comment by swd7** [comment]
This has been fixed and will go up in the next corp patch.

**Comment by MHGray** [comment]
Will notify client.
