### ISSUE TITLE
The 4797 does not carry to the QBI

### ISSUE THREAD

**Issue by TwZach** [TaxwareSupport/Issue-Reports#107]
**Client Name:**  
Chris
**Client ID:**  
5980
**Description:**  
When preparing the 199A on NextGen, the software is only pulling forward the loss from schedule F and not giving an option to notate the gain from the sale of business assets on Form 4797.
**Reproduce:**  

**Data Location:**

**Comment by DodgerDave** [comment]
Maybe it should, maybe it shouldn't. Nobody knows for sure.
