### ISSUE TITLE
1040 Legacy - MA - Schedule B not carrying numbers correctly causes No Tax Status to be applied

### ISSUE THREAD

**Issue by MHGray** [TaxwareSupport/Issue-Reports#11]
**Client Name:**  
Pam Crockett

**Client ID:**  
21344

**Description:**  
If client has a low income but not less than 8000 for a PY return then the program seems to be checking the No Tax Status indicator when it shouldn't be. I think this is a carry error with the Schedule B, which doesn't carry from line 9 of the form, to line 29. I'll attach the Schedule B for reference. 

![image](https://user-images.githubusercontent.com/8196735/42592401-3ae05662-84fe-11e8-8c8e-e89caff3e7cd.png)

![image](https://user-images.githubusercontent.com/8196735/42592436-5886a4f0-84fe-11e8-9e6b-babb8b213f33.png)

Line 35 here is what gets carried to the Schedule NTS-L-NR/PY to calculate No Tax Status, but it should be the 5785 amount

**Reproduce:**  
Use Data Provided

**Data Location:**
R:\Matt\MANoTaxStatusIssue

**Comment by DodgerDave** [comment]
Fixed on 7-12
