### ISSUE TITLE
Wintax - W2 Input - [09] SSN doesn't auto format

### ISSUE THREAD

**Issue by MHGray** [TaxwareSupport/Issue-Reports#112]
**Client Name:**  
Miguel

**Client ID:**  
21191

**Description:**  
[09] in W-2 input doesn't auto format SSNs.

**Reproduce:**  
W2 input -> [09] enter SSN -> Missing dashes which causes error on validity checks

**Comment by MyNameIsDonovan** [comment]
formats now
