### ISSUE TITLE
Wintax - No EIC but can't efile without due diligence

### ISSUE THREAD

**Issue by MHGray** [TaxwareSupport/Issue-Reports#113]
**Client Name:**  
Lilly

**Client ID:**  
21535

**Description:**  
Client is the dependent of another and so can't fill out Due Diligence without errors. Isn't trying to get EIC, 8863, or additional child tax credit but can't send even if not taking it. Their special filing category is set to Dependent of Another.

Error comes when trying to E-File. It won't allow efile if due diligence is not completed.

**Reproduce:**  
Use data provided

**Data Location:**
R:\Matt\NOEICbutForcingDueDil

**Comment by DodgerDave** [comment]
Fixed 1-28
