### ISSUE TITLE
Wintax - W2 - Mouse-Free for wizard mode and verification number

### ISSUE THREAD

**Issue by MHGray** [TaxwareSupport/Issue-Reports#117]
**Client Name:**  
Jeremy

**Client ID:**  
5980

**Description:**  
There is no way to mouse-free wizard mode toggle or enter the verification number. 
![image](https://user-images.githubusercontent.com/8196735/51624887-ac1bd400-1ef0-11e9-9446-dbb3bf162ea6.png)

**Comment by MyNameIsDonovan** [comment]
added
