### ISSUE TITLE
Wintax - Prompt State default doesn't appear after DD prompt

### ISSUE THREAD

**Issue by MHGray** [TaxwareSupport/Issue-Reports#119]
**Client Name:**  
Jeremy

**Client ID:**  
5980

**Description:**  
Have the 'Automatically prompt for entry to primary state' default turned on [28]. Have the federal direct deposit prompt show up. Leave direct deposit and the prompt to enter the state doesn't show up.

**Reproduce:**  
Use data provided cause I don't actually no the triggers for the direct deposit prompt.

**Data Location:**
R:\Matt\DDandStateOrdering

**Comment by MyNameIsDonovan** [comment]
This one took me waaaay to long to fix. Also fixed the issue with the MF numbers getting all wonky.
