### ISSUE TITLE
2018 S-Corp -> CA 100S -> Schema requires CA ID but no CA ID Exists for LLC Filing as S-Corp

### ISSUE THREAD

**Issue by twnathan** [TaxwareSupport/Issue-Reports#125]
**Client Name:**  
ROBERT LEACH

**Client ID:**  
12703

**Description:**  
2018 S-Corp -> CA 100S -> Schema requires CA ID but no CA ID Exists for LLC Filing as S-Corp

Bob has a client who is an LLC and wants to file as an S-Corp. FTB.ca.gov says that this should be possible via the CA 100 (filing as Corp), 100S (filing as S-Corp) or 568 (filing as Partnership): https://www.ftb.ca.gov/businesses/Structures/LLC-Filing-Requirements.shtml

When completing the CA 100S in program, the Basic Information requires the following:
![image](https://user-images.githubusercontent.com/44508876/51646446-66313100-1f2d-11e9-8871-76aa05614c17.png)

[01] California ID Number (numerics only)
[02] California Secretary of State file number

Bob has the LLC CA SoS file number but no California ID Number. His return fails schema validation because he does not have the CA ID #. Donovan believes that he has located, in the schema, an option to declare the business as an LLC filing as an S-Corp which would permit filing without certain information fields being completed, due to the information not applying to the LLC situation.

Client data located on the R Drive (below)

**Reproduce:**  

**Data Location:**
R:\Nathan\12703 BOB - LLC S-Corp CA 100S Issue

**Comment by MyNameIsDonovan** [comment]
should be available in the next patch
