### ISSUE TITLE
Wintax - Schedule E Overflow Schedules

### ISSUE THREAD

**Issue by twgreg** [TaxwareSupport/Issue-Reports#130]
**Client Name:**  
Steve

**Client ID:**  
87316

**Description:**  
The Schedule E  does not have the ability to add details to an expense with F3.
There are no blue corners in the input box.
The 2017 NG program was the same, but legacy had the blue corner and F3 function.

**Reproduce:**  
Mine is the same.
Prior years have the F3.

**Data Location:**

**Comment by MHGray** [comment]
Seems to be fixed
