### ISSUE TITLE
2018 Wintax -> Schedule A Schema Validation Error for State & local income taxes

### ISSUE THREAD

**Issue by twnathan** [TaxwareSupport/Issue-Reports#137]
**Client Name:**  
CONNIE VAZQUEZ

**Client ID:**  
28020

**Description:**  
2018 Wintax -> Schedule A Schema Validation Error for State & local income taxes

The schema validation XML states that the State & local income taxes value is incorrect, but the Validation states that the error is actually elsewhere. 

**Reproduce:**  
Matt has seen this error as well and believes he may have already turned it in. He can provide more detail.

**Data Location:**

**Comment by DodgerDave** [comment]
Looks like it only affected this user.  Their schema had a problem so Donovan deleted it and then the correct schema reloaded.
