### ISSUE TITLE
2018 Wintax -> OH State -> Printing/previewing nearly all OH forms and schedules regardless of Print Settings, unless Copy Count is "0"

### ISSUE THREAD

**Issue by twnathan** [TaxwareSupport/Issue-Reports#139]
**Client Name:**  
RANDALL @ ROBERT REEVES

**Client ID:**  
572-86

**Description:**  
2018 Wintax -> OH State -> Printing/previewing nearly all OH forms and schedules regardless of Print Settings, unless Copy Count is "0"

Client printed a return and was surprised when over 20 pages of OH forms and schedules printed when it should have only been 4. Pages were printing for forms and schedules that the taxpayer does not have/need. Print settings were already set to "Print only when required" but the client then completely unchecked the pages that he does not ever need. Print/preview still prints the extra forms/schedules. the only thing that prevents printing these pages is putting a "0" value in the copies input.

**Reproduce:**  
Reproduced on tech computer with dummy return

**Data Location:**

**Comment by DodgerDave** [comment]
Fixed 1-28
