### ISSUE TITLE
Cannot use the enter button on prompt asking to go to state input in next gen

### ISSUE THREAD

**Issue by TwZach** [TaxwareSupport/Issue-Reports#146]
**Client Name:**  
David 
**Client ID:**  
5980
**Description:**  
when leaving the line input or forms and schedules the prompt that asks if you would like to enter state input can only be clicked with the mouse, the enter key doesn't work.
**Reproduce:**  

**Data Location:**

**Comment by MyNameIsDonovan** [comment]
should be able to now
