### ISSUE TITLE
Wintax 2018 - Tax Reports Preparer Summary

### ISSUE THREAD

**Issue by twgenie** [TaxwareSupport/Issue-Reports#147]
**Client Name:**  
Adrian

**Client ID:**  
20157

**Description:**  
A message pops up saying "There is no row at position -1." when the client clicks on the buttons for Preparer Total Summary in the tax reports section.
![taxreports](https://user-images.githubusercontent.com/46978780/51920577-8c762700-239a-11e9-8f4c-6065e5e259ec.png)

**Reproduce:**  
Wintax 2018 Main menu -> [06] Tax reports -> [18] Preparer Summary Totals

**Comment by MyNameIsDonovan** [comment]
fixed
