### ISSUE TITLE
Louisiana - Line 17 not calculating

### ISSUE THREAD

**Issue by twgenie** [TaxwareSupport/Issue-Reports#154]
**Client Name:**  
Guy

**Client ID:**  
213104

**Description:**  
Values entered into LA Citizen insurance assessment is not multiplying the amount by 25 percent (.25)
![image](https://user-images.githubusercontent.com/46978780/51947982-b3a11880-23db-11e9-8599-c1a7bf690077.png)

![image](https://user-images.githubusercontent.com/46978780/51947995-c4ea2500-23db-11e9-95fa-1332a0500266.png)

**Reproduce:**  
Louisiana -> [02]Income, Deductions, and credits -> Line [06]
**Data Location:**

**Comment by twJorge** [comment]
Fixed, now calculating correctly.
