### ISSUE TITLE
8889 does not leave forms and schedules used when cleared

### ISSUE THREAD

**Issue by TwZach** [TaxwareSupport/Issue-Reports#162]
**Client Name:**  
chelsey
**Client ID:**  
21633
**Description:**  
when you clear form 8889 from the return it does delete from the return, but not from the forms and schedules used. 
**Reproduce:**  
add 8889 -> remove 8889 -> it is not removed from forms and schedules used but it is no longer included in preview return
**Data Location:**

**Comment by MyNameIsDonovan** [comment]
fixed
