### ISSUE TITLE
Wintax - Sch B - Tax withheld is carrying to the state box when it shouldn't

### ISSUE THREAD

**Issue by MHGray** [TaxwareSupport/Issue-Reports#171]
**Client Name:**  
Harlow

**Client ID:**  
21361

**Description:**  
Schedule B Dividends when entering federal witholdings should not carry that amount to the state as they will almost never be the same.

![image](https://user-images.githubusercontent.com/8196735/52140608-10811680-2608-11e9-8f82-b987b5161343.png)

**Reproduce:**  
Enter Federal witholdings on a dividend input in sch B and hit tab.

**Comment by MyNameIsDonovan** [comment]
ok
