### ISSUE TITLE
2018 Wintax -> Sch C -> [03] Recall Prior -> Line #s Are Wrong -> Exit/Re-enter Sch C -> Line #s Fixed

### ISSUE THREAD

**Issue by twnathan** [TaxwareSupport/Issue-Reports#178]
**Client Name:**  
LANNY SUMNER

**Client ID:**  
21012

**Description:**  
Client recalling prior Sch C info into new year has noticed that the line numbers are incorrect, but if not caught then they print/preview incorrectly. However if you exit out of the Sch C after recalling prior info then re-enter, the line numbers are corrected. 

**Reproduce:**  
2018 Wintax -> Sch C -> [03] Recall Prior -> Line #s Are Wrong -> Exit/Re-enter Sch C -> Line #s Fixed

Do not have a prior year client with Sch C info to reproduce on my side

**Data Location:**

**Comment by MyNameIsDonovan** [comment]
fixed
