### ISSUE TITLE
Next Gen misc features info is deleted when you exit the return

### ISSUE THREAD

**Issue by TwZach** [TaxwareSupport/Issue-Reports#180]
**Client Name:**  
Doug
**Client ID:**  
5590
**Description:**  
When in a individual return if you enter information in the Misc Schedules, then exit the return the information in the sch is deleted.
**Reproduce:**  
open return -> add misc schedule -> input data -> exit return -> open return -> data is gone.
**Data Location:**

**Comment by MyNameIsDonovan** [comment]
yup, fixed

**Comment by MHGray** [comment]
This still seems pretty messed up, particularly for prior year clients that have had Misc Schedules in the past. Got data from client. Use provided data to test. Looks like the prior year schedules are possibly messing up the schedule count.

**Data Location:**
R:\Matt\MiscSchedules

**Comment by MyNameIsDonovan** [comment]
Yeah its doing weird stuff
Should be fixed going forward... has something to do with index garbage
