### ISSUE TITLE
2018 Wintax -> 1040 Line Input -> [01] Wages -> Recall Prior Year (1099 from 2017) -> No Address on 1099

### ISSUE THREAD

**Issue by twnathan** [TaxwareSupport/Issue-Reports#183]
**Client Name:**  
LANNY SUMNER

**Client ID:**  
21012

**Description:**  
Client noticed that recalling a prior 1099 does not carry the address over, requiring re-entry. If not caught it passes FED but IL state rejects it.

**Reproduce:**  
2018 Wintax -> 1040 Line Input -> [01] Wages -> Recall Prior Year (1099 from 2017) -> No Address on 1099

Unable to duplicate on tech computer without a 2017 1099 to recall

**Data Location:**

**Comment by MyNameIsDonovan** [comment]
added
