### ISSUE TITLE
2018 Wintax -> QBI -> Auto-selecting simplified QBI worksheet for single, high-income taxpayer -> Providing larger deduction than it should

### ISSUE THREAD

**Issue by twnathan** [TaxwareSupport/Issue-Reports#185]
**Client Name:**
LANNY SUMNER

**Client ID:**  
21012

**Description:**  
Client found that a single, high-income taxpayer was receiving a larger deduction than he should because the program is auto-selecting the simplified QBI. Knows about the override but worried that other preparers may submit the wrong information. 

**Reproduce:**  
2018 Wintax -> QBI -> Auto-selecting simplified QBI worksheet for single, high-income taxpayer -> Providing larger deduction than it should

**Data Location:**

**Comment by DodgerDave** [comment]
For now on (until IRS releases further instructions), the user will be prompted to enter the QBI deduction amount in cases where the simplified worksheet can't be used.  If they don't enter anything than the QBI deduction will be zero.
