### ISSUE TITLE
2018 Fiduciary -> [09] Print Proforma(s) -> Select Client -> No Rental Activities Print Out

### ISSUE THREAD

**Issue by twnathan** [TaxwareSupport/Issue-Reports#189]
**Client Name:**  
STEVE WILLIAMS

**Client ID:**  
9913

**Description:**  
Client is looking for a rental activities print out with the Print Proforma(s) option but no such form is listed

**Reproduce:**  
2018 Fiduciary -> [09] Print Proforma(s) -> Select Client -> No Rental Activities Print Out

**Data Location:**

**Comment by MHGray** [comment]
Fiduc is very uncommon and the ones that have rentals are even more uncommon. Transferred this to bug testing for next year, but unlikely to be worth the time.
