### ISSUE TITLE
Wintax - Not taking ACTC, AOTC, or EIC but 8867 is still being created and sent

### ISSUE THREAD

**Issue by MHGray** [TaxwareSupport/Issue-Reports#191]
**Client Name:**  
Harlow

**Client ID:**  
21361

**Description:**  
Data Specific. They have a dependent that is disabled but doesn't qualify for any of the big credits, but due diligence is still printing and efiling. Can't find a way to remove 8867. 

The negative amount in other income is correct. The W-2 was given to them incorrectly. 

**Reproduce:**  
Use Data Provided

**Data Location:**
R:\Matt\Invincible8867

**Comment by DodgerDave** [comment]
Fixed 2-5
