### ISSUE TITLE
validity error in CA for a qualified widower 

### ISSUE THREAD

**Issue by TwZach** [TaxwareSupport/Issue-Reports#196]
**Client Name:**  
Charlie
**Client ID:**  
214-86
**Description:**  
Gets a validity error
![image](https://user-images.githubusercontent.com/45858181/52304280-36c7ee80-2947-11e9-9715-00fdb27dac82.png)
but xml shows
![image](https://user-images.githubusercontent.com/45858181/52304294-447d7400-2947-11e9-95fc-6e38ee061d97.png)

**Reproduce:**  

**Data Location:**
R:\Zac\2018clientdata\214-86clientdata

**Comment by DodgerDave** [comment]
fixed 2-4
