### ISSUE TITLE
clients medical insurance box won't check causing a reject

### ISSUE THREAD

**Issue by TwZach** [TaxwareSupport/Issue-Reports#199]
**Client Name:**  
Michael
**Client ID:**  
21225
**Description:**  
Medical Insurance coverage but not checked when selecting yes on health care coverage.
**Reproduce:**  

**Data Location:**
R:\Zac\2018clientdata\21225clientdata

**Comment by DodgerDave** [comment]
Dependent of another is checked so the instructions say not to check the box.
