### ISSUE TITLE
Indiv - State - DC Schema Validation Error

### ISSUE THREAD

**Issue by MHGray** [TaxwareSupport/Issue-Reports#2]
**Client Name:**  Miss Samuels

**Client ID:**  20190

**Description:**
Getting schema validation error below.   
![image](https://user-images.githubusercontent.com/8196735/41168542-2781d54a-6afb-11e8-9588-de73ae6980ea.png)  
Input seems correct but XML is making additional child element that DC doesn't want. 
![image](https://user-images.githubusercontent.com/8196735/41168731-b52a0714-6afb-11e8-927f-280a6a2a19c6.png)  
My guess is DC changed their schema.

**Reproduce:**
Use data provided and do a validation check.

**Data Location:**  
R:\Matt\DCSchemaChanged

**Comment by swd7** [comment]
Fixed next patch.
