### ISSUE TITLE
Georgia return rejected for line 21

### ISSUE THREAD

**Issue by TwZach** [TaxwareSupport/Issue-Reports#201]
**Client Name:**  
barry
**Client ID:**  
21240
**Description:**  
Reject for line 21 additions not equal to line 21
**Reproduce:**  
open client state data preview return
**Data Location:**
R:\Zac\2018clientdata\21240clientdata

**Comment by DodgerDave** [comment]
You have to limit the credit taken on Sch IND-CR so it is not more then the tax (line 16).  There is input for the amount of credit taken for each credit on the IND-CR to accomplish this.
