### ISSUE TITLE
Wintax - Prior Year Recall - Does not show Sch A as a prior form used

### ISSUE THREAD

**Issue by MHGray** [TaxwareSupport/Issue-Reports#202]
**Client Name:**  
Steve - Message Boards

**Client ID:**  
87316

**Description:**  
Recalling a prior year return that itemized does not show Sch. A as one of the prior forms used on line input/forms schedules

**Reproduce:**  
Recall prior the data provided which did have enough to itemize

**Data Location:**
R:\Matt\SchAPriorYear

**Comment by DodgerDave** [comment]
Fixed 3-21
