### ISSUE TITLE
Puerto Rico -Issue -1040

### ISSUE THREAD

**Issue by twcelmira** [TaxwareSupport/Issue-Reports#205]
**Client Name:**  
Jesenia Rodriguez

**Client ID:**  
21642
**Description:**  
The calculation for 1040SS are wrong according to the new changes. The maximum amount the taxpayer could take will be the total withholding of the social security and medicare. The data sample has a calculation of $1000 per child instead of the $1400.00 ( for this case the maximum amount the taxpayer should receive will be $3506 according to w2s information)
**Reproduce:**  
Data under Jesenia Rodriguez 
**Data Location:**
R:Dave/ 18ClientData/Jesenia Rodriguez

**Comment by DodgerDave** [comment]
Looks like this was corrected. I just forgot to close it.
