### ISSUE TITLE
client getting a reject for an invalid Calc

### ISSUE THREAD

**Issue by TwZach** [TaxwareSupport/Issue-Reports#206]
**Client Name:**  
lily
**Client ID:**  
21535
**Description:**  
Reject saying sch 1 adjustments is miscalculating, preview shows something similar
**Reproduce:**  
open client data preview schedule 1
**Data Location:**
R:\Zac\2018clientdata\21535clientdat

**Comment by DodgerDave** [comment]
Fixed 2-12
