### ISSUE TITLE
2018 Wintax->1040->[01] Wages->[04] Add (1099R - Pension)->[33] RRB? YES->[20] YES->[21]-> Not yet implemented

### ISSUE THREAD

**Issue by twnathan** [TaxwareSupport/Issue-Reports#208]
**Client Name:**  
LANNY SUMNER

**Client ID:**  
21012

**Description:**  
Client is wondering if the worksheet is not ready yet, is an oversight, or something else -- would like to complete the simplified worksheet for the RRB-1099-R

![image](https://user-images.githubusercontent.com/44508876/52378574-e6bb5b80-2a1c-11e9-8434-1fbc499e014f.png)

**Reproduce:**  
2018 Wintax -> 1040 -> [01] Wages -> [04] Add (1099R - Pension) -> [33] RRB? YES -> [20] Use simplified worksheet? YES -> [21] Simplified method worksheet -> Not yet implemented

Reproduced on tech computer

**Data Location:**

**Comment by twJorge** [comment]
Form was already in NextGen, just needed to be added.
