### ISSUE TITLE
NextGen - Summary Screen - Complete and Locked status locks things a little too much.

### ISSUE THREAD

**Issue by MHGray** [TaxwareSupport/Issue-Reports#21]
**Client Name:**  
Brenda

**Client ID:**  
87133

**Description:**  
In NextGen, when a return is set to complete and locked, it locks things that shouldn't be locked, like preview and printing the return, tax planning, and billing information.

**Comment by DodgerDave** [comment]
Fixed on 9-7.  Will go on next patch.
