### ISSUE TITLE
Validity error for sch a charitable contributions 

### ISSUE THREAD

**Issue by TwZach** [TaxwareSupport/Issue-Reports#211]
**Client Name:**  
lisa
**Client ID:**  
213167
**Description:**  
The client has two charitable contributions that are not vehicles or boats but is getting validity errors saying they need name and date.
**Reproduce:**  
see client data
**Data Location:**
R:\Zac\2018clientdata\213167clientdata

**Comment by DodgerDave** [comment]
Fixed 2-6.  Will have to go into each item on 8283 and hit button "clear PDF"
