### ISSUE TITLE
2018 Wintax -> TP as Head of Household -> Carry FED into CA -> [01] Basic Information -> FTB 3532 -> HoH Info Doesn't Completely Carry from FED -> CA Validity Check Misses Incomplete FTB 3532

### ISSUE THREAD

**Issue by twnathan** [TaxwareSupport/Issue-Reports#214]
**Client Name:**  
SANDRA @ FINESTONE & FINESTONE

**Client ID:**  
213150

**Description:**  
Client encountered a CA state reject on a client stating that if filing as Head of Household that the CA 3532 was required. Once the FTB 3532 was located the client realized that not all of the Head of Household information carried over including:

- Relationship of dependent
- SSN
- Estimated Income

CA Validity check did not catch the incomplete and unattached 3532 and FED HoH info did not carry over completely and needed to be entered in manually before e-file.

**Reproduce:**  
2018 Wintax -> TP as Head of Household -> Carry FED into CA -> [01] Basic Information -> FTB 3532 -> HoH Info Doesn't Completely Carry from FED -> CA Validity Check Misses Incomplete FTB 3532

**Data Location:**

**Comment by DodgerDave** [comment]
Relationship wasn't carrying if qualifier wasn't claimed as a dependent.  Fixed that.  SSN is carrying.  Estimated income of qualifier isn't entered in federal so there is nothing to carry.
