### ISSUE TITLE
Wintax 2018 - Form 4952 - Investment Interest Adjustment Not Working

### ISSUE THREAD

**Issue by twgenie** [TaxwareSupport/Issue-Reports#215]
**Client Name:**  
?
**Client ID:**  
?
**Description:**  
I put in an adjustment and it does not calculate.
 
**Reproduce:**  
Form 4952 -> [01] Enter Value and adjustment -> Push 'Ok' -> Line [01] does not change

**Comment by DodgerDave** [comment]
Fixed 2-12
