### ISSUE TITLE
Montana Itemized deduction is doubling 

### ISSUE THREAD

**Issue by TwZach** [TaxwareSupport/Issue-Reports#216]
**Client Name:**  
Michele
**Client ID:**  
26009
**Description:**  
When entering MT Itemized deduction the total deduction is doubling
**Reproduce:**  
Open client -> open Montana -> line 16 Itemized deduction -> enter amount on line 600 -> Preview
![image](https://user-images.githubusercontent.com/45858181/52439855-6dca0b80-2ad1-11e9-8991-82772f77b108.png)

**Data Location:**

**Comment by twJorge** [comment]
Fixed
