### ISSUE TITLE
2018 Wintax -> MO State -> Montana Additional Dependent Worksheet -> Calculates Correctly but Dependent Not Listed in Print/Preview

### ISSUE THREAD

**Issue by twnathan** [TaxwareSupport/Issue-Reports#218]
**Client Name:**  
JOSEPH R BALYEAT

**Client ID:**  
21493

**Description:**  
Client filing for Montana taxpayer family with four children. The main MO form only has room for three, requiring the use of the additional dependent overflow sheet. The client has entered in the dependent and information and has seen that the form is calculating all four dependents correctly, but the preview/print does not list the fourth dependent on the additional dependent overflow sheet.

**Reproduce:**  
2018 Wintax -> MO State -> TP with 4 children -> Room for 3 on Main Form -> Montana Additional Dependent Worksheet -> Calculates Correctly but Dependent Not Listed in Print/Preview

**Data Location:**

**Comment by twJorge** [comment]
Fixed.
