### ISSUE TITLE
NextGen - Tax Planning - Complete and Locked Status breaks tax planning.

### ISSUE THREAD

**Issue by MHGray** [TaxwareSupport/Issue-Reports#22]
**Client Name:**  
Brenda

**Client ID:**  
87133

**Description:**  
If you had a previously Complete and Locked return and want to get into Tax Planning you need to change status on summary screen to something else and then you can click Tax Planning, but doing so starts the tax plan as complete and locked. Tax Planning should never be initialized as complete and locked.

**Reproduce:**  
On a return that hasn't had a tax planning done. Go to summary and set to complete and locked. Go to forms and schedules. Go back to summary screen. Tax planning button is locked so change status to information pending. Open Tax Planning. Tax planning is locked.

**Comment by DodgerDave** [comment]
Fixed on 9-7.  Will go on next patch.
