### ISSUE TITLE
2018 Wintax -> CA Reject -> Your State submission does not match the latest published FTB Schema or is not well formed

### ISSUE THREAD

**Issue by twnathan** [TaxwareSupport/Issue-Reports#223]
**Client Name:**  
STEVE WILLIAMS

**Client ID:**  
9913

**Description:**  
Client received the following CA state reject: "Your State submission does not match the latest published FTB Schema or is not well formed. You must contact your software provider to resolve this error.

Hard copy of reject to be submitted with printed report. Client data located below.

**Reproduce:**  
2018 Wintax -> CA Reject -> Your State submission does not match the latest published FTB Schema or is not well formed

**Data Location:**
R:\Nathan\9913 - STEVE WILLIAMS - CA Reject for Out of Date State Schema

**Comment by MHGray** [comment]
Every CA schema reject comes with that notice. Not sure what the particular issue they are having as there are no files matching that in R:\Nathan
