### ISSUE TITLE
Suggestion: 2018 Wintax -> Misc Features -> Add Back in "Backup by Series" Function (per Legacy program)

### ISSUE THREAD

**Issue by twnathan** [TaxwareSupport/Issue-Reports#225]
**Client Name:**  
NORMAN A. JENKS

**Client ID:**  
7670-1

**Description:**  
Client prepares taxes both in the office and at client's homes. For this reason, his client data is setup to be mobile as well. Before he leaves the office to do house calls or work on returns from home he will backup select ranges of clients onto his laptop. In Legacy there was a feature to "Backup a series" of client IDs, and with the volume of taxpayers that the client services, this feature would save him some time.

I setup a shortcut to his data folder on his desktop and showed him how to backup select client data through File Explorer. He did say that would be good (for now) but he would still hope to have that functionality placed back inside the program. 

**Reproduce:**  

**Data Location:**

**Comment by MHGray** [comment]
File explorer is the way to go. I would much prefer we remove our backup feature entirely unless we put in more safe guards so people won't overwrite their entire datapath.
