### ISSUE TITLE
Wintax - 8867 not checking anything for line 11

### ISSUE THREAD

**Issue by MHGray** [TaxwareSupport/Issue-Reports#228]
**Client Name:**  
Bay

**Client ID:**  
2690-1

**Description:**  
On this particular client data it is not printing the checkbox for line 11
![image](https://user-images.githubusercontent.com/8196735/52524135-857ace80-2c4e-11e9-9875-1ee86c5883f0.png)
![image](https://user-images.githubusercontent.com/8196735/52524144-9fb4ac80-2c4e-11e9-8d21-10f0fbf28aa3.png)

**Reproduce:**  
Use data provided

**Data Location:**
R:\Matt\8867MissingCheckbox

**Comment by DodgerDave** [comment]
Fixed 2-12
