### ISSUE TITLE
Wintax - Arkansas - Won't let you leave with out killing your direct deposit info

### ISSUE THREAD

**Issue by MHGray** [TaxwareSupport/Issue-Reports#229]
**Client Name:**  
??

**Client ID:**  
??

**Description:**  
 Trying to leave AR with direct deposit information is impossible thanks to a terminator pop-up window.

**Reproduce:**  
AR -> put in Direct Deposit info -> Try to get back to the summary with Direct Deposit intact

**Comment by twJorge** [comment]
Calculation was firing twice. Moved Direct Deposit after both calculations.
