### ISSUE TITLE
Sch B interest is not appearing on Sch A  

### ISSUE THREAD

**Issue by TwZach** [TaxwareSupport/Issue-Reports#230]
**Client Name:**  
David Jones
**Client ID:**  
5980
**Description:**  
If you input a Sch B and carry to a Sch A the interest from Sch B does not appear on the Sch A, and it wont show adjustments either. 
![image](https://user-images.githubusercontent.com/45858181/52576819-bafdf400-2dd5-11e9-93bc-0c24762c4653.png)
![image](https://user-images.githubusercontent.com/45858181/52576797-b20d2280-2dd5-11e9-983a-a02420ede1a8.png)

**Reproduce:**  
open return -> add sch b interest income -> open sch A -> line 46 -> line 3 -> there is an amount there but it does not appear on the preview. 

**Data Location:**

**Comment by DodgerDave** [comment]
Fixed 2-12
