### ISSUE TITLE
Mississippi return puts pensions and annuities in return for Non-resident when it shouldn't

### ISSUE THREAD

**Issue by TwZach** [TaxwareSupport/Issue-Reports#231]
**Client Name:**  
David
**Client ID:**  
5980
**Description:**  
Mississippi line 46 has amount when the client is a non-resident but not when they are set to resident. Client says that it shouldn't. 
**Reproduce:**  
see client data -> preview return -> line 46 -> set to resident -> preview return -> line 46
**Data Location:**
R:\Zac\2018clientdata\5980clientdata

**Comment by MHGray** [comment]
Data no longer Available. Assuming this was fixed.
