### ISSUE TITLE
Wintax Validation Error for Care of Name

### ISSUE THREAD

**Issue by twsal** [TaxwareSupport/Issue-Reports#234]
Craig Thomas

21315  

The program is giving a validation error, It's coming out with "Validation Error: The 'http://www.irs.gov/efile:InCareOfNm' element is invalid - The value '%' is invalid according to its datatype 'http://www.irs.gov/efile:InCareOfNameType' - The Pattern constraint failed.XPath: Return\ReturnHeader\Filer\InCareOfNm\Location of error: Line number 25 at position 22.", even if there is name written on the correct line and correct information, it still flags it as an error.

![care](https://user-images.githubusercontent.com/44677096/52584995-7af43c80-2de8-11e9-9b10-dc33254e80e7.JPG)

![bug issue](https://user-images.githubusercontent.com/44677096/52585003-7fb8f080-2de8-11e9-8e4e-d57323ae1657.JPG)

R:\Sal\craig thomas 21315

**Comment by MyNameIsDonovan** [comment]
have the client go in and out of the last name field
