### ISSUE TITLE
Montana input is not keeping additions line 1

### ISSUE THREAD

**Issue by TwZach** [TaxwareSupport/Issue-Reports#237]
**Client Name:**  
Joseph
**Client ID:**  
21493
**Description:**  
when inputting Montana if you input an amount in additions line 1 it disappears when you exit additions. Also the calculations for this line are pulling the full amount from line 22 Montana taxable income from your 2017 form 2.
**Reproduce:**  
Open client data -> open Montana -> open line 13 additions -> enter amount on line 1 -> exit additions -> open additions amount is gone -> line 16-22 -> data shows amount on line 22 same amount appears on line 1. 
**Data Location:**
R:\Zac\2018clientdata\21493clientdata

**Comment by MHGray** [comment]
Assumed fixed.
