### ISSUE TITLE
Wintax - Due Diligence - Additional Questions acting oddly

### ISSUE THREAD

**Issue by MHGray** [TaxwareSupport/Issue-Reports#238]
**Client Name:**  
Sam

**Client ID:**  
21663

**Description:**  
In due diligence additional questions, when first going into the additional questions if the questions are locked they can still click in and edit the questions. 

Also, if you use mouse-free while the questions are locked you suddenly are forced to answer every single question rapid fire. If you mess up you have to go and answer all 9 questions again.

**Reproduce:**  
due diligence -> Additional Questions (with questions already locked) -> click into box [01] and type
From the same portion go into mouse free and type [01] to answer a question

**Comment by MHGray** [comment]
The first part is fixed, but the second part is still happening where if you go to answer one, you have to answer all of them.

**Comment by DodgerDave** [comment]
Fixed 5-7
