### ISSUE TITLE
IN State -> [03] Deductions -> [02] Residential Homeowner's Property Tax deduction -> Enter Value & Info -> Finish IN Return -> Validation Error for Property Tax -> Exit/Re-enter Return -> Validation Error Resolved

### ISSUE THREAD

**Issue by twnathan** [TaxwareSupport/Issue-Reports#239]
**Client Name:**  
RUTHANN MC CLAIN

**Client ID:**  
21815

**Description:**  
Client reported inputting the property tax deduction for IN state and receiving a validation error that only resolved once they completely exited the return and then re-entered the return.

**Reproduce:**  
IN State -> [03] Deductions -> [02] Residential Homeowner's Property Tax deduction -> Enter Value & Info -> Finish IN Return -> Validation Error for Property Tax -> Exit/Re-enter Return -> Validation Error Resolved

Unable to reproduce on tech computer

**Data Location:**

**Comment by MHGray** [comment]
I can reproduce it on my system (client 76). It is asking for an address if different than the return address, so I left return address blank. It gives 
![image](https://user-images.githubusercontent.com/8196735/52678997-672fff80-2ee8-11e9-94fb-9b55c91d3c6c.png)
![image](https://user-images.githubusercontent.com/8196735/52679015-78790c00-2ee8-11e9-8d6c-90f5466d0a95.png)
