### ISSUE TITLE
NextGen - Recall Prior - Mouse-Free doesn't work on Driver's License carry over.

### ISSUE THREAD

**Issue by MHGray** [TaxwareSupport/Issue-Reports#24]
**Client Name:**  
Enrique

**Client ID:**  
22022

**Description:**  
The Mouse-Free input on the Driver's License copy doesn't work correctly. Pressing * doesn't bring you to mouse free and instead type * into the input box (I don't think any of the boxes should accept * as a value but I may be wrong.) typing in the line number into mouse free doesn't take you to that line either. Only 99 and / seem to register. 

**Reproduce:**  
Recall prior and try to use mouse free.

**Comment by MyNameIsDonovan** [comment]
I just fixed it.
