### ISSUE TITLE
QBI deductions is carrying Sch E loss incorrectly?

### ISSUE THREAD

**Issue by TwZach** [TaxwareSupport/Issue-Reports#241]
**Client Name:**  
David
**Client ID:**  
9753
**Description:**  
Looking at the QBI Sch E loss carries line 22 from Sch E instead of line 21.
**Reproduce:**  
open client data -> open QBI -> first Sch E -> open first schedule E -> preview -> look at lines 21 and 22 
**Data Location:**
R:\Zac\2018clientdata\9753clientdata

**Comment by MHGray** [comment]
Assumed Fixed
