### ISSUE TITLE
2018 Wintax -> W2 Entry -> W2 Verification coming up after entering State return (long after W2 section has been entered)

### ISSUE THREAD

**Issue by twnathan** [TaxwareSupport/Issue-Reports#243]
**Client Name:**  
BARREY H. STAGGS, CPA

**Client ID:**  
87191

**Description:**  
Client has reported this issue multiple times between the past couple of years.

W2 Verification (which has some sort of interfacing issue with direct deposit? -- he was unclear) does not come up on screen until after he has been prompted to go into the state return, complete it and then the W2 Verification comes up. He is frustrated that the W2 verification does not come up earlier, immediately following exiting the W2 entry.

**Reproduce:**  
2018 Wintax -> W2 Entry -> W2 Verification coming up after entering State return (long after W2 section has been entered)

**Data Location:**

**Comment by MHGray** [comment]
Already told the workaround for that. It is in the same place it was last year, but the state prompt setting he has comes up before the W2 verification.
