### ISSUE TITLE
CA 541 fiduciary is not carrying line 22 to line 24

### ISSUE THREAD

**Issue by TwZach** [TaxwareSupport/Issue-Reports#245]
**Client Name:**  
Kathy
**Client ID:**  
10723
**Description:**  
The line 21 the exemption credit plus line 22 credits is supposed to be on line 24, client is getting rejected because line 24 is blank
![image](https://user-images.githubusercontent.com/45858181/52659648-a17eaa00-2eb2-11e9-8b81-8fa6c59a7d7e.png)

**Reproduce:**  
Open fiduciary return -> open Ca -> open line 4 credits -> line 4 has number 1 -> preview CA return ->  line 21-24 not correctly added. 
**Data Location:**

**Comment by MHGray** [comment]
Assumed Fixed
