### ISSUE TITLE
Wintax - Estimates producing invalid date type on xml

### ISSUE THREAD

**Issue by MHGray** [TaxwareSupport/Issue-Reports#246]
**Client Name:**  
Debbi

**Client ID:**  
6830

**Description:**  
![image](https://user-images.githubusercontent.com/8196735/52662391-f0c7d900-2eb8-11e9-837d-d96228fed6e0.png)
![image](https://user-images.githubusercontent.com/8196735/52662418-ffae8b80-2eb8-11e9-9d3c-b7b3c230bb82.png)
It is pulling the date in the wrong format on estimates

**Reproduce:**  
Put in Estimates and try a fed schema validation

**Comment by DodgerDave** [comment]
Fixed 2-12
