### ISSUE TITLE
Wintax - CA - Electronic Debit showing and bringing in wrong withdrawl dates

### ISSUE THREAD

**Issue by MHGray** [TaxwareSupport/Issue-Reports#247]
**Client Name:**  
Debbie

**Client ID:**  
6830

**Description:**  
![image](https://user-images.githubusercontent.com/8196735/52662565-65027c80-2eb9-11e9-82e8-bacf77e0475f.png)

**Comment by DodgerDave** [comment]
Fixed 2-12
