### ISSUE TITLE
MO County code and school district code are in the wrong places

### ISSUE THREAD

**Issue by TwZach** [TaxwareSupport/Issue-Reports#248]
**Client Name:**  
doug
**Client ID:**  
88172
**Description:**  
Missouri County 4 letter code/name is printing in the "In Care Of Name" box (approx. 2/3 of the way down page 1) of the MO-1040
School district code number is printing in the "County of Residence" box (bottom of page 1) of the MO-1040
**Reproduce:**  
start client -> MO -> basic info -> line 2 -> line 3 -> preview 
![image](https://user-images.githubusercontent.com/45858181/52672669-5de86800-2ed3-11e9-9f90-99e620b91b97.png)

**Data Location:**

**Comment by MHGray** [comment]
Assume Fixed
