### ISSUE TITLE
MN line M1PR line 31 has the wrong amount 

### ISSUE THREAD

**Issue by TwZach** [TaxwareSupport/Issue-Reports#249]
**Client Name:**  
Susan

**Client ID:**  
407-86

**Description:**  
On line 31 of M1PR in Minnesota the amount 4050 is appearing instead of 4150
![image](https://user-images.githubusercontent.com/45858181/52673660-3f37a080-2ed6-11e9-9090-dd7eb5ab121d.png)

**Steps to Reproduce:**  
Open client -> set age to before 1954 -> open MN -> line 27 -> check line 1 -> form print -> form M1PR -> line 31 

**Data Location:**

**Comment by MHGray** [comment]
Assume Fixed
