### ISSUE TITLE
Wintax next gen - billing set up is checking incorrectly

### ISSUE THREAD

**Issue by TwZach** [TaxwareSupport/Issue-Reports#251]
**Client Name:**  
Barry

**Client ID:**  
87191

**Description:**  
If you exit the program with line 10 in billing set up checked, then when you enter the program line 11 is checked instead. 

**Steps to Reproduce:**  
open program -> defualts -> billing set up -> check line 10 -> uncheck line 11 -> exit program -> open program -> they have switched.

**Data Location:**

**Comment by MyNameIsDonovan** [comment]
fixed
