### ISSUE TITLE
Wintax - ACA - Has no ACA penalties but should and I have no idea why

### ISSUE THREAD

**Issue by MHGray** [TaxwareSupport/Issue-Reports#254]
**Client Name:**  
Guillermo

**Client ID:**  
28011

**Description:**  
Has client that should be getting ACA penalty but isn't and I have no idea why. Causes reject.

**Data Location:**
R:\Matt\ACANoPenalty

**Comment by DodgerDave** [comment]
Preparer mistakenly chose "Dependent of another" as special category.
