### ISSUE TITLE
Wintax - 8283 - Reading from charity.dbf instead of lookup.db3

### ISSUE THREAD

**Issue by MHGray** [TaxwareSupport/Issue-Reports#256]
**Client Name:**  
Donald

**Client ID:**  
152-86

**Description:**  
8283 transactions F5 menu are reading from Charity.dbf instead of lookup.db3. 

**Steps to Reproduce:**  
Sch A -> [50]8283 -> [01]Add -> F5 on line [02]

**Comment by MyNameIsDonovan** [comment]
fixed
