### ISSUE TITLE
Wintax - Pub 523/Sch D - Can't delete pub 523 entries from schedule D

### ISSUE THREAD

**Issue by MHGray** [TaxwareSupport/Issue-Reports#258]
**Client Name:**  
Sam

**Client ID:**  
99081-1

**Description:**  
Had 523 entry. Carried to Sch D. Deleted 523 entry. Sch D entry still there. Can't delete the entry, says to go to 523 and delete. 523 doesn't exist.
![image](https://user-images.githubusercontent.com/8196735/52753412-614f2280-2fab-11e9-9d57-c39f9700ae22.png)
![image](https://user-images.githubusercontent.com/8196735/52753422-6d3ae480-2fab-11e9-92a2-08b57f915651.png)

**Steps to Reproduce:**  
Add 523 -> Check Sch D -> Delete 523 -> Check Sch D -> Try and Delete -> you can't

**Data Location:**
R:\Matt\Pub523Undeletable

**Comment by MyNameIsDonovan** [comment]
I have banished the SchD entries to the nether realm. Also fixed the issue that cause it in the first place
