### ISSUE TITLE
SUGGESTION 2018 Wintax - Summary - Mousefree cursor needs to be replaced via mouse after entering/exiting state return

### ISSUE THREAD

**Issue by twnathan** [TaxwareSupport/Issue-Reports#260]
**Client Name:**  
DAVID JONES

**Client ID:**  
5980

**Description:**  
Client would like mousefree functionality immediately following exiting a state return on the Summary screen without having to re-click the mousefree section

**Steps to Reproduce:**  
2018 Wintax -> Summary -> Enter/Exit State Return -> Mousefree cursor needs to be replaced via mouse click

**Data Location:**

**Comment by MHGray** [comment]
Pushing '*' after coming from a legacy state will put them back into mouse-free. This minor issue will resolve itself once all the states are converted over because it doesn't happen with NG states.
