### ISSUE TITLE
Wintax next gen only prints consolidated on the first 1040

### ISSUE THREAD

**Issue by TwZach** [TaxwareSupport/Issue-Reports#261]
**Client Name:**  
Missy

**Client ID:**  
2450

**Description:**  
If you print the return with two copies for 1040 only the first 1040 is consolidated .

**Steps to Reproduce:**  
open return -> print set up -> set 2 copies for 1040 -> print -> select consolidated

**Data Location:**

**Comment by MHGray** [comment]
No longer relevant
