### ISSUE TITLE
Wintax - Miscellaneous Schedules - Not Printing

### ISSUE THREAD

**Issue by twsal** [TaxwareSupport/Issue-Reports#263]
Edward

11073

When trying to print out a Miscellaneous schedule, from the form print, it keeps getting a message saying,"Nothing to Preview". 

![5](https://user-images.githubusercontent.com/44677096/52801302-6d31f780-3032-11e9-8b07-ef76cbbd80a1.JPG)

![6](https://user-images.githubusercontent.com/44677096/52801308-70c57e80-3032-11e9-9277-927ef869b6c8.JPG)

![7](https://user-images.githubusercontent.com/44677096/52801317-74f19c00-3032-11e9-9bf1-4c4bdef06c8f.JPG)
 

R:\Sal\Edward 11073

**Comment by MyNameIsDonovan** [comment]
Fixed this. Found another issue where closing the program and entering the client would make them disappear.
