### ISSUE TITLE
EIC not carrying to DC for the client 

### ISSUE THREAD

**Issue by TwZach** [TaxwareSupport/Issue-Reports#265]
**Client Name:**  
Sam 

**Client ID:**  
20190

**Description:**  
The client data is not carrying EIC to DC.

**Steps to Reproduce:**  
open client data -> line input -> EIC is there -> Open DC -> line 17-19 did not carry eic

**Data Location:**
R:\Zac\2018clientdata\20190clientdata

**Comment by MHGray** [comment]
Seems fixed.
