### ISSUE TITLE
NY refund is showing contradictory amounts

### ISSUE THREAD

**Issue by TwZach** [TaxwareSupport/Issue-Reports#266]
**Client Name:**  
ken

**Client ID:**  
99016

**Description:**  
Clients NY refund is different when you look at the actual form, or the direct deposit, the letter and the filing instructions. 

**Steps to Reproduce:**  
open client data -> preview return

**Data Location:**
R:\Zac\2018clientdata\99016clientdata

**Comment by DodgerDave** [comment]
Fixed sometime in the past, I just forgot to comment and close it.
