### ISSUE TITLE
Wintax ACA 8962 has the wrong AGI

### ISSUE THREAD

**Issue by TwZach** [TaxwareSupport/Issue-Reports#267]
**Client Name:**  
213145

**Client ID:**  
Louis

**Description:**  
The AGI for the client on the 8962 is 20,000 more than it is supposed to be. 
![image](https://user-images.githubusercontent.com/45858181/52820536-1b549600-3061-11e9-9cd1-c8e6b4524d7c.png)
![image](https://user-images.githubusercontent.com/8196735/53602915-f71aae00-3b64-11e9-8f4b-2e9cba444aba.png)

**Steps to Reproduce:**  
Open client data -> line input -> aca wizard -> 8962 -> preview

**Data Location:**
R:\Zac\2018clientdata\21345clientdata

**Comment by DodgerDave** [comment]
This is the correct modified AGI according to worksheet 1-1 on page 6 of 8962 instructions.
