### ISSUE TITLE
Wintax - Legacy - 18 Legacy considers itself as 17 causing errors opening state if 17 is open

### ISSUE THREAD

**Issue by MHGray** [TaxwareSupport/Issue-Reports#270]
**Client Name:**  
Fely

**Client ID:**  
Ticket 23470

**Description:**  
2018 Legacy thinks it is the 17 program so causes the following error if you try to open the state while the 17 legacy is open.
![image](https://user-images.githubusercontent.com/8196735/52827293-0dab0a80-3079-11e9-9c3b-62629dc002f9.png)

**Steps to Reproduce:**  
Open 17 legacy -> open 18 NextGen -> enter Hawaii State -> Error message above appears

**Comment by MyNameIsDonovan** [comment]
fixed
