### ISSUE TITLE
2018 Wintax - MT Return - No Function to Select Different Filing Status for 2017 Data Reported on 2018 Return

### ISSUE THREAD

**Issue by twnathan** [TaxwareSupport/Issue-Reports#271]
**Client Name:**  
KASEY @ MICHELE M AYERS

**Client ID:**  
26009

**Description:**  
Client has a taxpayer who filed Married Joint in 2017 and is filing Married Separate on Same Form this year. In the MT return -> [13] Additions to Income -> Recovery of federal income tax deduction in 2017 [17] - [23] you have to report 2017 return data, however the program is assuming deductions based off the current 2018 filing status (Married Separate on Same Form) instead of the 2017 filing status (Married Joint) and there is not a function to toggle this in the program. The client is manually altering the numbers in order to workaround.

Jorge is already aware and is working on it

![image](https://user-images.githubusercontent.com/44508876/52872225-c9fbe380-3100-11e9-88ec-c929b3c5dbe2.png)

**Steps to Reproduce:**  
2018 Wintax -> MT return -> [13] Additions to Income -> Recovery of federal income tax deduction in 2017 [17] - [23]

**Data Location:**

**Comment by twJorge** [comment]
Fixed
