### ISSUE TITLE
2018 Wintax - MT Form-IT - Print/Preview Only TP w/ TP Value but not Spouse Voucher/Value

### ISSUE THREAD

**Issue by twnathan** [TaxwareSupport/Issue-Reports#275]
**Client Name:**  
KASEY @ MICHELE M AYERS CPA

**Client ID:**  
26009

**Description:**  
Only printing one payment voucher for Taxpayer, and only for the Taxpayer's value -- the Spouse's voucher does not print/preview and the Spouse's total is not combined with the one payment voucher that is printing/previewing.

We need to print one each for the TO and SP or combine the two values from TP and SP on one payment voucher.

**Steps to Reproduce:**  
MT Return with TP and SP who both owe on MT Return -> Preview/Print MT Form-IT

**Data Location:**

**Comment by twJorge** [comment]
Fixed, value has been combined.
