### ISSUE TITLE
Wintax Sch SE is not calculating correctly

### ISSUE THREAD

**Issue by TwZach** [TaxwareSupport/Issue-Reports#278]
**Client Name:**  
Kasey

**Client ID:**  
26009

**Description:**  
Line 15 on sch SE is not inputting correct amount.
![image](https://user-images.githubusercontent.com/45858181/52966513-52c28b80-335c-11e9-93ca-08b432c1cee6.png)
![image](https://user-images.githubusercontent.com/45858181/52966550-6c63d300-335c-11e9-9744-a28d36ad4f93.png)
**Steps to Reproduce:**  
Open client data -> Sch SE -> preview -> page 2 -> Sch F -> 

**Data Location:**
R:\Zac\2018clientdata\26009clientdata

**Comment by DodgerDave** [comment]
Fixed 2-18
