### ISSUE TITLE
Wintax 1040-nr filing status selction is not working

### ISSUE THREAD

**Issue by TwZach** [TaxwareSupport/Issue-Reports#279]
**Client Name:**  
Dae

**Client ID:**  
8957

**Description:**  
In the 1040nr the filing category select is not working, selecting single selects married, and selecting married or widow populates notbound.

**Steps to Reproduce:**  
open return -> 1040nr -> filing category

**Data Location:**

**Comment by twJorge** [comment]
Fixed, selection was wrong.
