### ISSUE TITLE
Partnership - CA 568 - Sch K1 Carry

### ISSUE THREAD

**Issue by twsal** [TaxwareSupport/Issue-Reports#281]
Kathy

10723

State does not carry the K1 correct amount from the FED to the "capital account for the beginning of the year" and for the "capital account at end of the year".

![k1](https://user-images.githubusercontent.com/44677096/52972411-ae4a4480-336f-11e9-90cd-63a9a9c77346.JPG)

![k2](https://user-images.githubusercontent.com/44677096/52972413-b1ddcb80-336f-11e9-8528-a582086fd135.JPG)

R:\Sal\kathy 10723

**Comment by MHGray** [comment]
Calculates from the CA M2 line 1 * K1 %. Correct according to programmer
