### ISSUE TITLE
Wintax Maryland is calculating EIC when it shouldn't

### ISSUE THREAD

**Issue by TwZach** [TaxwareSupport/Issue-Reports#283]
**Client Name:**  
Hugo

**Client ID:**  
12583

**Description:**  
Client is receiving maryland EIC when they shouldn't 

**Steps to Reproduce:**  
open client data -> open MD -> Preview return EIC is there
![image](https://user-images.githubusercontent.com/45858181/52979745-d6e03780-338b-11e9-9cee-4499b7c97764.png)

**Data Location:**
R:\Zac\2018clientdata\12583clientdata

**Comment by DodgerDave** [comment]
Fixed 2-18
