### ISSUE TITLE
Wintax - Montana - Not Carrying over Spouse Info

### ISSUE THREAD

**Issue by twsal** [TaxwareSupport/Issue-Reports#284]
Joseph

21493  

State is only carrying the amounts for the taxpayer, but not the amounts for the spouse from the FED. The incorrect carry is causing the refund amount to show the taxpayer gets 298 back and for the spouse it's shows them owe an amount of 580. Overall should equal to an amount of 282, since its being filed as a married joint return.  This is also showing as well in the cover pages for clients, billing, etc. Can't remove any overrides once they are added.

![montana](https://user-images.githubusercontent.com/44677096/52979521-d98e5d00-338a-11e9-8bc7-c56e9b3ba6d0.JPG)

![montana 2](https://user-images.githubusercontent.com/44677096/52980311-5b33ba00-338e-11e9-848b-e3a13f5e0d08.JPG)

R:\Sal\joseph 21493

**Comment by twJorge** [comment]
Fixed
