### ISSUE TITLE
Wintax Alabama 40NR line 5 all sources is not carrying properly

### ISSUE THREAD

**Issue by TwZach** [TaxwareSupport/Issue-Reports#287]
**Client Name:**  
David

**Client ID:**  
Jones

**Description:**  
Line 5 all sources is not carrying all of the income or is carrying incorrectly
![image](https://user-images.githubusercontent.com/45858181/53036540-caf88200-342c-11e9-907b-d2dd7cda0f18.png)
![image](https://user-images.githubusercontent.com/45858181/53036625-f9765d00-342c-11e9-9883-81d1a69cc911.png)

**Steps to Reproduce:**  
open client data -> access Alabama -> preview state return -> page 1 and page 3

**Data Location:**
R:\Zac\2018clientdata\5980clientdata2

**Comment by MHGray** [comment]
Assume Fixed
