### ISSUE TITLE
Wintax - 1116 - Form produces credit of 81 even when credit should be 18

### ISSUE THREAD

**Issue by MHGray** [TaxwareSupport/Issue-Reports#289]
**Client Name:**  
Jobel

**Client ID:**  
9913

**Description:**  
This client has form 1116 with a credit of $18. However the 1040 is showing a credit of 81. Deleting the 1116 does not remove the credit. Changing the values to make it higher than 81 does not change the amount either. They have no override for the 1116. 

**Steps to Reproduce:**  
Use Data Provided

**Data Location:**
R:\Matt\9913Form1116

**Comment by DodgerDave** [comment]
Was using value from Sch B input.
