### ISSUE TITLE
Wintax NextGen - Form 1116 - Input Screen [01] Category of Income Selection Off by 2 & Preview Incorrect

### ISSUE THREAD

**Issue by twnathan** [TaxwareSupport/Issue-Reports#298]
**Client Name:**  
RUBY POIREL

**Client ID:**  
3830

**Description:**  
Upon entering the Form 1116 input screen, [01] Category of Income selection is off by 2 (both mouse and mouse-free). This error flows through with errors on the preview as well where if I select one category of income on the input screen, a different category of income is selected on the preview. This also affects how the rest of the form is calculated and which figures appear or do not appear.

![image](https://user-images.githubusercontent.com/44508876/53125695-6a904000-3513-11e9-82e9-6df7fffa6ca3.png)

![image](https://user-images.githubusercontent.com/44508876/53125713-74b23e80-3513-11e9-89e0-be4eff803443.png)

**Steps to Reproduce:**  
Wintax NextGen -> Forms and Schedules -> Form 1116 - Foreign Tax Credit -> Form 1116 (Input) -> [01] Category of Income selection -> Fill out values and preview as well

**Data Location:**

**Comment by DodgerDave** [comment]
Fixed a couple days ago.
