### ISSUE TITLE
Wintax - Montana issues

### ISSUE THREAD

**Issue by TwZach** [TaxwareSupport/Issue-Reports#299]
**Client Name:**  
Kasey

**Client ID:**  
26009

**Description:**  
Montana spouse is not carrying interest to Social Security 
montana  additions has a 2 there when it shouldn't
Spouse is not added for under-payment penalties
3rd party designee is not checking
cannot change prior year filing status

**Steps to Reproduce:**  

**Data Location:**
R:\Zac\2018clientdata\26009clientdata2

**Comment by twJorge** [comment]
Fixed
