### ISSUE TITLE
2018 Wintax - Form 2210 - QBI Deduction Validation Error for 3rd Annualized Income Period but not 1st, 2nd or 4th

### ISSUE THREAD

**Issue by twnathan** [TaxwareSupport/Issue-Reports#302]
**Client Name:**  
BRENDA BOTIZAN

**Client ID:**  
87133

**Description:**  
Client has input [03] Deduction for qualified business income across all four periods as both different values and the same value and the validation error only targets the 3rd Period. The XML points to there being a multitude of potentially missing items, including Installment Deduction Amount. Installment Deduction Amount is the only value that appears under Periods 1, 2 and 4, but not Period 3. This may be where the issue is located.

![image](https://user-images.githubusercontent.com/44508876/53193148-2493b480-35c5-11e9-8673-ad7ffe729005.png)
![image](https://user-images.githubusercontent.com/44508876/53193221-5ad13400-35c5-11e9-8c43-fd82e67ff10e.png)

**Steps to Reproduce:**  

**Data Location:**
R:\Nathan\87133 - BRENDA BOTIZAN - Form 2210 QBI Deduction Error

**Comment by DodgerDave** [comment]
Fixed 2-21.
