### ISSUE TITLE
2018 Wintax - Section B-Long Schedule SE - Negative Value on Form Line 3 not Carrying to Form Line 4a, Downstream Values on Form Incorrect 

### ISSUE THREAD

**Issue by twnathan** [TaxwareSupport/Issue-Reports#309]
**Client Name:**  
KASEY @ MICHELE M AYERS CPA

**Client ID:**  
26009

**Description:**  
Section B-Long Schedule SE not carrying negative values from Form Line 3 to Form Line 4a and it is throwing off the rest of the values on the form downstream.

![image](https://user-images.githubusercontent.com/44508876/53273481-f4bddd00-36a8-11e9-80c0-4441aec6c422.png)

**Steps to Reproduce:**  
2018 Wintax -> Schedule SE Input -> Generate Negative Value on Form Lines 2 & 3 -> Preview Long Schedule SE

**Data Location:**
R:\Nathan\26009 - KASEY @ MICHELE M AYERS - Long Schedule SE Negative Value to 4a Issue

**Comment by DodgerDave** [comment]
Fixed 2-25
