### ISSUE TITLE
2018 Wintax - LA - Louisiana Misspellings

### ISSUE THREAD

**Issue by twnathan** [TaxwareSupport/Issue-Reports#312]
**Client Name:**  
BRENDA @ YVONNE C VERNON's Office

**Client ID:**  
91160

**Description:**  
Misspelling #1 - Affects Billing and prints incorrectly as well
![image](https://user-images.githubusercontent.com/44508876/53279012-ff38a080-36c1-11e9-8057-70117fbb4e28.png)

Misspelling #2 - Lists Missouri Instead of Louisiana
![image](https://user-images.githubusercontent.com/44508876/53278998-e4fec280-36c1-11e9-8cf4-8081c9c9862d.png)

**Steps to Reproduce:**  

**Data Location:**

**Comment by twJorge** [comment]
Typo fixed. No longer spelled like Missouri.
