### ISSUE TITLE
2018 Wintax - LA - LA Return Does not List Paid Preparer CSZ

### ISSUE THREAD

**Issue by twnathan** [TaxwareSupport/Issue-Reports#313]
**Client Name:**  
BRENDA @ YVONNE C VERNON's Office

**Client ID:**  
91160

**Description:**  
LA Return does not list Paid Preparer's CSZ (city, state, zip) under the Firm's Address Box on page 4. Replicated on tech computer.

![image](https://user-images.githubusercontent.com/44508876/53279173-0f04b480-36c3-11e9-98f4-c3d52076dc3d.png)

**Steps to Reproduce:**  
2018 Wintax -> Complete Prep Setup -> Apply Prep Info to FED Return -> Carry to LA -> Preview LA Return

**Data Location:**

**Comment by twJorge** [comment]
Format was approved by state, and no errors have came back from state. No changes were made.
