### ISSUE TITLE
Wintax - Arizona - Part-year resident and non-resident forms don't print

### ISSUE THREAD

**Issue by TwZach** [TaxwareSupport/Issue-Reports#314]
**Client Name:**  
lindsey

**Client ID:**  
21055

**Description:**  
If you select AZ ptyear or non-resident it still prints the resident forms

**Steps to Reproduce:**  
Open client -> AZ -> set to nonresident or part-year resident -> preview forms or return

**Data Location:**

**Comment by DodgerDave** [comment]
Fixed 2-25
