### ISSUE TITLE
Wintax-form 8903 - not carrying forward correctly 

### ISSUE THREAD

**Issue by TwZach** [TaxwareSupport/Issue-Reports#315]
**Client Name:**  
David

**Client ID:**  
5980

**Description:**  
Line 25 on 8903 is not accurate to lines 22-24 added together.
![image](https://user-images.githubusercontent.com/45858181/53349515-24036280-38d2-11e9-9c4d-0da63a3d77c1.png)

**Steps to Reproduce:**  
open client -> 8903 -> enter amount on line 8 -> preview

**Data Location:**

**Comment by DodgerDave** [comment]
Fixed 2-25
