### ISSUE TITLE
2018 Wintax - OH Schema - OH State W2 EIN & Schema Validation Issue

### ISSUE THREAD

**Issue by twnathan** [TaxwareSupport/Issue-Reports#317]
**Client Name:**  
RONALD KARADEEMA

**Client ID:**  
21667

**Description:**  
Error occurs while running OH state schema validation -- W2s appear to be completed correctly, with EIN. The error referencing something missing from the MEFELFLOGS seems to be the source of the issue. Client data attached.

![image](https://user-images.githubusercontent.com/44508876/53353460-93308500-38d9-11e9-8a9e-7c4cded68705.png)
![image](https://user-images.githubusercontent.com/44508876/53353488-ac393600-38d9-11e9-97cc-65ec415b774d.png)

**Steps to Reproduce:**  

**Data Location:**
R:\Nathan\21667 - RONALD KARADEEMA - OH W2 EIN & Schema Error

**Comment by DodgerDave** [comment]
Have to enter FEIN for state id # for MIchigan
