### ISSUE TITLE
Wintax - Ohio - Validty error for W2 

### ISSUE THREAD

**Issue by TwZach** [TaxwareSupport/Issue-Reports#319]
**Client Name:**  
veronica

**Client ID:**  
215100

**Description:**  
Validity error says 
![image](https://user-images.githubusercontent.com/45858181/53357310-6d5bae00-38e2-11e9-9104-975ae665517f.png)
 Every thing seems to be fine, though it is missing OtherDeductionsBenefitsGrp in the Xml for state

**Steps to Reproduce:**  
Open client data -> validity check for state

**Data Location:**
R:\Zac\2018clientdata\215100clientdata

**Comment by DodgerDave** [comment]
Fixed 2-25
