### ISSUE TITLE
2018 Fiduciary - CA K-1 (541) - Beneficiary's Name on Form Places Middle Initial After the Last Name

### ISSUE THREAD

**Issue by twnathan** [TaxwareSupport/Issue-Reports#321]
**Client Name:**  
ELEANOR FARASHIAN

**Client ID:**  
5250

**Description:**  
Beneficiary name, Middle Initial listed after Last Name
![image](https://user-images.githubusercontent.com/8196735/53604317-f3892600-3b68-11e9-9d48-4b0d5207ec9f.png)

**Steps to Reproduce:**  

**Data Location:**

**Comment by MHGray** [comment]
Duplicate of bug 300
