### ISSUE TITLE
2018 Wintax - Form 8839 - TP Received IRS Letter Stating that Form 8839 was Not Transmitted with Return

### ISSUE THREAD

**Issue by twnathan** [TaxwareSupport/Issue-Reports#322]
**Client Name:**  
DAVID JONES

**Client ID:**  
5980

**Description:**  
Return was completed on 1/31/19 and transmitted and accepted on 2/1/19. Taxpayer received a letter from the IRS dated 2/22 stating that Form 8839 Qualified Adoption Expenses was not transmitted along with the return. Client has already faxed the completed Form 8839 to the IRS directly. Client is concerned why this issue occurred.

**Steps to Reproduce:**  

**Data Location:**
R:\Nathan\5980 - DAVID JONES - 8839 Supposedly Did Not Transmit with FED Return

**Comment by DodgerDave** [comment]
Looks like IRS was wrong.
