### ISSUE TITLE
Wintax - Maryland MD -> EIC is not applying to the return

### ISSUE THREAD

**Issue by TwZach** [TaxwareSupport/Issue-Reports#323]
**Client Name:**  
Samuels

**Client ID:**  
20190

**Description:**  
MD EIC is not being applied to the return 
![image](https://user-images.githubusercontent.com/45858181/53429699-fb4a9e00-39a1-11e9-9702-5765d4637aa9.png)
![image](https://user-images.githubusercontent.com/45858181/53429778-203f1100-39a2-11e9-92ff-7c4863fdd5a4.png)

**Steps to Reproduce:**  
Open client data -> access MD -> Credits -> Preview return

**Data Location:**
R:\Zac\2018clientdata\20190clientdata

**Comment by DodgerDave** [comment]
Fixed 2-26
