### ISSUE TITLE
2018 Wintax - QBI - Potential QBI Miscalculation

### ISSUE THREAD

**Issue by twnathan** [TaxwareSupport/Issue-Reports#324]
**Client Name:**  
MISSY @ ED HEYLIN's Office

**Client ID:**  
2450

**Description:**  
Client receiving the following error repeatedly after many different re-calculations:
![image](https://user-images.githubusercontent.com/8196735/53604391-2c28ff80-3b69-11e9-8c59-19252b01900f.png)

I'm unsure how they and the program are generating their QBI numbers, but running my own calculations, things seem odd. The client has filed a large number of QBI returns but this one is giving them trouble. They would appreciate someone taking a closer look at their client data and explaining what is going wrong.

**Steps to Reproduce:**  

**Data Location:**
R:\Nathan\2450 - MISSY @ ED HEYLIN - Possible QBI Miscalculation

**Comment by MyNameIsDonovan** [comment]
this should be fixed
