### ISSUE TITLE
2018 Wintax - QBI - QBI Miscalculation for 199A income

### ISSUE THREAD

**Issue by twsal** [TaxwareSupport/Issue-Reports#327]
David Jones

5980

When going into the QBI, it changes the K1s 199A income, into an income loss or a lower amount for the 199A income. For example the total 199A income is 14,120, but when going into the QBI it will change it into a loss of -8,270, when it should total to the original amount.

![qbi2](https://user-images.githubusercontent.com/44677096/53439118-32c34580-39b6-11e9-81b4-8e5130af2b34.JPG)

![image](https://user-images.githubusercontent.com/8196735/53604456-6b575080-3b69-11e9-8207-e20a8d804c73.png)

R:\Sal\jones 5980

**Comment by MyNameIsDonovan** [comment]
yeah I broke this, and it should be fixed
