### ISSUE TITLE
Wintax - AZ - AZ 8879 doesn't print when AZ is a secondary state

### ISSUE THREAD

**Issue by MHGray** [TaxwareSupport/Issue-Reports#330]
**Client Name:**  
Barrey

**Client ID:**  
87191

**Description:**  
AZ 8879 only prints when AZ is the primary state. Putting it into secondary states makes it not print.

**Steps to Reproduce:**  
Summary Menu -> Add AZ -> Go back and preview 8879 -> AZ 8879 shows up -> Summary Menu -> Add CA as primary -> Preview 8879 -> no AZ 8879

**Comment by DodgerDave** [comment]
Fixed 2-26
