### ISSUE TITLE
2018 Wintax - Bank Info for Direct Deposit or Debit Worksheet - AZ Refund and Direct Deposit Info not Appearing on Direct Deposit Worksheet

### ISSUE THREAD

**Issue by twnathan** [TaxwareSupport/Issue-Reports#332]
**Client Name:**  
BARREY H. STAGGS, CPA

**Client ID:**  
87191

**Description:**  
AZ Direct Deposit info filled out on client data but the refund and bank info are not appearing on Direct Deposit Worksheet:
![image](https://user-images.githubusercontent.com/44508876/53453868-48e2fd00-39da-11e9-81b1-f0483b642849.png)
![image](https://user-images.githubusercontent.com/44508876/53453924-7af45f00-39da-11e9-874a-0c28ee8a3e41.png)

**Steps to Reproduce:**  
2018 Wintax -> FED Direct Deposit -> Carry to AZ -> AZ Direct Deposit -> Form Print -> Worksheet -> Bank Info for Direct Deposit or Debit -> Check YES -> OK -> Preview

**Data Location:**
R:\Nathan\87191 - BARREY STAGGS - AZ Bank Info Not On Worksheet

**Comment by DodgerDave** [comment]
Fixed 2-27. Have client go into AZ (don't have to carry from fed) and then it will show on bank info worksheet.
