### ISSUE TITLE
Wintax - QBI - QBI causing Tax to lower

### ISSUE THREAD

**Issue by twsal** [TaxwareSupport/Issue-Reports#335]
Bryan Carlin

99063

QBI keeps changing, (multiples the income deduction) causing the tax to lower and increase the return amount. This happens everytime you exit from forms and sch to summary window or go into the QBI form.

![1](https://user-images.githubusercontent.com/44677096/53509543-dcffa380-3a70-11e9-9209-3aa4287f3bd4.JPG)
![2](https://user-images.githubusercontent.com/44677096/53509551-df61fd80-3a70-11e9-8c9d-11624bb9be91.JPG)
![4](https://user-images.githubusercontent.com/44677096/53509556-e12bc100-3a70-11e9-89aa-a1fd6a26bfd6.JPG)
![3](https://user-images.githubusercontent.com/44677096/53509562-e2f58480-3a70-11e9-83bb-fd6b5f4766c5.JPG)

R:\Sal\Bryan 99063

**Comment by MyNameIsDonovan** [comment]
fixed
