### ISSUE TITLE
WINTAX - Form 1116 - Foreign Tax Credit Print Preview

### ISSUE THREAD

**Issue by twsal** [TaxwareSupport/Issue-Reports#337]
Bryan Carlin

99063

When previewing the 1116 form, it only carries the first section 951A income (option #1), but does not show the rest of the amounts. In this case there are four incomes added to the 1116 and when you preview all four at once or individual, they all show just the first income amounts and not their corresponding amounts.

Forms and Sch--> Form 1116-->Option #2 -->preview-->previews amounts for option #1 

![tax](https://user-images.githubusercontent.com/44677096/53512783-7f6f5500-3a78-11e9-83a0-00b3ec5ff50b.JPG)
![tax1](https://user-images.githubusercontent.com/44677096/53512785-81391880-3a78-11e9-82a5-a61b62b0d8f0.JPG)

R:\Sal\Bryan 99063

**Comment by MyNameIsDonovan** [comment]
fixed
