### ISSUE TITLE
Wintax - CA - Fed 4684 not pulling in address to XML

### ISSUE THREAD

**Issue by MHGray** [TaxwareSupport/Issue-Reports#338]
**Client Name:**  
Andries

**Client ID:**  
215102

**Description:**  
Has a 4684 on the fed to carry it to CA, but XML is missing the address causing a validation error.
![image](https://user-images.githubusercontent.com/8196735/53514012-92375900-3a7b-11e9-9b58-9ae4d8dbe11a.png)
![image](https://user-images.githubusercontent.com/8196735/53514052-aaa77380-3a7b-11e9-82ff-0110d28dd698.png)
![image](https://user-images.githubusercontent.com/8196735/53514100-c579e800-3a7b-11e9-861a-3d741ad0a8ab.png)

**Steps to Reproduce:**  
Use Data Provided

**Data Location:**
R:\Matt\CA4684

**Comment by DodgerDave** [comment]
Fixed 2-27
