### ISSUE TITLE
Winpay - DE9 & DE9C 4th Qtr Dates Incorrect

### ISSUE THREAD

**Issue by twnathan** [TaxwareSupport/Issue-Reports#34]
**Client Name:**  
Bob
**Client ID:**  
94018
**Description:**  
Winpay - DE9 & DE9C for 4th quarter, dates at top are showing 2017 in place of 2018

![image](https://user-images.githubusercontent.com/44508876/47586296-a4aa5600-d914-11e8-8f21-13eab6d1dfce.png)

![image](https://user-images.githubusercontent.com/44508876/47586343-c4da1500-d914-11e8-97fc-621710130065.png)

**Reproduce:**  
Winpay --> Reports --> Quarterly Reports --> Check Preview --> Q2 California Form DE9 --> Select Quarter: 4 --> Print (for DE9) --> OK --> [07] Print EDD Copies (for DE9C)

**Data Location:**

**Comment by MHGray** [comment]
Fixed in 1-03-19
