### ISSUE TITLE
Wintax - NJ - New jersey voucher not printing 

### ISSUE THREAD

**Issue by TwZach** [TaxwareSupport/Issue-Reports#340]
**Client Name:**  
Jerry

**Client ID:**  
99079

**Description:**  
NJ voucher gives an error when trying to print

**Steps to Reproduce:**  
open client data -> form print NJ voucher
view error log

**Data Location:**
R:\Zac\2018clientdata\99079clientdata

**Comment by DodgerDave** [comment]
Already fixed.  Must go into NJ to make it work.
