### ISSUE TITLE
Wintax - PA - PA 8879 not printing with the rest of the 8879s

### ISSUE THREAD

**Issue by MHGray** [TaxwareSupport/Issue-Reports#341]
**Client Name:**  
21168

**Client ID:**  
Allen

**Description:**  
PA doesn't print an 8879 when printing 8879 from the E-File screen. Make sure it pulls this whether PA is primary or secondary state.

**Steps to Reproduce:**  
Add PA -> Summary -> [20]E-File -> Preview 8879

**Comment by DodgerDave** [comment]
Fixed 2-27
