### ISSUE TITLE
2018 Wintax - 1040 EIC Due Diligence - TP with Seven Dependents Breaks EIC Due Diligence Page

### ISSUE THREAD

**Issue by twnathan** [TaxwareSupport/Issue-Reports#342]
**Client Name:**  
JOHNNY ARISPE

**Client ID:**  
21140

**Description:**  
TP has seven dependents and the client is try to access the EIC Due Diligence but cannot move past the OK on this pop-up:
![image](https://user-images.githubusercontent.com/44508876/53533623-6aaeb380-3ab0-11e9-96b6-7088411301be.png)

**Steps to Reproduce:**  

**Data Location:**
R:\Nathan\21140 - JOHNNY ARISPE - EIC Due Diligence with Several Dependents

**Comment by MyNameIsDonovan** [comment]
mine does not do this...

**Comment by MyNameIsDonovan** [comment]
I have altered this code. It still functions the same, but the behind the scenes is now cleaned up a bit. Hopefully this fixes whatever what causing it on the clients machines
