### ISSUE TITLE
2018 Wintax - NY IT-203 - FED to NY Non-Resident Carryover Miscalculation on Page 2, Line 1 NY State Amount

### ISSUE THREAD

**Issue by twnathan** [TaxwareSupport/Issue-Reports#343]
**Client Name:**  
DAVID JONES

**Client ID:**  
5980

**Description:**  
FED Carry to NY Non-resident Return places wages amounts here:
[09] Additional Non-Resident Data -> [02] New York State Portion of Federal AGI -> [01] Wages, salaries, tips, etc.
![image](https://user-images.githubusercontent.com/44508876/53532843-5cab6380-3aad-11e9-9d80-233342711ac6.png)
...and here:
[09] Additional Non-Resident Data -> [12] Allocation Section -> [07] Allocation of Wage and Salary -> [09] Gross wages...
![image](https://user-images.githubusercontent.com/44508876/53532858-7056ca00-3aad-11e9-8bbb-f387d0d40960.png)

However the amount on the Form IT-203 Page 2, Line 1 - New York State amount here ends up being the total of ([09] Additional Non-Resident Data -> [02] New York State Portion of Federal AGI -> [01] Wages, salaries, tips, etc.) + (the Sch A NY State allocated wage that states "THIS WILL CARRY TO IT-203 LINE1").

In this example the value would equal $125,620 instead of $25,620

![image](https://user-images.githubusercontent.com/44508876/53533789-09d3ab00-3ab1-11e9-94cb-6b416c35cc7f.png)

**Steps to Reproduce:**  
2018 Wintax -> FED Return with NY Non-Resident Income -> Carry to NY -> [09] Additional Non-Resident Data -> [02] New York State Portion of Federal AGI -> [01] Wages, salaries, tips, etc. to verify value -> OK -> [09] Additional Non-Resident Data -> [12] Allocation Section -> [07] Allocation of Wage and Salary -> [09] Gross wages... to verify values -> OK -> OK -> OK -> Preview Return from main NY Return Screen -> IT-203 Page 2 Line 1 NY value incorrect

**Data Location:**
R:\Nathan\5980 - DAVID JONES - NY Return Miscalculating the AGI

**Comment by DodgerDave** [comment]
Solution: Take 100,000 out of wages on NY state portion of Federal AGI menu.
