### ISSUE TITLE
Wintax - Virgina - reject from not attaching the other state info

### ISSUE THREAD

**Issue by TwZach** [TaxwareSupport/Issue-Reports#344]
**Client Name:**  
Janie

**Client ID:**  
20105

**Description:**  
VA is rejecting saying it is missing binary attachments, however attachment are there and showing in validity xml. But not showing in submission xml or support folders.

**Steps to Reproduce:**  
Open client -> VA Nr -> 04 credits -> 03 other state tax credit -> attach pdf -> validity check

**Data Location:**

**Comment by MyNameIsDonovan** [comment]
![image](https://user-images.githubusercontent.com/40009439/53607863-61d3e580-3b75-11e9-9b51-77cf51ab785a.png)
![image](https://user-images.githubusercontent.com/40009439/53607890-73b58880-3b75-11e9-9645-41b9bc6ac7d3.png)
![image](https://user-images.githubusercontent.com/40009439/53607904-85972b80-3b75-11e9-9ccb-2d0899c90db6.png)
Can't reproduce

**Comment by MyNameIsDonovan** [comment]
Linked to transmitting from a different machine than prepared on?
