### ISSUE TITLE
Wintax - UT - TC-40C Retirement credit picking up MFS spouse and causing reject

### ISSUE THREAD

**Issue by MHGray** [TaxwareSupport/Issue-Reports#347]
**Client Name:**  
Diane

**Client ID:**  
21392

**Description:**  
On MFS return, either spouse shouldn't show up on TC-40C or line 3 should correctly calculate the number of X's. This is also what shows on the XML causing a reject.
![image](https://user-images.githubusercontent.com/8196735/53608084-34d40280-3b76-11e9-9e30-f2bd1302415f.png)

**Steps to Reproduce:**  
Use Sample Data

**Data Location:**
R:\Matt\UT40CReject

**Comment by DodgerDave** [comment]
fixed 3-4
