### ISSUE TITLE
Wintax - VA Virginia - line 11 form 760 not calculating correctly

### ISSUE THREAD

**Issue by TwZach** [TaxwareSupport/Issue-Reports#351]
**Client Name:**  
Maria

**Client ID:**  
7510-1

**Description:**  
On Virginia form 760 line 11 is not calculating correctly from VA Sch A. 
![image](https://user-images.githubusercontent.com/45858181/53651532-b3bf4e80-3bfb-11e9-8f7a-8a9259c89a8e.png)

**Steps to Reproduce:**  
open client data -> VA -> Preview form 760 line 1, Sch A line 5

**Data Location:**
R:\Zac\2018clientdata\7510-1clientdata

**Comment by DodgerDave** [comment]
fixed
