### ISSUE TITLE
2018 Wintax - QBI - Individual Farm QBI Miscalculation Leads to FED Reject

### ISSUE THREAD

**Issue by twnathan** [TaxwareSupport/Issue-Reports#352]
**Client Name:**  
MARTHA @ BURT MARSHALL's Office

**Client ID:**  
3170

**Description:**  
Client files many FED & NY Individual Farm Returns and has been successful until the most recent update. They are now receiving the following reject on three separate farm returns:
![image](https://user-images.githubusercontent.com/44508876/53653658-a6589300-3c00-11e9-8895-02ef640c3955.png)

The client is unsure why their numbers would be wrong on these returns with this current update after successfully filing several 2018 farm returns prior.

**Steps to Reproduce:**  

**Data Location:**
R:\Nathan\3170 - MARTHA @ BURT MARSHALL - Bad Farm QBI

**Comment by MyNameIsDonovan** [comment]
Get update, recalc, retransmit, it should fix this error
