### ISSUE TITLE
Wintax - W-2G - NYC Withholding and State Tax withholding are bound incorrectly together

### ISSUE THREAD

**Issue by MHGray** [TaxwareSupport/Issue-Reports#356]
**Client Name:**  
Lollie

**Client ID:**  
99079

**Description:**  
![image](https://user-images.githubusercontent.com/8196735/53686142-56e59600-3cd8-11e9-9bb4-683c76d53978.png)
21 and 25 are bound together

**Steps to Reproduce:**  
enter an amount on 21 -> press okay -> go back in to w-2G

**Comment by MyNameIsDonovan** [comment]
fixed
