### ISSUE TITLE
Wintax - 8889 - W-2 Box W doesn't pull into 8889 until leaving the form

### ISSUE THREAD

**Issue by MHGray** [TaxwareSupport/Issue-Reports#357]
**Client Name:**  
Barrey

**Client ID:**  
87191

**Description:**  
The amount in the W-2 Box 12 code W does not carry into the 8889 preview until leaving the form.

**Steps to Reproduce:**  
add W-2 with Box 12 code W amount -> Forms/Schedules -> Form 8889 -> preview -> Doesn't have anything on line 9 of the print -> leave and come back -> preview -> now it does

**Data Location:**

**Comment by MyNameIsDonovan** [comment]
fixed
