### ISSUE TITLE
Wintax - form 8880 is inputting an amount on both spouse and taxpayer

### ISSUE THREAD

**Issue by TwZach** [TaxwareSupport/Issue-Reports#361]
**Client Name:**  
susan

**Client ID:**  
407-86

**Description:**  
On form 8880 if you input an amount on Taxpayer it inputs it on spouses as well. If you input on both they both double.
![image](https://user-images.githubusercontent.com/45858181/53766331-66efa800-3e87-11e9-86ac-de95e92fb67f.png)
![image](https://user-images.githubusercontent.com/45858181/53766356-766ef100-3e87-11e9-9739-fcc92b3e52bc.png)

**Steps to Reproduce:**  
Open client -> forms and schedules -> 8880 input amount on taxpayer -> preview

**Data Location:**

**Comment by DodgerDave** [comment]
working correctly
