### ISSUE TITLE
2018 Wintax - 5695 - 2017 5695 Carryover Credit not Triggering 2018 5695 Form Inclusion Automatically 

### ISSUE THREAD

**Issue by twnathan** [TaxwareSupport/Issue-Reports#363]
**Client Name:**  
ALLEN GOLD

**Client ID:**  
21168

**Description:**  
TP has large prior year credit from Form 5695 Residential Energy Credit for solar panels. This credit should carry forward into 2018, however the program did not automatically include Form 5695 in the 2018 return until the client was told by the TP that there should be a credit there, and the client clicked into the Form 5695. Once opened, the carry forward information came through.

Client is worried that other people might miss this carry forward credit because they didn't know it was available to carry forward from last year, and that the carry forward values should trigger the inclusion of Form 5695 automatically when pulling in a prior year client with an applicable credit.

**Steps to Reproduce:**  

**Data Location:**
R:\Nathan\21168 - ALLEN GOLD - Form 5695 Carryforward Credit\2018 Data

**Comment by DodgerDave** [comment]
Fixed it so Form 5695 will automatically be created if there was a prior year carryforward.
