### ISSUE TITLE
Wintax - CA FORM 540NR - Validation Error

### ISSUE THREAD

**Issue by twsal** [TaxwareSupport/Issue-Reports#364]
Ralph

7350

Getting a Validation error for not having alimony information, when the information is on both the fed and the state.

Under CA nonresident --> Adjustments --> line 29 

![capture](https://user-images.githubusercontent.com/44677096/53772186-58f75280-3e9a-11e9-9cb0-b47bce1d4a8c.JPG)

R:\Sal\Ralph 7350

**Comment by DodgerDave** [comment]
Fixed 3-7
