### ISSUE TITLE
Wintax - 1116/SchB - Foreign Tax on Dividends not carrying to 1116

### ISSUE THREAD

**Issue by MHGray** [TaxwareSupport/Issue-Reports#366]
**Client Name:**  
Sandy

**Client ID:**  
213150

**Description:**  
In Schedule B they have a few dividends with Foreign Tax. The program give the prompt to carry the information to the 1116 but then nothing actually carries over. It will create the 1116, but it will not actually input any data.

**Steps to Reproduce:**  
Use Data Provided

**Data Location:**
R:\Matt\1116Carry

**Comment by DodgerDave** [comment]
Fixed 3-7
