### ISSUE TITLE
Wintax - 8283 - Attachment seems to be good but is getting a reject saying it is not attached.

### ISSUE THREAD

**Issue by MHGray** [TaxwareSupport/Issue-Reports#368]
**Client Name:**  
Barry

**Client ID:**  
87191

**Description:**  
Has 8283 with 1098-C PDF attached, and from what I can tell everything looks good but it is still rejecting. I've included the acknowledgement file and the submission for this particular return. 

**Steps to Reproduce:**  
See Data

**Data Location:**
R:\Matt\8283AttachmentReject

**Comment by DodgerDave** [comment]
Fixed 3-11
