### ISSUE TITLE
2018 Wintax - Sch A - F3 List Functionality for Sch A Personal Property Taxes

### ISSUE THREAD

**Issue by twnathan** [TaxwareSupport/Issue-Reports#370]
**Client Name:**  
MISSY @ ED HEYLIN's Office

**Client ID:**  
2450

**Description:**  
Client is hoping for a F3 list functionality to be added to the Sch A, [30] Personal property taxes section to be able to track multiple properties.
![image](https://user-images.githubusercontent.com/44508876/53913531-66cee400-4010-11e9-97da-5477219da878.png)

**Steps to Reproduce:**  

**Data Location:**

**Comment by MyNameIsDonovan** [comment]
they can have it
