### ISSUE TITLE
Wintax - CA - MFS missing prompt for spouse info when status is different from fed

### ISSUE THREAD

**Issue by MHGray** [TaxwareSupport/Issue-Reports#373]
**Client Name:**  
John Lee

**Client ID:**  
110-86

**Description:**  
If filing status is single on fed and MFS on CA, when setting the filing status to MFS it should prompt for information on the spouse to input on the print (and efile).

**Steps to Reproduce:**  
Be single on fed -> CA -> Basic info -> change status to MFS

**Comment by DodgerDave** [comment]
fixed 3-7

**Comment by MHGray** [comment]
![image](https://user-images.githubusercontent.com/8196735/54858631-38653000-4cc3-11e9-80fb-aef585ee8322.png)


Prompt works now, but they are getting validity error saying Spouse's name is missing.


![image](https://user-images.githubusercontent.com/8196735/54858605-094ebe80-4cc3-11e9-84c9-dd98f3f6ffb3.png)


Data:R:\Matt\110-86CAMFS

**Comment by DodgerDave** [comment]
Fixed for real this time.
