### ISSUE TITLE
Wintax - Schedule D Worksheet - High income client getting 600k on line 24 somehow

### ISSUE THREAD

**Issue by MHGray** [TaxwareSupport/Issue-Reports#375]
**Client Name:**  
Anita

**Client ID:**  
1380

**Description:**  
![image](https://user-images.githubusercontent.com/8196735/53984281-de167d80-40cd-11e9-8fbc-626e2e5b799e.png)

**Steps to Reproduce:**  
Use Data Provided

**Data Location:**
R:\Matt\ScheduleDTaxWrksht

**Comment by DodgerDave** [comment]
Fixed
