### ISSUE TITLE
Wintax - VT - State payment info being entered even if they aren't doing direct debit

### ISSUE THREAD

**Issue by MHGray** [TaxwareSupport/Issue-Reports#376]
**Client Name:**  
Martha

**Client ID:**  
3170

**Description:**  
On a Vermont return with a balance due, getting a validation error on the payment method even though they are not doing electronic payment.
![image](https://user-images.githubusercontent.com/8196735/53984550-6bf26880-40ce-11e9-8696-096a8067036e.png)

**Steps to Reproduce:**  
Validate with a vermont balance due but no direct debit info put in.

**Comment by twJorge** [comment]
Fixed
