### ISSUE TITLE
2018 Wintax - AL Sch CR - Taking loss on AGI Leads to % that Exceeds 100% and Throws Error/Reject

### ISSUE THREAD

**Issue by twnathan** [TaxwareSupport/Issue-Reports#377]
**Client Name:**  
CHERYL STARKEY

**Client ID:**  
601-86

**Description:**  
Client had the following reject:
![image](https://user-images.githubusercontent.com/44508876/53992079-ce546480-40e0-11e9-9b7b-e72dc7599160.png)

Due to a loss taken on AGI, the values calculate as follows:
![image](https://user-images.githubusercontent.com/44508876/53992124-e1ffcb00-40e0-11e9-8f31-21e5260b4969.png)

Value probably should not exceed 100%

**Steps to Reproduce:**  

**Data Location:**
R:\Nathan\601-86 - CHERYL STARKEY - AL Sch CR Percentage Exceeds 100

**Comment by twJorge** [comment]
Client was inputting wrong data.
