### ISSUE TITLE
Wintax -> form 8615 instructions change worksheet calculations

### ISSUE THREAD

**Issue by TwZach** [TaxwareSupport/Issue-Reports#380]
**Client Name:**  
Randal

**Client ID:**  
572-86

**Description:**  
The instructions on the 8615 says to make modifications to the capital gains and qualified dividends worksheet.

**Steps to Reproduce:**  
View 8615 filing instructions -> preview capital gains and qualified dividends worksheet

**Data Location:**

**Comment by DodgerDave** [comment]
Fixed 3-11
