### ISSUE TITLE
Wintax - IA - Validity error that residency is not populating

### ISSUE THREAD

**Issue by TwZach** [TaxwareSupport/Issue-Reports#382]
**Client Name:**  
Jenny

**Client ID:**  
21704

**Description:**  
Validity error that says the IA-126 is missing the Taxpayers residency status. Preview shows it is missing but there is no input for it besides the main residency status.

**Steps to Reproduce:**  
open client data -> Summary menu -> Validity check -> IA -> line 56 form 126 -> form print preview form 126

**Data Location:**
R:\Zac\2018clientdata\213129clientdata

**Comment by MyNameIsDonovan** [comment]
fixed
