### ISSUE TITLE
Proforma - Sch C - After 2018 Sch C QBI Additions, Numbering between 2018 Wintax Sch C Input and Printed Sch C Proforma Do Not Align

### ISSUE THREAD

**Issue by twnathan** [TaxwareSupport/Issue-Reports#385]
**Client Name:**  
DAVID A ALVAREZ

**Client ID:**  
9753

**Description:**  
Client uses prior year Proforma prints to help with current tax year input. However after the new QBI information was added to the 2018 Sch C Input, the numbers between the Proforma print and this year do not match. The client would like this fixed now, but I told him the likelihood of it being fixed this tax season was practically zero.

This issue will solve itself next year with zero input effort. He made me promise to submit the suggestion anyway.

**Steps to Reproduce:**  

**Data Location:**

**Comment by MHGray** [comment]
You can transfer over the file in R:\Matt\ProformaFix into their proforma program path and overwrite the one that is there.
