### ISSUE TITLE
2018 Wintax - IA126 - Potential Net Income Miscalculation Throwing Schema Validation Error

### ISSUE THREAD

**Issue by twnathan** [TaxwareSupport/Issue-Reports#387]
**Client Name:**  
SUSAN GIRGEN

**Client ID:**  
407-86

**Description:**  
Client is receiving a Net Income schema validation error on the IA126 -- first it was saying that there was no Net Income, but after carrying info into the IA126 again it is still throwing an error but with values. Client data attached below.

**Steps to Reproduce:**  

**Data Location:**
R:\Nathan\407-86 - SUSAN GIRGEN - IA126 Schema Validation

**Comment by MyNameIsDonovan** [comment]
fixed
