### ISSUE TITLE
2018 Wintax - CA540 Sch CA - Other Itemized Deductions Value Missing on Sch CA

### ISSUE THREAD

**Issue by twnathan** [TaxwareSupport/Issue-Reports#391]
**Client Name:**  
HARLOW DAWSON

**Client ID:**  
21361

**Description:**  
Client sees that the Other Itemized Deductions from the FED are being added into the CA Return properly, but the values do not show up in the form print:

FED Sch A:
![image](https://user-images.githubusercontent.com/44508876/54143712-9d797580-43e7-11e9-8a90-4f3a8dd6b724.png)

Sch CA Input:
![image](https://user-images.githubusercontent.com/44508876/54143752-b41fcc80-43e7-11e9-8bd0-68f3e6b9cd62.png)

CA Return Preview:
![image](https://user-images.githubusercontent.com/44508876/54143783-c6016f80-43e7-11e9-9a38-2c30be0341ec.png)

**Steps to Reproduce:**  

**Data Location:**

**Comment by DodgerDave** [comment]
Those amount show on page 3 (resident Sch CA) or page 4 (NR Sch CA)
