### ISSUE TITLE
Wintax - taxable income has an additional 8,240

### ISSUE THREAD

**Issue by TwZach** [TaxwareSupport/Issue-Reports#392]
**Client Name:**  
norm

**Client ID:**  
7670-1

**Description:**  
Has an additional amount in taxable income and we could not find where it is coming from

**Steps to Reproduce:**  
open client data -> line input

**Data Location:**
R:\Zac\2018clientdata\7670-1clientdata

**Comment by MHGray** [comment]
Figured it out
