### ISSUE TITLE
2018 Wintax - NJ-COJ - Name & Code of Jurisdiction not Appearing on Return

### ISSUE THREAD

**Issue by twnathan** [TaxwareSupport/Issue-Reports#393]
**Client Name:**  
JOSEPH M TEDESEO

**Client ID:**  
99075

**Description:**  
Client reporting that the Name & Code of Jurisdiction (in this case, 32 - New York) is not appearing on the preview or print of the NJ-COJ form. Client data included below.

![image](https://user-images.githubusercontent.com/44508876/54146874-25627e00-43ee-11e9-9237-eafce9955fcb.png)

![image](https://user-images.githubusercontent.com/44508876/54147020-7c685300-43ee-11e9-8eb7-d89ec989ce3b.png)

**Steps to Reproduce:**  

**Data Location:**
R:\Nathan\99075 - JOSEPH TEDESEO - NJ Return No Jurisdiction Info on Return

**Comment by DodgerDave** [comment]
Fixed 3-11
