### ISSUE TITLE
2018 Wintax - 1040 - Single TP, Dependent of Another (DoA), shows DoA check box in Print/Preview for Spouse

### ISSUE THREAD

**Issue by twnathan** [TaxwareSupport/Issue-Reports#394]
**Client Name:**  
MINDY WAGNER

**Client ID:**  
Sales Team

**Description:**  
Mindy found this on her son's return but I just recreated it with a dummy client.

When a single taxpayer (TP) is marked as Dependent of Another (DoA) the print/preview of their return has the Spouse DoA box automatically checked.

![image](https://user-images.githubusercontent.com/44508876/54147552-a66e4500-43ef-11e9-8947-d9e28fc82a32.png)

**Steps to Reproduce:**  
Create/Recall Client -> Single filing as Dependent of Another -> Preview 1040

**Data Location:**

**Comment by DodgerDave** [comment]
Fixed 3-11
