### ISSUE TITLE
Wintax - IA - With Part Year Resident, cannot get it to clear validation

### ISSUE THREAD

**Issue by MHGray** [TaxwareSupport/Issue-Reports#395]
**Client Name:**  
Connell

**Client ID:**  
21214

**Description:**  
Getting an IA validation error saying that TotalAdjustments is missing. I tried everything but I can't get it to put in TotalAdjustments.

**Steps to Reproduce:**  
Use data -> Validate IA

**Data Location:**
C:\Users\Christina\Desktop\IAPYValidation21214

**Comment by MyNameIsDonovan** [comment]
fixed
