### ISSUE TITLE
2018 Wintax - 1040NR - [57]-[59] (a) Country Input Accepts Dates but not Countries/Letters

### ISSUE THREAD

**Issue by twnathan** [TaxwareSupport/Issue-Reports#396]
**Client Name:**  
PATRICIA BARBA

**Client ID:**  
20186

**Description:**  
Once you access the 1040NR and scroll down to inputs [57]-[59] (a) Country, if you type any country names or letters and then move on the field blanks itself. If you type numbers, it puts them into date format. 

**Steps to Reproduce:**
2018 Wintax -> Forms & Schedules -> 1040NR -> [57]-[59] (a) Country Input

**Data Location:**

**Comment by MyNameIsDonovan** [comment]
fixed
