### ISSUE TITLE
2018 Wintax - UT TC-40 Sch B - Lines 35-37 Not Generating Values on the Form, but Correct Elsewhere

### ISSUE THREAD

**Issue by twnathan** [TaxwareSupport/Issue-Reports#398]
**Client Name:**  
ROB @ UDARBE TAX SERVICE

**Client ID:**  
213117

**Description:**  
UT TC-40 Sch B not generating values on Form Lines 35-37:
![image](https://user-images.githubusercontent.com/44508876/54161514-98302100-440f-11e9-9176-5b9541030f5c.png)
![image](https://user-images.githubusercontent.com/44508876/54161463-733bae00-440f-11e9-948b-eb3a7f9cf481.png)

**Steps to Reproduce:**  

**Data Location:**
R:\Nathan\213117 - ROB @ UDARBE TAX - UT TC-40B Issue

**Comment by DodgerDave** [comment]
Fixed 3-11
