### ISSUE TITLE
Wintax - Alabama - Part v line 4 is not calculating correctly 

### ISSUE THREAD

**Issue by TwZach** [TaxwareSupport/Issue-Reports#399]
**Client Name:**  
David

**Client ID:**  
5980

**Description:**  
part 5 line 4 is not calculating correctly, 
![image](https://user-images.githubusercontent.com/45858181/54214201-03770300-44a3-11e9-84f3-5d5fd807a981.png)

Seems to be caused by the ratio being over 100 but not being inputted as such.

**Steps to Reproduce:**  
open client data -> AL -> Preview

**Data Location:**
R:\Zac\2018clientdata\5980clientdata5

**Comment by twJorge** [comment]
Fixed, now capped at 100%.
