### ISSUE TITLE
1040 NextGen - Suggestion - Remember sort choice on recall current

### ISSUE THREAD

**Issue by MHGray** [TaxwareSupport/Issue-Reports#4]
**Client Name:**  Dale

**Client ID:**  21200

**Description:**  
Client wants recall current screen to remember the last way it was sorted. Currently it will always sort by client ID, but Legacy used to remember that if you used [Last Name] sort the previous to time to leave it in [Last Name] sort.

**Reproduce:**  
Recall Client -> Sort by Last Name by typing in last name field or clicking the name tab on top -> Push okay to go back to main menu -> Push Recall Client -> list is now sorted by client ID again.

**Data Location:** None

**Comment by MyNameIsDonovan** [comment]
Ive added this in for 18
