### ISSUE TITLE
Wintax - Hawaii- 1099R Carry over to Part Yr

### ISSUE THREAD

**Issue by twsal** [TaxwareSupport/Issue-Reports#400]
Richard

Richard

The 1099R from the FED is not carrying over into the state Hawaii, as income. Its having an issue with non or part yr resident calculation, but its calculating correct with the regular resident option.

Full yr

![haw](https://user-images.githubusercontent.com/44677096/54217219-6fa83580-44a8-11e9-9417-42b2e6253088.JPG)

Part yr

![ha](https://user-images.githubusercontent.com/44677096/54217243-7cc52480-44a8-11e9-9899-14b237341a3b.JPG)

R:\Sal\RICHARD

**Comment by twJorge** [comment]
Was a non issue. 1099 was not filled correctly.
