### ISSUE TITLE
Wintax - VA - Basic Info, line 19 unbound?

### ISSUE THREAD

**Issue by MHGray** [TaxwareSupport/Issue-Reports#401]
**Client Name:**  
jmb

**Client ID:**  
Message Boards

**Description:**  
![image](https://user-images.githubusercontent.com/8196735/54218601-20afcf80-44ab-11e9-9bd6-5a964024daca.png)
Checking line 19 on VA Basic info doesn't keep. 

**Steps to Reproduce:**  
Check the box -> press Okay -> go back into Basic Info -> Box is unchecked.

**Comment by DodgerDave** [comment]
Items 21-23 weren't working either. All fixed on 3-13
