### ISSUE TITLE
2018 Partnership - CA 568 - 'FarmExpensesGrp' Schema Error for Investment Risk Indicator

### ISSUE THREAD

**Issue by twnathan** [TaxwareSupport/Issue-Reports#403]
**Client Name:**  
ROBERT LEACH

**Client ID:**  
12703

**Description:**  
Client is receiving the following schema validation error for the CA 568:
![image](https://user-images.githubusercontent.com/44508876/54221561-feb94b80-44b0-11e9-820d-a720c4b51c20.png)

Checking the FED Sch F information and the CA 568 Sch F carryover information, there does not appear to be any errors or missing information. The FED XML shows the Risk Indicator as checked but at the bottom of the 'FarmExpensesGrp' information.

Client data located below.

**Steps to Reproduce:**  

**Data Location:**
R:\Nathan\12703 - ROBERT LEACH - Ptnr CA 568 Farm Expenses Group Schema Error

**Comment by MyNameIsDonovan** [comment]
fixed
