### ISSUE TITLE
Partnership - CA568- NonNegativeInteger

### ISSUE THREAD

**Issue by twsal** [TaxwareSupport/Issue-Reports#404]
Bob

12763

In the partnership program, there is a issue when calculating a negative number coming from a loss. It is giving multiple errors when going into the state validation check, saying total income is invalid, that the number is to large or too small. This is a continuing partnership, and it is only giving this error with CA568. Another error is FarmExpensesGrp where its not taking the number of investment .

![Capture](https://user-images.githubusercontent.com/44677096/54218007-ebef4880-44a9-11e9-96eb-b5c68b8cc1a2.JPG)

R:\Sal\bob 12763

**Comment by MyNameIsDonovan** [comment]
fixed. They will need to remove the income and add in the info on the last two k1s for this to work
