### ISSUE TITLE
2018 Partnership - CA 568 - Income Worksheet Typo

### ISSUE THREAD

**Issue by twnathan** [TaxwareSupport/Issue-Reports#406]
**Client Name:**  
BOB LEACH

**Client ID:**  
12703

**Description:** 
2018 Partnership -> CA 568 - Income Worksheet:
![image](https://user-images.githubusercontent.com/44508876/54224754-6d010c80-44b7-11e9-87e1-2f065c41d5b9.png)

CA 568, Schedule IW Online frm FTB website:
![image](https://user-images.githubusercontent.com/44508876/54224799-830ecd00-44b7-11e9-92be-82f89c55bca8.png)

Typo: Says "Line 8" but should be "Line 3"

**Steps to Reproduce:**  

**Data Location:**

**Comment by MyNameIsDonovan** [comment]
fixed
