### ISSUE TITLE
2017 1120 Fed Corp Return - NOL - Negative Income Tax issue

### ISSUE THREAD

**Issue by twnathan** [TaxwareSupport/Issue-Reports#41]
**Client Name:**  
HARLOW DAWSON

**Client ID:**  
21361

**Description:**  
2017 1120 Fed Corp Return --> Company has Net Operating Loss but form preview shows a negative amount for income tax when it should be blank.

**Reproduce:**  
Bug is in the client data --> able to manipulate the negative income tax value but not eliminate it --> See 1120 --> Page 3 --> Schedule J, Part I --> Lines 2 & 4
![image](https://user-images.githubusercontent.com/44508876/49482442-131be700-f7e4-11e8-9459-cbafcd0df536.png)

**Data Location:**
R:\Nathan --> TX401._CA & TX401.CRP

**Comment by MHGray** [comment]
This had to do with the prorated tax for fiscal year corps. It isn't correct to show a negative value there but it also doesn't affect any of the other calculations. This has been resolved with client already.
