### ISSUE TITLE
Wintax- Validity error

### ISSUE THREAD

**Issue by TwZach** [TaxwareSupport/Issue-Reports#410]
**Client Name:**  
Phylistine

**Client ID:**  
21253

**Description:**  
Client is getting a validity error on the 8862 eic after dis-allowance. Asking for other dependent info

**Steps to Reproduce:**  
open client data -> validity check

**Data Location:**
R:\Zac\2018clientdata\21253clientdata

**Comment by DodgerDave** [comment]
Validates on my machine and Zach's.
