### ISSUE TITLE
Wintax 2018 - NY IT-201-X - Print buttons not working

### ISSUE THREAD

**Issue by twgenie** [TaxwareSupport/Issue-Reports#412]
**Client Name:**  
Martha

**Client ID:**  
3170

**Description:**  
Clicking either print button will not print the forms.

**Steps to Reproduce:**  
![image](https://user-images.githubusercontent.com/46978780/54398971-8d78c480-4679-11e9-8f32-c24bb1511e8c.png)

**Comment by DodgerDave** [comment]
Fixed 3-15.  The print button wasn't working from any legacy menu. They will all work now.
