### ISSUE TITLE
Wintax- Client data print out a page with numbers that don't make sense

### ISSUE THREAD

**Issue by TwZach** [TaxwareSupport/Issue-Reports#413]
**Client Name:**  
martha

**Client ID:**  
20182

**Description:**  
The preview prints out two pages with numbers in the millions and a title that makes no sense. See pages attached.

**Steps to Reproduce:**  
Open client data -> Preview return

**Data Location:**
R:\Zac\2018clientdata\20182clientdata

**Comment by MyNameIsDonovan** [comment]
There was something weird going on with the misc schedules. I have removed them from the return
