### ISSUE TITLE
2018 Wintax - EIC Worksheet B - Worksheet B Not Triggering for Minister, Defaults to A

### ISSUE THREAD

**Issue by twnathan** [TaxwareSupport/Issue-Reports#414]
**Client Name:**  
KARIN WITMER

**Client ID:**  
29017

**Description:**  
TP is a minister and currently is receiving too large a credit on EIC according to the client. In any case, EIC should trigger Worksheet B for the minister but only Worksheet A triggers or after playing with the data, no worksheet at all.

**Steps to Reproduce:**  

**Data Location:**
R:\Nathan\29017 - KARIN WITMER - EIC Worksheet B Not Triggering for Minister

**Comment by DodgerDave** [comment]
Fixed 3-18
