### ISSUE TITLE
2018 Wintax - CA 540 - Educator Credit Carried from FED Is Put Into CA 540 Line 14 Instead of Line 16

### ISSUE THREAD

**Issue by twnathan** [TaxwareSupport/Issue-Reports#416]
**Client Name:**  
FRANK LUKEHART

**Client ID:**  
21331

**Description:**  
Client called to inform us that some credits, such as the Educator Credit from FED Adjustments to Income, are being added together with subtractions on Page 2, Line 14 of the CA 540 return rather than the Additions on Line 16. The value ends up being the same, but the normal way of tracking and seeing those numbers come through is incorrect. 

The client believes that this may also be occurring with other credits as well, but knows of at least this one.

**Steps to Reproduce:**  
1040 Line Input -> [07] Adjustment to Income -> [23] Educator Expenses = $250 -> Carry to CA 540 -> Preview Return

**Data Location:**

**Comment by DodgerDave** [comment]
Carried to correct line for me.
