### ISSUE TITLE
Wintax- Reject - for MF-S return

### ISSUE THREAD

**Issue by TwZach** [TaxwareSupport/Issue-Reports#418]
**Client Name:**  
John

**Client ID:**  
327-86

**Description:**  
Client is getting rejected for Spouse income or expense but there is none in the return

**Steps to Reproduce:**  
Open client data

**Data Location:**
R:\Zac\2018clientdata\327-86clientdata

**Comment by MyNameIsDonovan** [comment]
im going to close this issue, needs to change the social on th w2
