### ISSUE TITLE
2018 Wintax - Form 5405 - Form 5405 not generating values properly

### ISSUE THREAD

**Issue by twnathan** [TaxwareSupport/Issue-Reports#419]
**Client Name:**  
JOHN VERTNIK

**Client ID:**  
21620

**Description:**  

![image](https://user-images.githubusercontent.com/44508876/54478960-79e27080-47d5-11e9-9a69-2e51fd3d18b0.png)
![image](https://user-images.githubusercontent.com/44508876/54478962-836bd880-47d5-11e9-8f66-1d640721792a.png)

![image](https://user-images.githubusercontent.com/44508876/54478980-b3b37700-47d5-11e9-9323-f9aa5536e9e0.png)

**Steps to Reproduce:**  

**Data Location:**

**Comment by MHGray** [comment]
This looks like he just wants to make the 500 payment. He shouldn't be filling out anything other than lines [01] - [05]. This will not print a 5405 because it is not necessary but will put the 500 payment on the return.
