### ISSUE TITLE
Winpay - preview and print of 941 quarterly reports for 2019 show 2017

### ISSUE THREAD

**Issue by TwZach** [TaxwareSupport/Issue-Reports#42]
**Client Name:**  
david
**Client ID:**  
21388
**Description:**  
Printing out the quarterly 941 prints a 2017 document
**Reproduce:**  
Open winpay → Click reports → Click quarterly reports → click 941 → quarter 4 → 
![image](https://user-images.githubusercontent.com/45858181/49961654-155b0100-fec8-11e8-817b-88e597522457.png)

**Data Location:**

**Comment by MHGray** [comment]
This was fixed in a patch
