### ISSUE TITLE
2018 Wintax - MA Return - Reject Stating Part-time Resident Status when Non- Resident

### ISSUE THREAD

**Issue by twnathan** [TaxwareSupport/Issue-Reports#422]
**Client Name:**  
NICOLE @ BRIGLIO & CHEUNG

**Client ID:**  
94031

**Description:**  
Client received the following reject, multiple times:
![image](https://user-images.githubusercontent.com/44508876/54542900-d7072f00-4959-11e9-9b87-d7ee653c2e32.png)
TP is listed as Non-Resident, not Part-Time:
![image](https://user-images.githubusercontent.com/44508876/54543096-454bf180-495a-11e9-957e-642137336394.png)
![image](https://user-images.githubusercontent.com/44508876/54543172-64e31a00-495a-11e9-9186-182d835cfb0b.png)

Previewing the return shows Non-Resident status:
![image](https://user-images.githubusercontent.com/44508876/54543375-c905de00-495a-11e9-82d6-d58f32146694.png)

**Steps to Reproduce:**  

**Data Location:**
R:\Nathan\94031 - NICOLE @ BRIGLIO & CHEUNG - MA Return Non-Resident Bad Dates

**Comment by DodgerDave** [comment]
Fixed 3-18
