### ISSUE TITLE
Wintax - NY - Error when efile on form 214

### ISSUE THREAD

**Issue by TwZach** [TaxwareSupport/Issue-Reports#423]
**Client Name:**  
Waqar

**Client ID:**  
213102

**Description:**  
receiving an error when trying to efile the client, produces error log for IT214

**Steps to Reproduce:**  
Open client data -> see error log

**Data Location:**
R:\Zac\2018clientdata\213102clientdata3

**Comment by DodgerDave** [comment]
Form IT-214 not needed
