### ISSUE TITLE
2018 Winatx - CA 540 - Adj to FED Itemized Deductions Miscalculation & Reject

### ISSUE THREAD

**Issue by twnathan** [TaxwareSupport/Issue-Reports#424]
**Client Name:**  
MONTIE MERRILL

**Client ID:**  
21307

**Description:**  
![image](https://user-images.githubusercontent.com/44508876/54545425-e2a92480-495e-11e9-9682-67268d78e77f.png)
![image](https://user-images.githubusercontent.com/44508876/54545431-e9d03280-495e-11e9-98a4-794748b947f9.png)

**Steps to Reproduce:**  

**Data Location:**
R:\Nathan\21307 - MONTIE MERRILL - CA Adj to Fed Itemized Off by One Dollar

**Comment by DodgerDave** [comment]
They may have made a change in federal and didn't go back into CA
