### ISSUE TITLE
Wintax 2018 - Form 8889 Health Savings Accounts - Form will not auto calc

### ISSUE THREAD

**Issue by twgenie** [TaxwareSupport/Issue-Reports#425]
**Client Name:**  
Barrey

**Client ID:**  
87191

**Description:**  
Form 8889 will not calculate without leaving the form and going back into it. Because of this it will not carry to CA Schedule CA line [24]

**Steps to Reproduce:**  
Enter amounts on line [02] and line [03] on the form 8889, preview form and lines [04] - [13] are blank. Carry to California and no value is on line [24] in the schedule CA.

Leave the form and go back into form 8889, click preview and lines [04] - [13] populate and recarry to California and line [24] in the schedule CA fills in.

**Comment by DodgerDave** [comment]
It worked for me.
