### ISSUE TITLE
Wintax - 1099r pension - distribution code 3 and under age limit put income in wages

### ISSUE THREAD

**Issue by TwZach** [TaxwareSupport/Issue-Reports#434]
**Client Name:**  
mo

**Client ID:**  
22025

**Description:**  
When inputting a 1099r-pension with distribution code 3 and select below minimum age limit it carries income to wages and not pensions

**Steps to Reproduce:**  
open client -> add 1099r-pension -> distribution code 3 -> select no on age limit -> 1040

**Data Location:**

**Comment by DodgerDave** [comment]
According to instructions, that is how it should work.
