### ISSUE TITLE
Wintax - client reject for car and truck worksheet

### ISSUE THREAD

**Issue by TwZach** [TaxwareSupport/Issue-Reports#435]
**Client Name:**  
Barry

**Client ID:**  
87191

**Description:**  
Client is getting rejected for car and truck worksheet on sch c

**Steps to Reproduce:**  
see client data -> see reject -> open client data -> sch c -> car and truck worksheet

**Data Location:**
R:\Zac\2018clientdata\87191clientdata3

**Comment by DodgerDave** [comment]
Input total miles and business miles and it should work.
