### ISSUE TITLE
Wintax - CO - Colorado non or part year resident select is not working

### ISSUE THREAD

**Issue by TwZach** [TaxwareSupport/Issue-Reports#438]
**Client Name:**  
Rosalba

**Client ID:**  
21487

**Description:**  
In colorado basic info the spouses residency select is not matching 

**Steps to Reproduce:**  
Open client -> CO -> Basic info -> 104pn data -> spouse residency preview

**Data Location:**

**Comment by twJorge** [comment]
Fixed.
