### ISSUE TITLE
2018 Individual Program --> 8879 CA Print Issues --> Prints for some clients, not others

### ISSUE THREAD

**Issue by twnathan** [TaxwareSupport/Issue-Reports#44]
**Client Name:**  
BARREY H. STAGGS, CPA

**Client ID:**  
87191

**Description:**  
(From provided data location below)
Open Client #1 in 2018 Individual Program --> Summary --> E-File --> [02] Print 8879 --> No pop-up question --> Prints only Fed

Open Client #2 in 2018 Individual Program --> Summary --> E-File --> [02] Print 8879 --> Pop up question: "Taxware Systems - Would you like to print ALL federal signature documents?" --> YES --> Prints Fed AND CA state

![image](https://user-images.githubusercontent.com/44508876/50256668-329e3c80-03ac-11e9-97e8-070bb436f0a7.png)

Barrey is concerned that CA prints for one but not the other. Client #2 triggers the additional question seen above while Client #1 does not; unsure why.

**Reproduce:**  
Reproduced with client data and standard printer settings; data location found below.

**Data Location:**
R:\Nathan\8879 Troubles

**Comment by DodgerDave** [comment]
This must be working right.  I've never heard of anyone else having problems.  Let me know if it is still a problem.
