### ISSUE TITLE
2018 Wintax - GA Return - FED Retirement Income Carrying to GA as Georgia Income

### ISSUE THREAD

**Issue by twnathan** [TaxwareSupport/Issue-Reports#442]
**Client Name:**  
DAVID JONES

**Client ID:**  
5980

**Description:**  

TP is filing GA as Non-Resident -- Retirement Income seems to be carrying incorrectly to GA Return as Georgia income

![image](https://user-images.githubusercontent.com/44508876/54725290-bf7fa000-4b2b-11e9-926d-98e927526cd7.png)

![image](https://user-images.githubusercontent.com/44508876/54725333-edfd7b00-4b2b-11e9-86f1-48f00362391a.png)

![image](https://user-images.githubusercontent.com/44508876/54725385-1a18fc00-4b2c-11e9-91b0-bb96c42cb7ed.png)

**Steps to Reproduce:**  

**Data Location:**
R:\Nathan\5980 - DAVID JONES - GA Return Carrying Retirement as Taxable Income

**Comment by DodgerDave** [comment]
Looks like it is working correctly.
