### ISSUE TITLE
Wintax - VT Vermont - Carries a negative taxable income from the federal

### ISSUE THREAD

**Issue by TwZach** [TaxwareSupport/Issue-Reports#443]
**Client Name:**  
Peter

**Client ID:**  
7850

**Description:**  
Getting a reject for having negative fed taxable income, that is carrying from a standard deduction greater than income

**Steps to Reproduce:**  
Open client data -> 1040 -> form print -> VT -> Form 153 

**Data Location:**
R:\Zac\2018clientdata\7850clientdata

**Comment by twJorge** [comment]
Issue fixed.
