### ISSUE TITLE
Wintax - form 4631 fuel credit is applying even after deleted

### ISSUE THREAD

**Issue by TwZach** [TaxwareSupport/Issue-Reports#447]
**Client Name:**  
Miguel

**Client ID:**  
2740

**Description:**  
Form 4631 fuel credit is applying to schedule 5 even after deleting it, but the form doesn't show where amount is coming from

**Steps to Reproduce:**  
Open client data -> line input -> sch 5

**Data Location:**
R:\Zac\2018clientdata\2740clientdata

**Comment by DodgerDave** [comment]
They had 283 in the override section so it was going to show no matter what.  Take out override and it goes away.
