### ISSUE TITLE
S-corp and Corp - MS -franchise tax is calculating incorrectly

### ISSUE THREAD

**Issue by TwZach** [TaxwareSupport/Issue-Reports#449]
**Client Name:**  
David

**Client ID:**  
5980

**Description:**  
The franchise tax in Mississippi is not calculating correctly, instruction say first 100,000 is excluded. 
![image](https://user-images.githubusercontent.com/45858181/54928245-dda12380-4ed0-11e9-91bd-bb7cd5b49f2e.png)
  
![image](https://user-images.githubusercontent.com/45858181/54928564-53a58a80-4ed1-11e9-9671-9615cab4cb63.png)

**Steps to Reproduce:**  
open client data -> MS -> Preview return -> Franchise Tax

**Data Location:**
R:\Zac\2018clientdata\5980clientdata6

https://www.dor.ms.gov/Forms/83100188.pdf

**Comment by DodgerDave** [comment]
Fixed 3-27
