### ISSUE TITLE
Wintax - GA - Retirement income Carrying to wrong place

### ISSUE THREAD

**Issue by TwZach** [TaxwareSupport/Issue-Reports#451]
**Client Name:**  
Frank

**Client ID:**  
26021

**Description:**  
Client says that the k-1 should carry to schedule 1 retirement line 2 occasionally instead of line 13 
![image](https://user-images.githubusercontent.com/45858181/54947754-4e0f6b00-4ef8-11e9-9f30-7b6d2567c0ee.png)

**Steps to Reproduce:**  
open client data -> open GA -> adj to income -> preview

**Data Location:**
R:\Zac\2018clientdata\26021clientdata

**Comment by DodgerDave** [comment]
Fixed by adding overrides for line 2 and 13 of retirement income exclusion in GA.
