### ISSUE TITLE
2018 Wintax - 1099-G - 1099-G for Reporting State Tax Refund not Carrying Properly to the 1040/Sch 1

### ISSUE THREAD

**Issue by twnathan** [TaxwareSupport/Issue-Reports#454]
**Client Name:**  
ARTHUR MINTZ

**Client ID:**  
213152

**Description:**  
Inputs on [84] Other Income/Adjustments/Payments, [02] Taxable state tax refunds and/or [04] Unemployment compensation are not carrying forward properly to the 1040/Schedule 1 and need to be manually entered in on the Schedule 1 to appear as intended.

In fact, information entered in [02] & [04] under Other Income... doesn't even appear in those [02] & [04] fields after completing the input of those values.

![image](https://user-images.githubusercontent.com/44508876/54961232-2252ac00-4f1d-11e9-8fbe-6370292d3a64.png)

**Steps to Reproduce:**  
1040 -> [84] Other Income... -> [02} & [04] Inputs

**Data Location:**

**Comment by DodgerDave** [comment]
This worked for me.  I need to see data where it doesn't work.
