### ISSUE TITLE
Wintax - WI - Form Line Carry

### ISSUE THREAD

**Issue by twsal** [TaxwareSupport/Issue-Reports#455]
Susan 

407-86

Amount entered in line 9 and line 10 are switched when previewed. When you enter an amount on line 9, it carry's into line 16 when it should be on line 15a on the form, and the same for line 10 it carry's into line 15a instead of carrying into line 16 on the form

Wisconsin--> Subtractions--> Line 4(Sch WD)--> Line 10 (Long-term capital loss carryover from 2017)

![line 9](https://user-images.githubusercontent.com/44677096/55009772-57eca900-4fa0-11e9-9071-cf8890a290eb.JPG)

![line 91](https://user-images.githubusercontent.com/44677096/55009777-59b66c80-4fa0-11e9-9170-9dc916fb2a34.JPG)

![line 10](https://user-images.githubusercontent.com/44677096/55009780-5b803000-4fa0-11e9-85ed-2dbdd7303e77.JPG)
![line 10 1](https://user-images.githubusercontent.com/44677096/55009784-5cb15d00-4fa0-11e9-9c42-76a01dcd26d8.JPG)

**Comment by DodgerDave** [comment]
Fixed 3-26
