### ISSUE TITLE
Wintax - GA - Schedule 1 pulling in rental loss as a gain

### ISSUE THREAD

**Issue by MHGray** [TaxwareSupport/Issue-Reports#456]
**Client Name:**  
Frank

**Client ID:**  
26021

**Description:**  
In GA Schedule 1, the amounts carried to line 13 are not subtracting loss but instead adding it. 
![image](https://user-images.githubusercontent.com/8196735/55014209-c84af880-4fa7-11e9-8794-db86c1cefee1.png)
![image](https://user-images.githubusercontent.com/8196735/55014242-d731ab00-4fa7-11e9-9799-e865caa163e3.png)

**Steps to Reproduce:**  
Use Data provided, GA -> [02] Adjustments -> Preview

**Data Location:**
R:\Matt\GASchEAdj

**Comment by DodgerDave** [comment]
Fixed 3-26
