### ISSUE TITLE
Wintax - Ca - 3885-a not populating on the return

### ISSUE THREAD

**Issue by TwZach** [TaxwareSupport/Issue-Reports#459]
**Client Name:**  
cathy

**Client ID:**  
10723

**Description:**  
Client is expecting the 3885-a to populate but its not

**Steps to Reproduce:**  
open client data -> sch c -> depr -> summary menu -> preview return -> Ca -> Other data -> 3885A

**Data Location:**
R:\Zac\2018clientdata\10723clientdata

**Comment by DodgerDave** [comment]
Can't tell what he is expecting to carry to 3885A.  He will have to enter what he wants in it.
