### ISSUE TITLE
2018 S Corp Print Proforma is crashing

### ISSUE THREAD

**Issue by twsal** [TaxwareSupport/Issue-Reports#46]
Debra  

8826

2018 S Corp Print Proforma is crashing when trying to print the proforma from the S corp. The print blank proforma works, but not the print proforma feature (line 14). Keeps crashing the service with a error "SCorpPDFPRINTER has stopped working". C:\Taxware\18WScorp\SCorpPDFPrinter.exe

**Reproduce:**  
This is also going on with my S Corp print proforma
![scorppdfprinter error](https://user-images.githubusercontent.com/44677096/50304077-ddae0500-0443-11e9-8396-d366475578d1.JPG)

Blank proforma
![scorp blank](https://user-images.githubusercontent.com/44677096/50304903-2070dc80-0446-11e9-8648-ccfae40ca985.JPG)

**Comment by MHGray** [comment]
Should be fixed in the next patch.
