### ISSUE TITLE
Wintax - Ca - Error index out of bounds when entering and exiting CA

### ISSUE THREAD

**Issue by TwZach** [TaxwareSupport/Issue-Reports#469]
**Client Name:**  
Charlie

**Client ID:**  
214-86

**Description:**  
When entering and trying to exit CA an index out of bounds error occurs and generates an error log

**Steps to Reproduce:**  
open client data -> Ca

**Data Location:**
R:\Zac\2018clientdata\214-86clientdata

**Comment by MyNameIsDonovan** [comment]
Hey Zac I won't be in today, so if it's a rush have Dave look at it. I will be in monday

**Comment by DodgerDave** [comment]
Fixed 3-29
