### ISSUE TITLE
Wintax - Sch C Accounting Method changes other sch c accounting methods when chagned

### ISSUE THREAD

**Issue by TwZach** [TaxwareSupport/Issue-Reports#470]
**Client Name:**  
debbie

**Client ID:**  
6830

**Description:**  
If a client has multiple sch c and changes the accounting method on one it changes the accounting method on the other sch c

**Steps to Reproduce:**  
open client -> Sch c -> add 2 -> open one -> line 9 accounting method

**Data Location:**

**Comment by MyNameIsDonovan** [comment]
fixed
