### ISSUE TITLE
2018 Wintax - Basic Info - Program Forcing "Qualified Widower" Status on Single Taxpayer

### ISSUE THREAD

**Issue by twnathan** [TaxwareSupport/Issue-Reports#479]
**Client Name:**  
MIKE PAEK

**Client ID:**  
21002

**Description:**  
TP is Single, but program switches her filing status as soon as you get to the Summary screen to Qualifying Widower. At this point it throws a validation error for missing name information, which I assume pertains to the Qualifying Widower status. 

**Steps to Reproduce:**  

**Data Location:**
R:\Nathan\21002 - MIKE PAEK - Forcing Qualified WIdower on Single TP

**Comment by MyNameIsDonovan** [comment]
i will look into it some more, but for now just have them reselect the status on the 1040NR
