### ISSUE TITLE
Wintax - MD - Nonresident forcing in an override of 0 that can't be removed

### ISSUE THREAD

**Issue by MHGray** [TaxwareSupport/Issue-Reports#485]
**Client Name:**  
Maria

**Client ID:**  
7510-1

**Description:**  
I cannot remove the 0 in the override for MD NR. Even if I 'Override' it with the correct amount, if I leave and return it just puts the 0 back in.

**Steps to Reproduce:**  
MD -> Nonresident Data -> [11] Override

**Comment by DodgerDave** [comment]
Fixed 4-1
