### ISSUE TITLE
Wintax - AZ - PY return not taking into account IRA Deduction on XML causing reject

### ISSUE THREAD

**Issue by MHGray** [TaxwareSupport/Issue-Reports#489]
**Client Name:**  
Jessica

**Client ID:**  
6340-1

**Description:**  
![image](https://user-images.githubusercontent.com/8196735/55422218-027c4300-5530-11e9-98a8-d0e24e2cd802.png)
***
![image](https://user-images.githubusercontent.com/8196735/55422284-2b043d00-5530-11e9-9ebc-a53e39025a8f.png)
***
![image](https://user-images.githubusercontent.com/8196735/55422406-6272e980-5530-11e9-8754-2c5ab81f5f70.png)

**Steps to Reproduce:**  
Use Data Provided

**Data Location:**

**Comment by DodgerDave** [comment]
Fixed 4-2
