### ISSUE TITLE
2018 Wintax --> Recall Prior Client x2 --> No Warning that Client Exists in Recall Current

### ISSUE THREAD

**Issue by twnathan** [TaxwareSupport/Issue-Reports#49]
**Client Name:**  
ENRIQUE SANCHEZ

**Client ID:**  
22022

**Description:**  
Recall Prior Year Client --> Exit Return --> Recall Same Prior Year Client --> Immediately allows you to duplicate client in Recall Current without warning of duplication.

Warning of client duplication existed in Legacy but was not carried forward into Next Gen (2017 or 2018). Believed to check Recall Current for Client's SSN to verify no duplication would take place without warning first.

**Reproduce:**  
Reproduced on client's computer and three technicians' computers

**Data Location:**

**Comment by MyNameIsDonovan** [comment]
Fixed in next patch
