### ISSUE TITLE
Wintax - sch 3 line 1 foreign tax credit is only allowing the sch B foreign tax

### ISSUE THREAD

**Issue by TwZach** [TaxwareSupport/Issue-Reports#490]
**Client Name:**  
Rob

**Client ID:**  
213117

**Description:**  
The sch 3 line one is only inputting the sch b foreign tax amounts not the foreign tax credit, when deleted the foreign tax credit flows correctly.

**Steps to Reproduce:**  
open client data -> line input -> line 12 -> line 1 -> preview -> sch b -> dividends 2 and 3 -> foreign tax

**Data Location:**
R:\Zac\2018clientdata\213117clientdata

**Comment by DodgerDave** [comment]
If foreign tax paid is entered on Sch B and is less than 300 (600 if MFJ) then that amount carries to the 1040 as the foreign tax credit and Form 1116 is not required.
