### ISSUE TITLE
2018 Wintax - Co Return - CO Return Line 1 Value is a Miscarry that Includes QBI

### ISSUE THREAD

**Issue by twnathan** [TaxwareSupport/Issue-Reports#491]
**Client Name:**  
JENNIFER @ VISTA BUSINESS

**Client ID:**  
2690-1

**Description:**  
CO Return Line 1 states "Enter Federal Taxable Income from your federal income tax form: 1040 line 10". Client has a TP who's QBI value is being added into the Taxable Income value from 1040 Line 10 when carrying into CO:

![image](https://user-images.githubusercontent.com/44508876/55439866-beeafe80-555a-11e9-8a7e-6e7003739e4b.png)

![image](https://user-images.githubusercontent.com/44508876/55439846-abd82e80-555a-11e9-89fb-35e6abb4d313.png)

**Steps to Reproduce:**  

**Data Location:**
R:\Nathan\2690-1 - JENNIFER @ VISTA - CO Return Line 1 Miscarry

**Comment by twJorge** [comment]
Fixed.
