### ISSUE TITLE
Wintax - CA540 - Contribution Amount Carry

### ISSUE THREAD

**Issue by twsal** [TaxwareSupport/Issue-Reports#492]
Barrey 

87191

Keeps getting a reject saying the amount for line 110 on the 540 is incorrect, the value is coming out to 230, which should be the correct number but its saying the amount should be 210.

![Capture](https://user-images.githubusercontent.com/44677096/55499794-b1d21c00-55fb-11e9-9fd1-00ea107287e6.JPG)
 

R:\Sal\barrey 87191

**Comment by DodgerDave** [comment]
Fixed 4-4
