### ISSUE TITLE
Wintax - W7 - W7 doesn't show up on the list of forms and schedules used

### ISSUE THREAD

**Issue by MHGray** [TaxwareSupport/Issue-Reports#493]
**Client Name:**  
Anita

**Client ID:**  
21410

**Description:**  
W-7 Doesn't show up on the list of forms/schedules used. 

**Steps to Reproduce:**  
Add a W-7 to a return -> go to line input/Forms and Schedules -> Doesn't show up in forms used.

**Comment by MHGray** [comment]
This has not been fixed

**Comment by DodgerDave** [comment]
Fixed 5-7
