### ISSUE TITLE
Wintax - CA - Schedule A non-job related expense causing validation error

### ISSUE THREAD

**Issue by MHGray** [TaxwareSupport/Issue-Reports#494]
**Client Name:**  
Pamela

**Client ID:**  
529-86-1

**Description:**  
If on federal schedule A they have deductions under the 2% category that are both job related and non job related, they will get a validation error for the non job related ones. It doesn't put in the CA description in the XML.
![image](https://user-images.githubusercontent.com/8196735/55515153-b65bfc00-561e-11e9-8f82-5d54999b34c3.png)
***
![image](https://user-images.githubusercontent.com/8196735/55515165-be1ba080-561e-11e9-955e-1df759310079.png)
***
![image](https://user-images.githubusercontent.com/8196735/55515209-db506f00-561e-11e9-8fd9-0444a4740915.png)

**Steps to Reproduce:**  
Use Data Provided

**Data Location:**
R:\Matt\CAScheduleAMissingDetail

**Comment by DodgerDave** [comment]
Fixed 4-4
