### ISSUE TITLE
Wintax - CA - Returns getting adjusted due to XML line showing CA deductions incorrectly

### ISSUE THREAD

**Issue by MHGray** [TaxwareSupport/Issue-Reports#496]
**Client Name:**  
Yvonne

**Client ID:**  
21051

**Description:**  
![image](https://user-images.githubusercontent.com/8196735/55578440-c204fc80-56ca-11e9-871b-629b3144b6da.png)
The <CADeductions> line CA is picking up as what the amount should be but on the 540 it is carrying the itemized deduction amount which is the correct amount. It seems like CADeductions should equal the itemized deduction amount. Clients are receiving letters and adjustments because of this.

**Steps to Reproduce:**  
Use Data provided

**Data Location:**
R:\Matt\CAItemizedDeduction

**Comment by DodgerDave** [comment]
Fixed 4-4
