### ISSUE TITLE
Wintax - client prior year loss is not carrying to state correctly

### ISSUE THREAD

**Issue by TwZach** [TaxwareSupport/Issue-Reports#497]
**Client Name:**  
nid

**Client ID:**  
21486

**Description:**  
The clients prior year unallowed loss is not carrying to the 3801 correctly. 

**Steps to Reproduce:**  
open client data -> preview return -> Ca form 3801

**Data Location:**
R:\Zac\2018clientdata\21486clientdat

**Comment by DodgerDave** [comment]
User needed to enter prior year unallowed loss for state.
