### ISSUE TITLE
1040 NextGen - ELF Tracker - Reprocessing CA Ack does not set status and leaves off on Grey Screen.

### ISSUE THREAD

**Issue by MHGray** [TaxwareSupport/Issue-Reports#5]
**Client Name:**  
Bianca

**Client ID:**  
10723

**Description:**   
They try and reprocess CA ack for this client, after preview of ack shows, they push the close button and it leaves grey screen up (Have to close out of program entirely to get rid of grey screen). Upon checking client's E-File status, it has not updated from 'Awaiting Acknowledgement' to 'Accepted' as it should. 

**Reproduce:**  
Use Data available? Did not have time to test it when making this bug report. Will test tomorrow.

**Data Location:** 
R:\Matt\CAElfTrackIssue

**Comment by MyNameIsDonovan** [comment]
I think we figured out the issue with this right? I need to fix acks with extensions?

**Comment by MHGray** [comment]
Right. Something about the extensions from the comparison tool not having client IDs right away so it needs to check by social to match to a client ID if the first one it hits is an extension or something like that.

**Comment by MyNameIsDonovan** [comment]
I think this was resolved in the 7/25 update.
