### ISSUE TITLE
2018 Wintax --> Recall Current/Prior --> Search by TP SSN Function Not Working

### ISSUE THREAD

**Issue by twnathan** [TaxwareSupport/Issue-Reports#50]
**Client Name:**  
ENRIQUE SANCHEZ

**Client ID:**  
22022

**Description:**  
2018 Wintax --> Recall Client --> Search by TP SSN function not working. When clicked into, throws "Sequence contains no matching element" error. Clicking OK and attempting to add digits to the field throws " 'Table' type does not have property named ", so cannot sort data collection. Also, Sort By SSN function does not work --> same issue.

**Reproduce:**  
Reproduced on multiple in-office computers

**Data Location:**

**Comment by MyNameIsDonovan** [comment]
Fixed in next patch
