### ISSUE TITLE
2018 Wintax - 1041 K-1 to Sch B - Fiduc K-1 info not Carrying to Sch B

### ISSUE THREAD

**Issue by twnathan** [TaxwareSupport/Issue-Reports#501]
**Client Name:**  
STEVE WILLIAMS

**Client ID:**  
9913

**Description:**  
1041 K-1 info not carrying into Sch B, leading to FED reject

![image](https://user-images.githubusercontent.com/44508876/55739713-7316da00-59de-11e9-866e-657f1252dfba.png)

![image](https://user-images.githubusercontent.com/44508876/55739858-c9841880-59de-11e9-9d13-33461bd6b2db.png)

**Steps to Reproduce:**  

**Data Location:**
R:\Nathan\9913 - STEVE WILLIAMS - 1041 K1 to Sch B Issue

**Comment by MyNameIsDonovan** [comment]
fixed the data
