### ISSUE TITLE
Wintax - MA - reject for part year resident 

### ISSUE THREAD

**Issue by TwZach** [TaxwareSupport/Issue-Reports#507]
**Client Name:**  
missy

**Client ID:**  
2450

**Description:**  
Client return is getting rejected for amounts on lines 13 and 14 but there is not amounts there

**Steps to Reproduce:** 
see reject -> open client data -> MA -> preview

**Data Location:**
R:\Zac\2018clientdata\2450clientdata

**Comment by DodgerDave** [comment]
Fixed 4-9
