### ISSUE TITLE
Wintax - Schedule D amount in long term gain that should not be

### ISSUE THREAD

**Issue by TwZach** [TaxwareSupport/Issue-Reports#510]
**Client Name:**  
Rafael

**Client ID:**  
20104

**Description:**  
Client has an amount on line 3 in sch D but it does not carry from anywhere i can tell and it changes income amounts

**Steps to Reproduce:**  
open client data -> Sch d -> preview return

**Data Location:**
R:\Zac\2018clientdata\20104clientdata

**Comment by DodgerDave** [comment]
In Sch D choose (04) Total for all long-term transactions, hit enter twice and gain or loss will get zeroed.
