### ISSUE TITLE
Wintax - Schedule 6 - Client not able to speak with IRS despite 3rd party designee checked

### ISSUE THREAD

**Issue by MHGray** [TaxwareSupport/Issue-Reports#512]
**Client Name:**  
Lydia

**Client ID:**  
21705

**Description:**  
Client tried to speak with IRS about a client and IRS said that we are not transmitting the schedule 6 when we should be. 

**Steps to Reproduce:**  
Have a 3rd party designee on return -> Look at XML

**Comment by DodgerDave** [comment]
Its working correctly. Sounds like IRS person was mistaken.
