### ISSUE TITLE
Wintax - form 8962 line 8a is rounding incorrectly

### ISSUE THREAD

**Issue by TwZach** [TaxwareSupport/Issue-Reports#517]
**Client Name:**  
Maria

**Client ID:**  
99015

**Description:**  
On form 8962 line 8A the amount is rounded down but the number is a .5

**Steps to Reproduce:**  
open client data -> form 8962 -> preview -> multiply line 3 and 7 -> does not equal 8A

**Data Location:**
R:\Zac\2018clientdata\99015clientdata

**Comment by DodgerDave** [comment]
Fixed 4-11
