### ISSUE TITLE
Wintax - SCH A - 8829 is not carrying

### ISSUE THREAD

**Issue by twsal** [TaxwareSupport/Issue-Reports#518]
Richard

Richard 

Form 8829 is not carrying over to Schedule A on line 29 for excess carried from 8829. Amounts are not carrying over only into Schedule C.

![Capture](https://user-images.githubusercontent.com/44677096/55991755-d95e5f80-5c5f-11e9-8a53-eee6ac3d8b30.JPG)

![1](https://user-images.githubusercontent.com/44677096/55991763-dcf1e680-5c5f-11e9-8cc4-3e62212a1d42.JPG)

R:\Sal\richard

**Comment by DodgerDave** [comment]
When entered on line 10 and 11 of 8829 they do carry to Sch A.  He had them on line 16 and 17.  I'm not saying the user was wrong to enter the amounts on 16 and 17.
