### ISSUE TITLE
Wintax - CA - Reject on NR for additions regarding NOL difference

### ISSUE THREAD

**Issue by MHGray** [TaxwareSupport/Issue-Reports#520]
**Client Name:**  
Don

**Client ID:**  
152-86

**Description:**  
![image](https://user-images.githubusercontent.com/8196735/56002856-eb98c780-5c78-11e9-958a-6dcac6db92b4.png)
Client getting this reject and I have no idea how to fix it. The print on it looks correct, but the CA has trouble with the XML. Print is below.
![image](https://user-images.githubusercontent.com/8196735/56003020-9f9a5280-5c79-11e9-8281-8d64e5eec8c3.png)

**Steps to Reproduce:**  
Use Data Provided

**Data Location:**
R:\Matt\152-86CAScheduleAReject

**Comment by DodgerDave** [comment]
Fixed 4-12
