### ISSUE TITLE
Wintax Va not carry rental loss issue

### ISSUE THREAD

**Issue by twraul** [TaxwareSupport/Issue-Reports#521]
**Client Name:**  
Joe Nalley

**Client ID:**  
21634

**Description:**  
Viriginia State return carrying rental loss from 2017 -2437 instead of 2018 rental loss of -3028 even though -3028 was entered on 2018 state return.  Also line 3 of return is not calculating correctly carrying over Fed AGI from return which is being filed Married Joint, VA return is being filed Married Seperate.

**Steps to Reproduce:**  
Captured Data - connected with client to view issue

**Data Location:**
R Drive Raul Folder 21634

**Comment by DodgerDave** [comment]
Rental was carrying.  Fixed AGI on Form 763, line 1 when MFS
