### ISSUE TITLE
2018 Wintax - MT Return - Amount Owed Calculating Correctly in Summary but not Calculating Correctly in XML/Print/Preview

### ISSUE THREAD

**Issue by twnathan** [TaxwareSupport/Issue-Reports#525]
**Client Name:**  
CECIL @ DOUG NEILL

**Client ID:**  
88172

**Description:**  
Client wants to ensure that the TP and SP won't have to pay $818 tax due for SP but the combined tax due of $336 shown in summary. Please confirm that this will be the case or if an adjustment needs to be made to the XML to avoid having to cut a check for $818.

![image](https://user-images.githubusercontent.com/44508876/56083307-f61da300-5dd7-11e9-8642-7807f436f315.png)

![image](https://user-images.githubusercontent.com/44508876/56083298-df774c00-5dd7-11e9-8a74-ff2cd2fd58df.png)

![image](https://user-images.githubusercontent.com/44508876/56083318-16e5f880-5dd8-11e9-8594-f030d98f7720.png)

**Steps to Reproduce:**  

**Data Location:**
R:\Nathan\88172 - CECIL @ DOUG NEILL - MT Return MFS Total Tax Due

**Comment by twJorge** [comment]
Non issue. Montana does not want the changes to show on the return. Separate form to handle this case. Refer clients to page 8 in instructions.
