### ISSUE TITLE
Wintax - Alabama - Getting a reject for a math error that seems to work

### ISSUE THREAD

**Issue by TwZach** [TaxwareSupport/Issue-Reports#526]
**Client Name:**  
Charlie

**Client ID:**  
214-86

**Description:**  
Client reject says total income line 8 must equal the sum of lines 5,6 and 7. The preview shows that it does, the Xml does not list the amounts on line 6 and 7 but the total is correct.

**Steps to Reproduce:**  
open client data -> AL -> preview -> validity check -> XML

**Data Location:**
R:\Zac\2018clientdata\214-86clientdata

**Comment by twJorge** [comment]
Fixed
