### ISSUE TITLE
2018 Wintax - ACA - Client Shouldn't Qualify for an ACA Exemption Due to Business Income, Needs to Remove Exemption

### ISSUE THREAD

**Issue by twnathan** [TaxwareSupport/Issue-Reports#528]
**Client Name:**  
RANDY LANG

**Client ID:**  
21414

**Description:**  
Client does not believe that TP and family should qualify for the ACA exemption due to business income, but program awarding exemption anyway. The client would like to remove the automatic exemption to avoid penalties he believes that they will incur if they file as is.

**Steps to Reproduce:**  

**Data Location:**
R:\Nathan\21414 - RANDY LANG - Turn Off ACA Exemption

**Comment by DodgerDave** [comment]
A work around is to enter income for dependents on 8965 menu. Just make sure it puts them over "low income" level. That amount won't show anywhere.
