### ISSUE TITLE
2018 Wintax - VA 763 ADJ - Page 2 Calc Error Leads to Reject

### ISSUE THREAD

**Issue by twnathan** [TaxwareSupport/Issue-Reports#530]
**Client Name:**  
GALEN WARD

**Client ID:**  
21468

**Description:**  
Client has the following reject from VA:

![image](https://user-images.githubusercontent.com/44508876/56248492-114d1480-605d-11e9-961a-36db8dbc22be.png)

Page 2 of the VA 763 ADJ stops calculating values at line 10 which carries zeroes down through line 13 leading to the error.

**Steps to Reproduce:**  

**Data Location:**
R:\Nathan\21468 - GALEN WARD - VA 763 ADJ Page 2 Reject

**Comment by DodgerDave** [comment]
Fixed 4-16
