### ISSUE TITLE
Wintax - 8853 - Other Tax Statement on XML not filling out with 8853 info

### ISSUE THREAD

**Issue by MHGray** [TaxwareSupport/Issue-Reports#531]
**Client Name:**  
John

**Client ID:**  
21036

**Description:**  
8853 is producing 150 in tax but it is not being added to the XML which is causing an error.
![image](https://user-images.githubusercontent.com/8196735/56321330-41f38380-611b-11e9-8629-2ab4e066cdb3.png)
![image](https://user-images.githubusercontent.com/8196735/56321350-50da3600-611b-11e9-85e8-4a1ede002445.png)
![image](https://user-images.githubusercontent.com/8196735/56321378-5e8fbb80-611b-11e9-96a7-f4c460428e3f.png)

**Steps to Reproduce:**  
Use Data Provided

**Data Location:**
R:\Matt\MedMsaLitCodeReject21036

**Comment by DodgerDave** [comment]
Fixed 4-17
