### ISSUE TITLE
2018 Wintax - MT MFS on Same Form - Direct Deposit Issue Impacting Refund

### ISSUE THREAD

**Issue by twnathan** [TaxwareSupport/Issue-Reports#537]
**Client Name:**  
KASEY @ MICHELE AYERS

**Client ID:**  
26009

**Description:**  
Client currently has two sets of clients that this impacts. Both are Montana Returns filed as "Married Filing Separate on Same Form." Either the TP or SP would owe taxes while the other received a refund, as seen in the image below. The refund would cover what was owed and provide a small refund.
 
![image](https://user-images.githubusercontent.com/44508876/56692465-1df1ee00-6697-11e9-85ae-82063879617a.png)

The client input information for Direct Deposit into the MT portion of the program so that the TP & SP could receive the refund. They did not input Direct Debit information.

However, the client was debited the amount owed and then refunded the smaller refund amount. In the example above, the TP was debited $862 and then refunded $57, leaving them short -$862.

Additional information regarding what was transmitted to the state of MT is attached to the paper copy of this bug report.

**Steps to Reproduce:**  

**Data Location:**

**Comment by twJorge** [comment]
Fixed
