### ISSUE TITLE
2018 Wintax - MD 502 - Married Filing Separate 502 Doesn't List Spouse Last Name

### ISSUE THREAD

**Issue by twnathan** [TaxwareSupport/Issue-Reports#539]
**Client Name:**  
GOLDIE @ LINWOOD JENNINGS

**Client ID:**  
523-86

**Description:**  
Spouse Last Name is just "Jones" but nothing listed -- transmits without issue, but preview/print version should be fixed.

![image](https://user-images.githubusercontent.com/44508876/56767700-40503e00-6761-11e9-92ac-1b042bd5d9fe.png)

**Steps to Reproduce:**  

**Data Location:**

**Comment by DodgerDave** [comment]
Fixed 5-2
