### ISSUE TITLE
2018 WinPay --> Patch Update --> Fail - Error Code 9 --> Invalid Patch File WP18_010118_042318.rtp

### ISSUE THREAD

**Issue by twnathan** [TaxwareSupport/Issue-Reports#54]
**Client Name:**  
VAROUJ TOTLIAN, CPA

**Client ID:**  
413-86

**Description:**  
Client attempts update of new 2018 WinPay Payroll Checkwrite --> Finds update --> DL/Install update --> Finished w/ status: Fail - Error Code 9 --> Search for invalid patch file in C:\TWWinPay shows no .rtp file --> Re-install did nothing

**Reproduce:**  
Reproduced twice on client computer, but WinPay up to date on tech computer

![image](https://user-images.githubusercontent.com/44508876/50493146-75759b00-09d0-11e9-88dc-dbabeb566b44.png)

**Data Location:**
Image provided above

**Comment by MHGray** [comment]
Client wasn't up-to-date. Installed current payroll. For some reason she was being blocked on downloading the patch resulting in a patch file that was 0kb. Downloaded patch file manually which ran smoothly.
