### ISSUE TITLE
Wintax - MT - Itemization limiting to 5k instead of 10 on single returns

### ISSUE THREAD

**Issue by MHGray** [TaxwareSupport/Issue-Reports#540]
**Client Name:**  
Brenda

**Client ID:**  
87133

**Description:**  
MT is limiting sales tax itemization section to 5k on single returns when it should be 10k.
![image](https://user-images.githubusercontent.com/8196735/56769487-311fbf00-6766-11e9-9bcb-bcfda55cdafe.png)

**Comment by twJorge** [comment]
Fixed
