### ISSUE TITLE
2018 Wintax - NY Return - Withholding Reject

### ISSUE THREAD

**Issue by twnathan** [TaxwareSupport/Issue-Reports#541]
**Client Name:**  
JHOSE CASTANEDA

**Client ID:**  
20127

**Description:**  
Client has the following reject repeatedly for a part-year NY resident:

![image](https://user-images.githubusercontent.com/44508876/56977525-309e7400-6b2a-11e9-9247-789e8cd72286.png)

Return has CA withholding in the NY Return XML -- not sure if that is the issue

**Steps to Reproduce:**  

**Data Location:**
R:\Nathan\20127 - JHOSE CASTANEDA - NY Withholding Reject

**Comment by DodgerDave** [comment]
User had wrong amounts for NYS and NYC withholding in NY input.
