### ISSUE TITLE
Wintax - MD 502 - Married Filing Separate 502 Exemptions

### ISSUE THREAD

**Issue by twsal** [TaxwareSupport/Issue-Reports#542]
Goldy 

523-86

Line B on exemptions, the box is being checked for the spouse when it should be unchecked when filing married separate return.

![Capture](https://user-images.githubusercontent.com/44677096/57033028-a248f180-6c00-11e9-8172-73b8ea0439b1.JPG)

R:\Sal\goldy 523-86

**Comment by DodgerDave** [comment]
Fixed 5-2
