### ISSUE TITLE
2018 Wintax - Due Diligence/EIC - Previously EIC Qualified Dependent Greyed Out with "ON EIC" Still Checkmarked

### ISSUE THREAD

**Issue by twnathan** [TaxwareSupport/Issue-Reports#543]
**Client Name:**  
VARIOUS

**Client ID:**  

**Description:**  
When completing Due Diligence and the EIC in the program, there can be changes made to dependents after the fact that disqualify them from being included on the EIC. However, if they were previously qualified, the Due Diligence "ON EIC" checkbox will be marked for that name. Once they are disqualified, it greys out that checkbox, but with the box still checkmarked. This causes a validation error. This has been an issue all tax season.

![image](https://user-images.githubusercontent.com/44508876/57099165-a17f9080-6cd0-11e9-8fae-a348015b580c.png)

To get around this issue, we have had to go into the dependents and make a change that qualifies them for EIC again (age change, disability, etc.), go back into the EIC Due Diligence. un-check the "ON EIC" checkbox, and then go back into the dependent and undo the changes.

We would request that if something disqualifies a dependent that the "ON EIC" checkbox be unmarked automatically along with the grey out.

**Steps to Reproduce:**  
Generate dependent who qualifies for EIC -> complete Due Diligence and EIC -> Change dependent to not qualify -> stuck on EIC

**Data Location:**

**Comment by DodgerDave** [comment]
Fixed 5-2. It will now uncheck the "ON EIC" box automatically for this situtaion.
