### ISSUE TITLE
2018 Wintax - 4684 Casualty Loss - 4684 Not Attaching to XML

### ISSUE THREAD

**Issue by twnathan** [TaxwareSupport/Issue-Reports#549]
**Client Name:**  
RON LAUDIE

**Client ID:**  
21055

**Description:**  
![image](https://user-images.githubusercontent.com/44508876/57561239-653ad880-733f-11e9-93b8-295180767d86.png)

TP was a victim of a fraud which is being reported on the Form 4684. Not sure if he can claim it, but it is populating correctly on the forms and clears validity check. However, the Form 4684 does not attach to the XML, leading to the rejection.

**Steps to Reproduce:**  

**Data Location:**
R:\Nathan\21055 - RON LAUDIE - 4684 Reject

**Comment by DodgerDave** [comment]
Fixed 5-13
