### ISSUE TITLE
990 - CA 199 - Input Expenses [Line 12] Cannot be deleted

### ISSUE THREAD

**Issue by twnathan** [TaxwareSupport/Issue-Reports#550]
**Client Name:**  
SANDY FINESTONE

**Client ID:**  
213150

**Description:**  
990 -> CA 199 -> [02] Receipts and Expenses -> [12] Contributions, gifts, grants, and similar amounts paid

Inputs made under here cannot be deleted, and removing the info leaves blank lines which may lead to problems with print or others

![image](https://user-images.githubusercontent.com/44508876/57644285-a2d27800-7570-11e9-944f-a00ef9093bf9.png)

**Steps to Reproduce:**  
990 -> CA 199 -> [02] Receipts and Expenses -> [12] Contributions, gifts, grants, and similar amounts paid -> Input info -> Attempt to delete entry afterward

**Data Location:**
R:\Nathan\213150 - SANDY FINESTONE - 990 to CA 199 Removing Expenses

**Comment by DodgerDave** [comment]
Fixed 5-13
