### ISSUE TITLE
2018 Wintax - NY Return - Dependent DOB is Correct in FED & NY but XML for NY is Wrong

### ISSUE THREAD

**Issue by twnathan** [TaxwareSupport/Issue-Reports#558]
**Client Name:**  
ELLA JORDAN

**Client ID:**  
21258

**Description:**  
![image](https://user-images.githubusercontent.com/44508876/57949195-9a43af80-7898-11e9-90e1-c8ae7b004db6.png)

![image](https://user-images.githubusercontent.com/44508876/57949265-c52e0380-7898-11e9-8752-17734959caea.png)

![image](https://user-images.githubusercontent.com/44508876/57949291-d414b600-7898-11e9-8104-ab9c1d6d7745.png)

![image](https://user-images.githubusercontent.com/44508876/57949315-e989e000-7898-11e9-8a95-3773a7bd66eb.png)

**Steps to Reproduce:**  

**Data Location:**
R:\Nathan\21258 - ELLA JORDAN - NY Dependent DOB Missing Digit in XML

**Comment by DodgerDave** [comment]
It needed to be corrected in IT-215
