### ISSUE TITLE
Wintax - 8949 - Missing adjustment code Z

### ISSUE THREAD

**Issue by MHGray** [TaxwareSupport/Issue-Reports#572]
**Client Name:**  
Jeff

**Client ID:**  
98014

**Description:**  
Client wants to know if we can add adjustment code Z.
![image](https://user-images.githubusercontent.com/8196735/59527298-044b7680-8e90-11e9-9c0e-776d0b3f20fa.png)
![image](https://user-images.githubusercontent.com/8196735/59527187-bd5d8100-8e8f-11e9-9cc2-2d1b9d3c2c37.png)

**Comment by DodgerDave** [comment]
Done 6-17.
