### ISSUE TITLE
Wintax - MA - M-2210 doesn't calculate correctly causing letters from the state

### ISSUE THREAD

**Issue by MHGray** [TaxwareSupport/Issue-Reports#575]
**Client Name:**  
Missy

**Client ID:**  
21150

**Description:**  
M-2210 doesn't calculate correctly. according to MA. This client has received ~20 letters from various taxpayers regarding this miscalculation. She provided what Taxware produces vs what ATX produces which is included in the data, along with the clients data. 

It looks like it is something to do with the calculation of the number of days on line 14 of the form. I've tried overriding the dates for line 13 but it doesn't change the amounts on line 14 at all.

**Data Location:**
R:\Matt\MA2210Issue

**Comment by DodgerDave** [comment]
Fixed 6-19. Will post patch on 6-20.
