### ISSUE TITLE
Wintax - CA - State Total Tax Reject

### ISSUE THREAD

**Issue by twsal** [TaxwareSupport/Issue-Reports#577]
John

21036

Return keeps getting a reject, due to the total taxes paid, being higher. On the W2 they are coming out to 460 for the state, but carry's over 521 to the state instead, causing the return to get a reject.

**Steps to Reproduce:**  
![image](https://user-images.githubusercontent.com/44677096/59713364-201e8780-91c4-11e9-9d4e-113e7ccd262b.png)

R:\Sal\John 21036

**Comment by DodgerDave** [comment]
When state sales tax is greater then state income tax withheld and not itemizing on federal than override sales tax on Sch A with state withholding amount
