### ISSUE TITLE
1099 All Employee print 

### ISSUE THREAD

**Issue by twsal** [TaxwareSupport/Issue-Reports#58]
Brenda

87133

When printing all employees, with no collated, it will only select one employee on all copies, instead of having one for each employee. When you say yes to collated, it will print one for each employee. This only happens on copy b, copy 1, and copy2.  Copy C and Federal copy are ok

1099 Reports-¬---> Selection of 1099 to print (copy b)--->All Employee---->no to collated

![1099 bug](https://user-images.githubusercontent.com/44677096/50655522-4ff30f00-0f45-11e9-917d-a098258a5875.JPG)

**Comment by MHGray** [comment]
Seems fixed 01.04.2019 Patch
