### ISSUE TITLE
Wintax - Schedule C - No place to put business address if foreign

### ISSUE THREAD

**Issue by MHGray** [TaxwareSupport/Issue-Reports#581]
**Client Name:**  
Burt

**Client ID:**  
3170

**Description:**  
On schedule C there is no check mark for foreign business address. I checked the schema list and it looks like it should be supported for efile.
![image](https://user-images.githubusercontent.com/8196735/60115929-de459200-972b-11e9-917e-ca119a0c2cc5.png)

**Comment by DodgerDave** [comment]
Done 7-2
