### ISSUE TITLE
Wintax - 1040 - HoH qualifying child name and SSN doesn't appear on print

### ISSUE THREAD

**Issue by MHGray** [TaxwareSupport/Issue-Reports#585]
**Client Name:**  
Connie

**Client ID:**  
28020

**Description:**  
If filing status is Head of Household, and they have a qualifying child with no dependents, then the name of the qualifying child (and SSN if it is the same as 17) should appear in the top filing status line.

![image](https://user-images.githubusercontent.com/8196735/60372675-460d0e80-99b2-11e9-9857-75b63188aa49.png)

![image](https://user-images.githubusercontent.com/8196735/60372782-b7e55800-99b2-11e9-9d63-cd3bdde75136.png)

**Comment by DodgerDave** [comment]
Fixed 7-3
