### ISSUE TITLE
Wintax - IL - Return won't clear validation even though schema is clear

### ISSUE THREAD

**Issue by MHGray** [TaxwareSupport/Issue-Reports#586]
**Client Name:**  
Latoya

**Description:**  
Return won't clear yellow validation error for schema check even though it passes schema.

**Steps to Reproduce:**  
Validate state and then go to summary, Still yellow.

**Data Location:**
R:\Matt\ILWontClear

**Comment by MyNameIsDonovan** [comment]
Fixed
