### ISSUE TITLE
2018 Wintax - MA Form 1 HC - MA Charging for Health Care Penalty when FED Penalty Should Override It

### ISSUE THREAD

**Issue by twnathan** [TaxwareSupport/Issue-Reports#587]
**Client Name:**  
MISSY HEY:LIN

**Client ID:**  
2450

**Description:**  
*According to the taxpreparer* -- When a MA taxpayer is uninsured they are charged a health care penalty by both the FED and the state of MA. If the FED health care penalty is greater than the MA health care penalty, then the TP only needs to pay the FED penalty.

![image](https://user-images.githubusercontent.com/44508876/60607144-90570c80-9d71-11e9-85b0-86ab78ea73f8.png)

When this particular client was e-filed, the FED penalty exceeded the MA penalty; MA should be waived. However, MA mailed a bill to the TP for the MA health care penalty amount, stating that they owed because the FED amount was $0. In looking at the XML for the client file (not the transmission -- couldn't find it one their computer) the MA portion shows no health care penalty info for either FED or MA. Print preview of the MA return shows what you see above -- both penalties for FED and MA.

Client wants to know if she is wrong or if this is a bug, whether or not MA is mistaken, and if this can be patched or if it needs to be paper filed.

**Steps to Reproduce:**  

**Data Location:**
R:\Nathan\2450 - MISSY HEYLIN - MA Health Care Penalty Issue

**Comment by DodgerDave** [comment]
In the case where fed penalty is greater than MA penalty, nothing was showing in the XML.  I changed it so it will (just like it does on the printed Form 1)
