### ISSUE TITLE
Wintax - K1- Not able to remove K1's

### ISSUE THREAD

**Issue by twsal** [TaxwareSupport/Issue-Reports#589]
Meredith 

205-86

Keeps getting an error when trying to remove a blank K1 from the input. The error will say "Index was outside the bounds of the array".

![image](https://user-images.githubusercontent.com/44677096/60846047-0c4abd80-a193-11e9-9d9a-2b1bc700a232.png)

R:\Sal\meredith 205-86

**Comment by MyNameIsDonovan** [comment]
I manually deleted the k1, should be ok to transfer back to the client.
