### ISSUE TITLE
2018 Wintax --> Current Year Data Path --> Add Button not Functioning Proper

### ISSUE THREAD

**Issue by twnathan** [TaxwareSupport/Issue-Reports#59]
**Client Name:**  
CHARLIE TOWN

**Client ID:**  
214-86

**Description:**  
2018 Wintax --> Current Year Data Path --> Add --> Successfully adds new data path to current year data path list --> exit to Main Menu --> re-enter Current Year Data Path selection --> one option that existed before disappears

Client has three folders he would like to have in current year data path selection. However, when he adds a new one, then exits to Main Menu and then re-enters Current Year Data Path, the selection is no longer three option but two, with the new option he selected replacing one of the ones he had put in before.

Updated his program and tried adding data path through a few different menus unsuccessfully.

**Reproduce:**  
Reproduced on client computer --> could not reproduce on tech computer --> Scott D. has encountered this issue before

**Data Location:**
N/A

**Comment by MyNameIsDonovan** [comment]
This should be fixed in the next patch
