### ISSUE TITLE
2018 Wintax - North Carolina estimates - Print and preview buttons don't function

### ISSUE THREAD

**Issue by twMikeE** [TaxwareSupport/Issue-Reports#593]
**Client Name:**  
Walter

**Client ID:**  
21118-4

**Description:**  
The print/preview buttons inside of the NC State estimates screen don't seem to function

**Steps to Reproduce:**  
With a NC state return, attempt to print or preview an estimate via the buttons at the top of the window.

**Data Location:**
N/A

**Comment by DodgerDave** [comment]
Legacy states no longer have that capability when on the State Estimates menu.  Must use FormPrint to preview or print state estimates for legacy states.  NC will be NextGen in 2019 Wintax.
