### ISSUE TITLE
1040 NextGen - AL - 

### ISSUE THREAD

**Issue by MHGray** [TaxwareSupport/Issue-Reports#6]
**Client Name:**  
Burnetta Davis

**Client ID:**  
21401

**Description:**  
![image](https://user-images.githubusercontent.com/8196735/41800477-9fd6c1f6-762a-11e8-9da3-c7c1f257bc5d.png)
Reject caused by NextGen putting in Spouse information with Married Filing Separate return when it shouldn't be. Works correctly in Legacy. Client already sent with legacy this particular return, but needs to be fixed for future.

**Reproduce:**  
Use Data Provided

**Data Location:** 
R:\Matt\ALMarriedSeparateRejectNG

**Comment by swd7** [comment]
This was actually fixed a few week ago but boland was sick and then I forgot to post it....I have a big note on my white board to remind us to post the patch on Monday.
