### ISSUE TITLE
Wintax- AL - Sch D amount of 0 on AL NR produces validation error

### ISSUE THREAD

**Issue by MHGray** [TaxwareSupport/Issue-Reports#602]
**Client Name:**  
Guy

**Client ID:**  
213104

**Description:**  
![image](https://user-images.githubusercontent.com/8196735/62075488-0a0bda00-b1fa-11e9-8063-21e96e5e6550.png)
AL NR amount should be 0 for schedule D income, but removing the schedule D amount on regular AL side produces a reject
![image](https://user-images.githubusercontent.com/8196735/62075530-2f004d00-b1fa-11e9-92c8-b7d320238c77.png)
Having a 0 amount on the NR produces the validation error meaning they can't send at all.

**Steps to Reproduce:**  
Use data provided.

**Data Location:**
R:\Matt\213104ALMSData

**Comment by twJorge** [comment]
Fixed, made load mandatory.
