### ISSUE TITLE
Wintax - If their data paths have changed, creates trouble for grabbing acks

### ISSUE THREAD

**Issue by MHGray** [TaxwareSupport/Issue-Reports#607]
**Client Name:**  
Dave

**Client ID:**  
213190

**Description:**  
If the data path has changed since the time of transmission (or they are networked with different data paths) pulling in an ack will cause an error and break the print routine. The error of path not found does not produce an error log.

**Steps to Reproduce:**  
Use Data Provided

**Data Location:**
R:\Matt\DangDataDrives

**Comment by MyNameIsDonovan** [comment]
Missing clients no longer try to get updated
I the future I'll try to have it fix the elftracker at the same time
