### ISSUE TITLE
Winpay - check formatter is not saving checks

### ISSUE THREAD

**Issue by TwZach** [TaxwareSupport/Issue-Reports#611]
**Client Name:**  
Lusy

**Client ID:**  
23014

**Description:**  
When editing and saving a new or edited check in winpay, the changes do not stay and are reset. 

**Steps to Reproduce:**  
Open winpay, select client data, check formats, open a check format delete a part of the check, save to different or same name, employer setup, select new check format, reports, paychecks, preview existing paycheck, deleted item is still there, then when you return to check formats and edit it again the deleted aspects are still there. 

**Data Location:**
R:\Zac\client data\winpay 21026-1

**Comment by MHGray** [comment]
Possibly due to Data Path or install location, otherwise due to a file sync program. Will have to take a look when they call back in
