### ISSUE TITLE
Wintax - Prior Year Compare - Excess Advance PTC Repayment input and print issues

### ISSUE THREAD

**Issue by MHGray** [TaxwareSupport/Issue-Reports#613]
**Client Name:**  
Monte

**Client ID:**  
21307

**Description:**  
If prior year had Excess PTC Repayments (8962), It does not show in the prior year column in the Prior Year Compare section. On the print for the same Prior Year Compare section it looks like the 2018 amount is put in the 2017 box and the 'Change' amount is put in the 2018 box. See attached sheet

**Steps to Reproduce:**  
Use provided Data.

**Data Location:**
R:\Matt\PriorYearCompareBug

**Comment by DodgerDave** [comment]
Fixed 9-13
