### ISSUE TITLE
Wintax - AL - Nonresident Return increasing AL income erroneously

### ISSUE THREAD

**Issue by MHGray** [TaxwareSupport/Issue-Reports#614]
**Client Name:**  
Leonard

**Client ID:**  
21112

**Description:**  
AL income showing much higher than it actually should be. Seems to be tied with resident/nonresident status. This is causing an AL reject of the AL Wages not matching the federal return.

**Steps to Reproduce:**  
Use Data provided. 
AL -> [02] Income -> [01] Wages shows 91,988 but actual wages are 67,019 -> In the wage screen itself it shows the W2 amounts but altering them does not alter the total on the previous screen -> Go back to AL main menu -> [01] Basic Info -> [02] Change Residency Status to resident -> Back to AL main menu -> [02] Income -> [01] Wages show correct amount of 67,019 -> Going into the wage screen and altering the amounts still does not modify the amounts on the previous page.

**Data Location:**
R:\Matt\ALNRWageIssue

**Comment by twJorge** [comment]
Was counting income twice from W2s with multiple entries from different states, fixed.
