### ISSUE TITLE
Wintax - 8801 - 8801 credit not calculating correctly til you hit summary

### ISSUE THREAD

**Issue by MHGray** [TaxwareSupport/Issue-Reports#615]
**Client Name:**  
Sandy

**Client ID:**  
213150

**Description:**  
8801 Credit that carries to the Schedule 3 is wrong the first time you go into line input/ preview on form input. Program calculates correctly once you hit the summary screen.
Before:
![image](https://user-images.githubusercontent.com/8196735/65440238-46644c80-dddd-11e9-834d-d4ff161a14d7.png)
After:
![image](https://user-images.githubusercontent.com/8196735/65440198-35b3d680-dddd-11e9-821d-0599a4120b1e.png)

**Steps to Reproduce:**  
Use Data Provided. Line Input ->line 12 Reads "12,287" -> Press Okay ->  [11] Line Input -> Line 12 now reads "4,544"

**Data Location:**
R:\Matt\8801WrongTimeCalc

**Comment by DodgerDave** [comment]
Fixed 9-23
