### ISSUE TITLE
Wintax - 8801 - Print formatting missing comma on a couple lines

### ISSUE THREAD

**Issue by MHGray** [TaxwareSupport/Issue-Reports#616]
**Client Name:**  
Sandy

**Client ID:**  
213150

**Description:**  
Lines 7-10, and line 22 of the 8801 print are not formatting the amounts with a comma as they should be.
![image](https://user-images.githubusercontent.com/8196735/65440700-fdf95e80-dddd-11e9-8931-2e09a639eec4.png)

**Steps to Reproduce:**  
Use Data Provided. Preview 8801

**Data Location:**
R:\Matt\8801WrongTimeCalc

**Comment by DodgerDave** [comment]
Fixed 9-23
