### ISSUE TITLE
Wintax18 - Hawaii - State Tax ID number not formatting correctly

### ISSUE THREAD

**Issue by MHGray** [TaxwareSupport/Issue-Reports#618]
**Client Name:**  

Marshall
**Client ID:**  
3170

**Description:**  
Hawaii tax ID number not being correctly formatted.
![image](https://user-images.githubusercontent.com/8196735/65705513-76118f80-e03d-11e9-9c2d-8429d7f3ce4d.png)

**Steps to Reproduce:**  
Use data provided.

**Data Location:**
R:\Chris\Hawaii Bug Report

**Comment by twJorge** [comment]
fixed

**Comment by MHGray** [comment]
This also needs to be fixed for the HI Tax ID on Sch C, E, and F. On HI main menu -> [02] Income -> Lines [10],[12], and [16]

**Comment by MHGray** [comment]
You fixed it so the number prints good, but entering just the number so it prints good, breaks the validation:
![image](https://user-images.githubusercontent.com/8196735/66784928-aa37dd80-ee90-11e9-9ed1-f5ba75ecd9ff.png)


With the GE in the input, the print looks stupid cause it is pre-printed:

![image](https://user-images.githubusercontent.com/8196735/66784893-8e343c00-ee90-11e9-83c8-5e6fc4786de9.png)

**Comment by twJorge** [comment]
fixed..... probably
