### ISSUE TITLE
2018 Individual - Form 4797 - Adding gains from disposition of property error

### ISSUE THREAD

**Issue by MHGray** [TaxwareSupport/Issue-Reports#624]
**Client Name:**  
Randal

**Client ID:**  
572-86

**Description:**  
While adding gains from disposition of property there is an error message that states "You have reached the limit of 50 part II Transactions" while there are no entries in part II.

**Steps to Reproduce:**  
Go to forms and schedules open up form 4797, go to part 3 and click add to get the error.
![image](https://user-images.githubusercontent.com/8196735/66438682-4a4dbc80-e9e2-11e9-84e8-37190e08e679.png)

**Data Location:**
R:\Chris\Randall 572-86

**Comment by DodgerDave** [comment]
Increased Part III transactions from 13 to 50. Corrected limit message so it says Part III.
