### ISSUE TITLE
Wintax 17 - OH - Reject caused by no return element in XML

### ISSUE THREAD

**Issue by MHGray** [TaxwareSupport/Issue-Reports#627]
**Client Name:**  
Randall

**Client ID:**  
572-86

**Description:**  
![image](https://user-images.githubusercontent.com/8196735/66687650-3a2f1a80-ec38-11e9-8e65-95b437c736b5.png)

On 2017 return OH is getting rejected due Return element missing. Looks like Schema is version 1.0 so I imagine they changed their schema, though we only download 1.0 when OH is missing. You may need to speak with Scott B to see if OH changed their schema for 17.

**Steps to Reproduce:**  
Only reproduces when return is actually sent, currently does not break in program validation. Use data provided.

**Data Location:**
R:\Matt\OH17Schema

**Comment by twJorge** [comment]
Ohio has acknowledged as an error on their part. Solution is to either keep sending until it accepts the return or paper file.
