### ISSUE TITLE
Wintax - SC - Negative rents and rentals cause proration to go negative. Proration should be limited to 0

### ISSUE THREAD

**Issue by MHGray** [TaxwareSupport/Issue-Reports#628]
**Client Name:**  
21046

**Client ID:**  
Bill

**Description:**  
On a SC Nonresident return, if the adjustedments make SC income negative proration should be limited to 0, otherwise it causes a validation error.
![image](https://user-images.githubusercontent.com/8196735/66766115-354daf00-ee62-11e9-990e-534916eb3410.png)
![image](https://user-images.githubusercontent.com/8196735/66766143-44ccf800-ee62-11e9-8e0c-b191528034a9.png)

**Steps to Reproduce:**  
Make a SC Return -> [02] Adjustments -> Enter a large negative number in one of the income columns.

**Comment by MyNameIsDonovan** [comment]
fixed
