### ISSUE TITLE
Wintax - CA - Sch CA not putting in XML correctly for automatic 2555 carry, causes reject

### ISSUE THREAD

**Issue by MHGray** [TaxwareSupport/Issue-Reports#629]
**Client Name:**  
Haydeh

**Client ID:**  
21033

**Description:**  
Reject below is caused by program not putting the Other Adjustment elements into the subtraction sections on the XML.
![image](https://user-images.githubusercontent.com/8196735/66849889-92159c00-ef2c-11e9-9cc4-32310d1d0304.png)

![image](https://user-images.githubusercontent.com/8196735/66849937-a9ed2000-ef2c-11e9-8dcc-73f6ae41f725.png)

**Steps to Reproduce:**  
Use data provided -> View XML

**Data Location:**
R:\Matt\CASchCA2555

**Comment by DodgerDave** [comment]
Fixed 10-16.
