### ISSUE TITLE
Wintax - MT - NR return with negative fed AGI causes validation error

### ISSUE THREAD

**Issue by MHGray** [TaxwareSupport/Issue-Reports#630]
**Client Name:**  
Sandra

**Client ID:**  
88239

**Description:**  
![image](https://user-images.githubusercontent.com/8196735/66853729-cdb46400-ef34-11e9-9b36-881afed58691.png)
![image](https://user-images.githubusercontent.com/8196735/66853831-081e0100-ef35-11e9-863d-632d2e7a880f.png)

**Steps to Reproduce:**  
Have negative fed AGI -> Put in NR info -> Ratio isn't included in XML or print

**Data Location:**
R:\Matt\MontanaNegativeAGINR

**Comment by twJorge** [comment]
Fixed
