### ISSUE TITLE
Wintax - MFJ-MFS Comparison - SS Witholdings from spouse remain on split returns

### ISSUE THREAD

**Issue by MHGray** [TaxwareSupport/Issue-Reports#639]
**Client Name:**  
Brenda

**Client ID:**  
87133

**Description:**  
If you have a MFJ return with SS witholdings on the spouse, and then use the MFJ-MFS comparison tool to split the return, then on the taxpayer's newly made return the SS withholdings will be included with no normal way of being able to remove those withholdings other than through an override. The program should remove that amount during the split.

**Steps to Reproduce:**  
Use Data Provided. -> Run MFJ-MFS compare tool and split returns -> Go into taxpayer return -> Line [16] of line input shows 5,000 in withholdings from SS even though they have no withholdings

**Comment by DodgerDave** [comment]
Fixed 2-3-20.
