### ISSUE TITLE
Wintax - On new client, HoH status shows spouse input

### ISSUE THREAD

**Issue by MHGray** [TaxwareSupport/Issue-Reports#64]
**Client Name:**  
Enrique

**Client ID:**  
22022

**Description:**  
![image](https://user-images.githubusercontent.com/8196735/50798030-b81a5b80-128b-11e9-8324-aa5774532e98.png)

**Reproduce:**  
Make new client, Choose Head of Household

**Comment by MyNameIsDonovan** [comment]
Fixed, will be in 1.5
