### ISSUE TITLE
Wintax19 - Due diligence

### ISSUE THREAD

**Issue by twsal** [TaxwareSupport/Issue-Reports#641]
Enrique

22022

After adding everything to the Due Diligence for two dependents, it keeps marking it red, if something was missing. 

**Steps to Reproduce:**  
![image](https://user-images.githubusercontent.com/44677096/71695331-a23c5b00-2d66-11ea-912d-063c07377321.png)

R:\Sal\enrique 22022

**Comment by DodgerDave** [comment]
Fixed with 1-3 patch.
