### ISSUE TITLE
Scorp - Sch L balance sheet

### ISSUE THREAD

**Issue by TwZach** [TaxwareSupport/Issue-Reports#642]
**Client Name:**  
Brian

**Client ID:**  
99063

**Description:**  
The drop downs for lines 9 and 26 do not add the ending amounts inputted to the asset side of the balance sheet.

**Steps to Reproduce:**  
Open client -> Sch L -> line 9 or line 26 -> type ending amount nothing populates -> Similar issues in some beginning amounts for lines 9, 26 and 10 

**Data Location:**

**Comment by MHGray** [comment]
Fixed 01/06. Will be in next patch
