### ISSUE TITLE
Fiduciary - Efile - Validity check fails on fed

### ISSUE THREAD

**Issue by MHGray** [TaxwareSupport/Issue-Reports#643]
**Client Name:**  
Dale

**Client ID:**  
21330

**Description:**  
On federal validation I get the message:
![image](https://user-images.githubusercontent.com/8196735/71855009-ba78e680-3094-11ea-84b4-d21e51a12e0a.png)
Not sure why it is failing, and odd that a failure message would show up in green instead of red.

**Steps to Reproduce:**  
Try to validate a fiduc return

**Comment by MyNameIsDonovan** [comment]
Doesn't happen to me... but I think it happened for Dale because schemas were missing from the server?
Closing this as it should be fixed now
