### ISSUE TITLE
Wintax - W2 - Retirement plan checkboxes are in wrong tabbing order

### ISSUE THREAD

**Issue by MHGray** [TaxwareSupport/Issue-Reports#65]
**Client Name:**  
Enrique

**Client ID:**  
22022

**Description:**  
Tabbing order for the three checkboxes in box 13 of the W-2, pictured below, are wrong: 
![image](https://user-images.githubusercontent.com/8196735/50798245-8c4ba580-128c-11e9-8801-f41824eb09a9.png)

Tabbing from [21] should go into the checkboxes. Instead you can only get to them by tabbing 5 times from the mousefree box.

**Reproduce:**  
Try it

**Comment by MyNameIsDonovan** [comment]
fixed in 1.5
