### ISSUE TITLE
Wintax - Preparer Info - Zip is an integer which means NJ preparers can't put in their zip.

### ISSUE THREAD

**Issue by MHGray** [TaxwareSupport/Issue-Reports#653]
**Client Name:**  
Felix

**Client ID:**  
21119

**Description:**  
Tax preparer information has a spot for ZIP, but the SQLLite DB3 has that field as an integer. All NJ zip codes start with '0' so the zip code gets trimmed to a four digit number. This causes rejects. 
![image](https://user-images.githubusercontent.com/8196735/72372307-f0ccec00-36ba-11ea-8bcd-35b8bba3d4b6.png)

**Steps to Reproduce:**  
Preparer Setup -> put in 08861 into zip code and press enter -> Zip code immediately gets trimmed to 8861

**Comment by MyNameIsDonovan** [comment]
We fixed this on the clients machine. This looks like an issue with new year wizard from the master tax menu
Deleting the prep and having wintax/app create it works properly
