### ISSUE TITLE
Wintax 1040 - basic info and due diligence - relationships for dependents change when they shouldn't

### ISSUE THREAD

**Issue by TwZach** [TaxwareSupport/Issue-Reports#654]
**Client Name:**  
David

**Client ID:**  
5980

**Description:**  
If you have a dependent that can be claimed by another person in the due diligence, if you answer the question of their relationship is it changes the taxpayers relationship to that.
![image](https://user-images.githubusercontent.com/45858181/72385183-c0457c00-36d3-11ea-984e-8b61a7a4917a.png)

**Steps to Reproduce:**  
open client -> enter dependent as a relationship grandchild -> open due diligence -> oprn dependents due diligence -> answer yes to 4 -> set relationship as son -> open basic info -> dependents relationship has changed.

**Data Location:**

**Comment by DodgerDave** [comment]
Fixed on 1-15.
