### ISSUE TITLE
Wintax - Due Dilligence - Validity Error for Due Diligence, but 8867 is complete

### ISSUE THREAD

**Issue by MHGray** [TaxwareSupport/Issue-Reports#655]
**Client Name:**  
Stacy

**Client ID:**  
21915

**Description:**  
Client has validity error for incomplete due diligence, but due diligence seems to be complete.
![image](https://user-images.githubusercontent.com/8196735/72389227-bb38fa80-36dc-11ea-8848-27cfd34e0025.png)
![image](https://user-images.githubusercontent.com/8196735/72389243-c2600880-36dc-11ea-8ad1-df4a9e2cb576.png)

**Steps to Reproduce:**  
Use Data Provided

**Data Location:**
R:\Matt\8867Ghost

**Comment by DodgerDave** [comment]
User had box checked On EIC screen that says allow EIC without completing due diligence.
