### ISSUE TITLE
Wintax - 8812- Carry

### ISSUE THREAD

**Issue by twsal** [TaxwareSupport/Issue-Reports#662]
Jose

213181

When entering the schedule 8812,  the amount on line 13a is not being carried over to line 2 from the 1040.

![image](https://user-images.githubusercontent.com/44677096/72543491-ac685a00-383a-11ea-9d7f-533449cfe09f.png)

![image](https://user-images.githubusercontent.com/44677096/72543532-be49fd00-383a-11ea-8831-146a0b9b6f9e.png)

R:\Sal\jose 213181

**Comment by DodgerDave** [comment]
This ended up being a problem with the display on Line Input.  The 8812 was working right,
