### ISSUE TITLE
Corp/S-Corp - Recall Client - Phone and Date Return Started don't show in Client Grid

### ISSUE THREAD

**Issue by MHGray** [TaxwareSupport/Issue-Reports#666]
**Client Name:**  
Rachel

**Client ID:**  
21118

**Description:**  
![image](https://user-images.githubusercontent.com/8196735/72565218-3ed22300-3866-11ea-9cad-a0a4ecedb7d1.png)

**Steps to Reproduce:**  
Add a phone number

**Comment by MyNameIsDonovan** [comment]
The phone number looks like the efile officer phone number... not sure if this is correct though
Legacy didn't have these fields... it doesn't look like date return started is working in any of the entities...
I run this by Scott on Monday

**Comment by MyNameIsDonovan** [comment]
removed date started, fixed phones
