### ISSUE TITLE
Wintax - NY - TR-579 Not printing with Federal 8879 on EFILE Menu

### ISSUE THREAD

**Issue by MHGray** [TaxwareSupport/Issue-Reports#669]
**Client Name:**  
Mike

**Client ID:**  
87193

**Description:**  
TR-579 (NY Signature Document) not printing with the 8879 from the E-File Menu. Client says it did it last year.

**Comment by DodgerDave** [comment]
I picked a random NY return and it printed for me.  I'll need data where it doesn't print.

**Comment by MHGray** [comment]
Have data of one not showing up.
R:\Matt\NY8879

**Comment by MHGray** [comment]
fixed
