### ISSUE TITLE
Wintax - NY - Driver's Licence Document Number not carry from fed

### ISSUE THREAD

**Issue by MHGray** [TaxwareSupport/Issue-Reports#670]
**Client Name:**  
Mike

**Client ID:**  
87193

**Description:**  
Drivers License Additional Info on fed doesn't carry to NY return as a document number and causes validation error

**Comment by DodgerDave** [comment]
I couldn't duplicate this.  Do you have any data?

**Comment by MHGray** [comment]
Sorry looks like I got it wrong when he told me the first time. Looks like his complaint is to do with recalling from prior year, the Drivers License prompt. It has their prior year info on the bottom but you can't recall the Additional Info from prior year. 
![image](https://user-images.githubusercontent.com/8196735/72747909-c079c780-3b6a-11ea-9a41-a1eb6624802c.png)

**Comment by DodgerDave** [comment]
Fixed 1-20.
