### ISSUE TITLE
Wintax- NY - Direct Deposit Authorization not picking up NY State Direct Deposit

### ISSUE THREAD

**Issue by MHGray** [TaxwareSupport/Issue-Reports#672]
**Client Name:**  
Message Boards

**Client ID:**  
---

**Description:**  
![image](https://user-images.githubusercontent.com/8196735/72666656-6a215300-39c9-11ea-9634-ccc7eb8f69ba.png)
![image](https://user-images.githubusercontent.com/8196735/72666696-a0f76900-39c9-11ea-89bc-448886dd3872.png)

**Steps to Reproduce:**  
Have a NY Refund -> Enter Direct Deposit Info on NY -> Preview return and NY direct deposit info doesn't show up

**Comment by DodgerDave** [comment]
Fixed 1-20
