### ISSUE TITLE
Wintax - IN - CC40 College list not coming up

### ISSUE THREAD

**Issue by MHGray** [TaxwareSupport/Issue-Reports#680]
**Client Name:**  
Message Boards - IN FORM CC-40

**Client ID:**  
---

**Description:**  
The '...' buttons for choosing the college and 4 digit code don't do anything. Also seems like mouse free goes straight to the 4 digit code box instead of the name (or presumably '...' button).
![image](https://user-images.githubusercontent.com/8196735/72818360-355b0900-3c20-11ea-996f-78dfeac883d0.png)

**Steps to Reproduce:**  
IN Main Menu -> [05] Credits -> [12] Schedule 6/G -> [05] CC-40 College Credit -> Click the  '...' on [01] - [03]

**Data Location:**

**Comment by MTNielson** [comment]
Missing the INColleg.db3 file.  Will be in next patch
