### ISSUE TITLE
Wintax - NE - Schedule 1 not included in print when Taxable SS is included

### ISSUE THREAD

**Issue by MHGray** [TaxwareSupport/Issue-Reports#681]
**Client Name:**  
Myran

**Client ID:**  
10203

**Description:**  
When only an amount for SS adjustment is put in, the schedule 1 doesn't print. 
![image](https://user-images.githubusercontent.com/8196735/72837946-3e5dd180-3c44-11ea-8ad1-3b2369c21f8c.png)
Also, after changing things on the schedule 1, the total on the previous screen doesn't change until you leave and return.

Original:
![image](https://user-images.githubusercontent.com/8196735/72838134-9399e300-3c44-11ea-81d7-2a2412e02094.png)
Adding Amount:
![image](https://user-images.githubusercontent.com/8196735/72838149-9d234b00-3c44-11ea-9abe-a99c96aac1cb.png)
Total is wrong:
![image](https://user-images.githubusercontent.com/8196735/72838162-a14f6880-3c44-11ea-8cff-c8651bb34bae.png)
Leave and return:
![image](https://user-images.githubusercontent.com/8196735/72838177-a9a7a380-3c44-11ea-9812-c15a0cc47a8f.png)

**Steps to Reproduce:**  
Use Data Provided -> Preview return -> Locate NE Schedule 1 (you can't)

**Data Location:**
R:\Matt\NESch1SS

**Comment by MTNielson** [comment]
Fixed refreshing the dollar amounts on Credits and Schedule 1 lines.
Fixed the adding of Schedule 1 being a form that should print.
Note: efile still included the Schedule 1.  It was using the correct test to include form.
Will be in next patch.
