### ISSUE TITLE
Wintax - 8962 - Repayment limitation tables are out of date

### ISSUE THREAD

**Issue by MHGray** [TaxwareSupport/Issue-Reports#682]
**Client Name:**  
Lily

**Client ID:**  
21535

**Description:**  
![image](https://user-images.githubusercontent.com/8196735/72840336-d8c01400-3c48-11ea-8841-d1c861aa3775.png)
![image](https://user-images.githubusercontent.com/8196735/72840355-e07fb880-3c48-11ea-8f33-679121122170.png)

**Comment by DodgerDave** [comment]
Fixed 1-21.
