### ISSUE TITLE
Wintax- PA- Local Tax Return

### ISSUE THREAD

**Issue by twsal** [TaxwareSupport/Issue-Reports#685]
21645

Terri

When going into Local tax return, nothing carries over from the fed, even when you click on the carry button on line 18

**Steps to Reproduce:**  
![image](https://user-images.githubusercontent.com/44677096/72850929-1cbe1380-3c5f-11ea-8da8-3d4d65e03f3e.png)

**Comment by DodgerDave** [comment]
It carried. It just wasn't calculating PA local tax. Fixed 1-28.
