### ISSUE TITLE
Wintax - PA- Direct Deposit

### ISSUE THREAD

**Issue by twsal** [TaxwareSupport/Issue-Reports#686]
21645

Terri

Under Pennsylvania Direct Deposit, when selecting the account type it will enter checkings or savings on line 3 instead of line 4. 

**Steps to Reproduce:** 
![image](https://user-images.githubusercontent.com/44677096/72851133-abcb2b80-3c5f-11ea-9602-339a90f9cd9a.png)

**Comment by DodgerDave** [comment]
Fixed 1-22
