### ISSUE TITLE
Wintax - W2 - Validity error for SSN matching Basic even with ITIN in Basic

### ISSUE THREAD

**Issue by MHGray** [TaxwareSupport/Issue-Reports#687]
**Client Name:**  
Jose

**Client ID:**  
21416

**Description:**  
Getting Validity Error:
![image](https://user-images.githubusercontent.com/8196735/72852019-27c67300-3c62-11ea-8bc3-d03c355813a5.png)
But spouse has ITIN and is putting in SSN on the W2 which seems to be correct. Not sure Why internal validation is flagging it.

**Steps to Reproduce:**  
Use Data Provided

**Data Location:**
R:\Matt\ITINW2SSN

**Comment by DodgerDave** [comment]
Fixed 1-22.
