### ISSUE TITLE
Wintax - E-File Screen - Print successful translog doesn't seem to work

### ISSUE THREAD

**Issue by MHGray** [TaxwareSupport/Issue-Reports#688]
**Client Name:**  
Gail

**Client ID:**  
21168-1

**Description:**  
Client tries to print the successful translog from the E-File screen on a single client, but only a 0KB file is created which fails to open.

**Steps to Reproduce:**  
Print that translog on a test client

**Comment by MyNameIsDonovan** [comment]
Looks like the reports are missing, will be included in the next patch
