### ISSUE TITLE
Wintax - NJ - Healthcare form not calculating partial coverage of family

### ISSUE THREAD

**Issue by MHGray** [TaxwareSupport/Issue-Reports#691]
**Client Name:**  
Gail

**Client ID:**  
21168-1

**Description:**  
The program is computing Part 2 of Worksheet L (Shared Responsibility Payment Calculation) instead of Part 3. The child has coverage but the taxpayer does not, but the tax is coming out as though both did not have insurance

**Steps to Reproduce:**  
Use Data Provided -> Preview Return

**Data Location:**
R:\Matt\NJHealthCare

**Comment by DodgerDave** [comment]
Fixed 1-23.
