### ISSUE TITLE
Wintax - NY - Carry

### ISSUE THREAD

**Issue by twsal** [TaxwareSupport/Issue-Reports#693]
Michael 

87193

Client is saying on the form IT-213, the amount on line 16, is not carrying over to the return, but carrying over to line 18 which it shouldn't. The client is electing to file married filing separate, but it seems its taking it as a part time or nonresident spouse return. It should stop on line 16, but continues to line 18.

![image](https://user-images.githubusercontent.com/44677096/73091486-63925000-3e8f-11ea-815a-32906b6e49e2.png)

R:\Sal\Michael 87193

**Comment by DodgerDave** [comment]
Fixed 1-24.
