### ISSUE TITLE
Wintax - 1040-SR - Account and Routing are off center

### ISSUE THREAD

**Issue by MHGray** [TaxwareSupport/Issue-Reports#697]
**Client Name:**  
Jim

**Client ID:**  
21317

**Description:**  
![image](https://user-images.githubusercontent.com/8196735/73186051-02a78980-40d4-11ea-88fd-48e4f79d9ed1.png)

**Steps to Reproduce:**  

**Data Location:**

**Comment by DodgerDave** [comment]
Fixed 1-27.
