### ISSUE TITLE
Individual - Form 1116 - Reject looking for attachment

### ISSUE THREAD

**Issue by MHGray** [TaxwareSupport/Issue-Reports#7]
**Client Name:**  
Connie

**Client ID:**  
28020

**Description:**  
![image](https://user-images.githubusercontent.com/8196735/41876438-a70d4922-7882-11e8-8986-ba30da10bbdb.png)
Form 1116 is looking for an attachment but I cannot find any place to attach such a statement.

**Comment by DodgerDave** [comment]
Fixed in Legacy and NG on 7-2-18.
