### ISSUE TITLE
Wintax - CA - 3514 rounding error

### ISSUE THREAD

**Issue by MHGray** [TaxwareSupport/Issue-Reports#701]
**Client Name:**  
Lots

**Client ID:**  
Lots

**Description:**  
![image](https://user-images.githubusercontent.com/8196735/73212919-11a63000-4104-11ea-83d5-35acc20bfb14.png)

**Steps to Reproduce:**  
Use Data

**Data Location:**
R:\Matt\CA3514

**Comment by DodgerDave** [comment]
Fixed 1-27.
