### ISSUE TITLE
1040 - CA 3514 - Not calculating 

### ISSUE THREAD

**Issue by twchrs** [TaxwareSupport/Issue-Reports#704]
**Client Name:**  
Shannon

**Client ID:**  
29023

**Description:**  
Line 26 on form CA 3514 not calculating correctly. 

**Steps to Reproduce:**  
Wintax 2019- Go into california -Payments-Line 8- Preview form 3514
![image](https://user-images.githubusercontent.com/58183787/73219313-b0388e00-4110-11ea-9732-12aedd388aff.png)

**Data Location:**
R:\Chris\29023 Shannon

**Comment by DodgerDave** [comment]
Fixed 1-27.
