### ISSUE TITLE
S Corp - Sch K - Section 199A overide is not staying

### ISSUE THREAD

**Issue by TwZach** [TaxwareSupport/Issue-Reports#708]
**Client Name:**  

**Client ID:**  

**Description:**  
The 199a override in the scorp Sch K disappears once you exit the sch k. 

**Steps to Reproduce:**  
open client -> open sch k -> line 97 input amount -> exit sch k -> open sch k

**Data Location:**

**Comment by MHGray** [comment]
Reported again by Peggy - ID:94031

**Comment by MHGray** [comment]
fixed 01/29
