### ISSUE TITLE
Wintax - PA- Schema

### ISSUE THREAD

**Issue by twsal** [TaxwareSupport/Issue-Reports#709]
Terri 

21645

when trying to run the state schema for pennsylvania 

**Steps to Reproduce:**  
![image](https://user-images.githubusercontent.com/44677096/73290572-871d0980-41b3-11ea-9da6-977e8158672d.png)

R:\Sal\terri 21645

**Comment by DodgerDave** [comment]
Fixed 1-28. User will need to go into PA Form W-2S, section II and reenter the type.
