### ISSUE TITLE
2018 s-corp CA return prints out as 2017

### ISSUE THREAD

**Issue by TwZach** [TaxwareSupport/Issue-Reports#71]
**Client Name:**  
derral
**Client ID:**  
21046
**Description:**  
2018 CA s-corp preview shows 2017
**Reproduce:**  
![image](https://user-images.githubusercontent.com/45858181/50936154-5e4c9980-1423-11e9-91a1-194804cf1bf4.png)

**Data Location:**

**Comment by MHGray** [comment]
Fixed 1.03.19
