### ISSUE TITLE
Wintax - PA- Local

### ISSUE THREAD

**Issue by twsal** [TaxwareSupport/Issue-Reports#710]
Terri

21645

Tax liability is not being carried over to the local income tax data input on line 8

**Steps to Reproduce:**  
![image](https://user-images.githubusercontent.com/44677096/73292778-7e2e3700-41b7-11ea-8237-df1e6e93e12c.png)

R:\Sal\terri 21645

**Comment by DodgerDave** [comment]
Tax liability wasn't calculating because tax rate wasn't carrying from format.  Fixed it 1-28
