### ISSUE TITLE
Wintax - UT- State income as Fed

### ISSUE THREAD

**Issue by twsal** [TaxwareSupport/Issue-Reports#711]
Alejandra

21555

Utah is carrying over the federal income as utah taxable income, not carrying over the $8k from the W2

**Steps to Reproduce:**  
![image](https://user-images.githubusercontent.com/44677096/73294088-f990e800-41b9-11ea-839b-fffe6531ff24.png)

R:\Sal\alejandra 2155

**Comment by DodgerDave** [comment]
It's working correctly.  See UT Sch TC-40B.
