### ISSUE TITLE
Fiduciary -CA validity check crashes the program

### ISSUE THREAD

**Issue by TwZach** [TaxwareSupport/Issue-Reports#712]
**Client Name:**  
moe

**Client ID:**  
22025

**Description:**  
when running validity check on CA the program closes

**Steps to Reproduce:**  
open ca -> run validity check

**Data Location:**

**Comment by MyNameIsDonovan** [comment]
can you get me data?

**Comment by MHGray** [comment]
R:\Matt\CAFiducCrash

**Comment by TwZach** [comment]
This Also happens when you try to access CA form print

**Comment by MyNameIsDonovan** [comment]
This might have been fixed... does not crash when I go into validity.
However, I have no idea how long form print for states has been busted for fiduc… but it should be fixed now lol
For next update
