### ISSUE TITLE
Wintax - CA - Schedule CA Part II causing Reject

### ISSUE THREAD

**Issue by MHGray** [TaxwareSupport/Issue-Reports#713]
**Client Name:**  
Lily

**Client ID:**  
21535

**Description:**  
![image](https://user-images.githubusercontent.com/8196735/73303006-788e1c80-41ca-11ea-811d-c081a91fcfd4.png)
![image](https://user-images.githubusercontent.com/8196735/73303028-804dc100-41ca-11ea-9c42-01af081d1bcd.png)

**Steps to Reproduce:**  
Use Data Provided

**Data Location:**
R:\Matt\CASchCAPartII

**Comment by DodgerDave** [comment]
Fixed 1-28.
