### ISSUE TITLE
Wintax - IA - Validation from HoH but no way to clear it

### ISSUE THREAD

**Issue by MHGray** [TaxwareSupport/Issue-Reports#714]
**Client Name:**  
Anita

**Client ID:**  
21410

**Description:**  
![image](https://user-images.githubusercontent.com/8196735/73304123-7e84fd00-41cc-11ea-876c-a15f8f3fc7bc.png)

**Steps to Reproduce:**  
Use Data Provided

**Data Location:**
R:\Matt\IAHoH

**Comment by MyNameIsDonovan** [comment]
I added input for these on the basic info, in next patch
