### ISSUE TITLE
1040 -Car and truck worksheet  - Value showing as negative.

### ISSUE THREAD

**Issue by twchrs** [TaxwareSupport/Issue-Reports#716]
**Client Name:**  
Reyes

**Client ID:**  
21942

**Description:**  
Getting a validation error saying that the value is negative but checking the car and truck worksheet it shows positive.

**Steps to Reproduce:**  
Forms and schedules-Schedule C- Go into schedule C input-Line 37 Car and truck worksheet.

**Data Location:**
R:\Chris\21942 Reyes

**Comment by DodgerDave** [comment]
Must enter total mileage.
