### ISSUE TITLE
2018 Wintax -> 1040 Line Input -> [14] -> Mouse free numbers are increased by +1

### ISSUE THREAD

**Issue by twnathan** [TaxwareSupport/Issue-Reports#72]
**Client Name:**  
ELIZABETH CORTINA

**Client ID:**  
99059

**Description:**  
2018 Wintax -> 1040 Line Input -> [14] -> Mouse free numbers are increased by +1

For example, when you type "57" to access line [57], it accesses [58] instead. It does this for all numbers. In fact, you cannot mouse-free select [57], you must click it to gain access.

**Reproduce:**  
Reproduced on Tech computer:

2018 Wintax -> 1040 Line Input -> [14] -> Mouse free numbers are increased by +1

**Data Location:**
N/A

**Comment by MyNameIsDonovan** [comment]
Fixed in 1.5
