### ISSUE TITLE
Wintax - GA - Net Operating Loss comes over as negative instead of positive

### ISSUE THREAD

**Issue by MHGray** [TaxwareSupport/Issue-Reports#727]
**Client Name:**  
Frank

**Client ID:**  
26012

**Description:**  
NOL from fed is being pulled over to the GA Schedule 1 as a negative number but it should be a positive number since it is an addback
![image](https://user-images.githubusercontent.com/8196735/73554662-018e9900-4401-11ea-80e5-d6c3bdfb3516.png)

**Steps to Reproduce:**  
Use Data provided -> Carry going into GA -> Schedule 1 Line [03] is a negative number

**Data Location:**
R:\Matt\GANOL

**Comment by DodgerDave** [comment]
Fixed 1-31.
