### ISSUE TITLE
1040 -8995A  - Part 3 getting filled out 

### ISSUE THREAD

**Issue by twchrs** [TaxwareSupport/Issue-Reports#728]
**Client Name:** 
Florino
**Client ID:**  
500-86

**Description:**  
On form 8995A Part 3 is getting filled out but they have a taxable income of 489450. Causing line 24 to have a percentage more than 100.
![image](https://user-images.githubusercontent.com/58183787/73564184-e24d3700-4413-11ea-94cf-55a8eff81ac3.png)
![image](https://user-images.githubusercontent.com/58183787/73564212-ec6f3580-4413-11ea-80b3-d2ad52bc92ed.png)

**Steps to Reproduce:**  
Forms and schedules- QBI deduction worksheet and preview.

**Data Location:**
R:\Chris\500-86

**Comment by MyNameIsDonovan** [comment]
Yeah this was a math error and was not limiting the percentage. Fixed for the next update
