### ISSUE TITLE
1040 - 8867 - Due Dilligence question not carrying over to 8867 

### ISSUE THREAD

**Issue by twchrs** [TaxwareSupport/Issue-Reports#730]
**Client Name:**  
Jay

**Client ID:**  
4382

**Description:**  
Question 13 on due dilligence not carrying over to form 8867.
![image](https://user-images.githubusercontent.com/58183787/73583841-3e7e7e00-4449-11ea-9f56-51f32ab8ede4.png)
![image](https://user-images.githubusercontent.com/58183787/73583885-6c63c280-4449-11ea-8ac3-892858f4f972.png)

**Steps to Reproduce:** 
Go to forms and schedules  then line 94 check line 13. Go back into forms and schedules form 8867 and preview.

**Data Location:**
R:\Chris\4382 Jay

**Comment by MHGray** [comment]
Not Fixed. Data in same location, tax client 1.

**Comment by MHGray** [comment]
fixed
