### ISSUE TITLE
Partnership - E-File - Partnership errors or crashes on get ACKS

### ISSUE THREAD

**Issue by MHGray** [TaxwareSupport/Issue-Reports#731]
**Client Name:**  
Mo

**Client ID:**  
22025

**Description:**  
If you press get acks from the clients return -> E-file the program crashes with no error logs.
If you press get acks from the efile status screen, you get the following error: 
![Annotation 2020-02-03 105934](https://user-images.githubusercontent.com/8196735/73682114-8d5c2b80-4674-11ea-8073-9362e8262a1a.png)

If you print the 8879 it doesn't change the state status to transmit.
If you try to validate a CA568 without the CA XSD files downloaded you get an error. Workaround for this issue is known.

**Steps to Reproduce:**  
Use Data Provided

**Data Location:**
R:\Matt\PTNRCrashOnGetAcks

**Comment by MyNameIsDonovan** [comment]
Ok I fixed the CAMEFELFLOGS thing in all the entities
I also fixed the 568 Schema Issue
