### ISSUE TITLE
Wintax - Password PDF Checkbox should be moved to print

### ISSUE THREAD

**Issue by MHGray** [TaxwareSupport/Issue-Reports#732]
**Client Name:**  
Maria

**Client ID:**  
21635

**Description:**  
The PDF Password protect checkboxes are in the Misc Features but they really should be in the print setup, that way clients can create print profiles specifically for archiving with password and be able to switch between the two on the summary menu. As it is, if the client wants to do one return password protected than one non-password protected they would:
1. Go into Misc features
2. Check the Box
3. Go back to recall clients
4. select their client
5. go to the summary menu
6. archive the return
7. leave the client
8. go to Misc features and uncheck the box
9. go into their next return...

If they want to switch frequently, this is a huge pain.

**Comment by twJorge** [comment]
Moved only checkbox to print setup.
