### ISSUE TITLE
Corp - CA- Schema error

### ISSUE THREAD

**Issue by twsal** [TaxwareSupport/Issue-Reports#736]
peggy

94031

When running the state schema, it comes out with this error "empty path name is not legal". I've tried to redownload the schema, and redownload the patch for the program, and still no luck. I tried it on my side, and get the same error.

**Steps to Reproduce:**  
![c corp](https://user-images.githubusercontent.com/44677096/73698788-f2c11400-4696-11ea-87ba-e4fd2f7185e7.PNG)

R:\Sal\peggy 94031\TX211

**Comment by MyNameIsDonovan** [comment]
i think the issue that caused this has already been fixed
