### ISSUE TITLE
Wintax - Print Setup - Misc Schedules print even if it is not selected in the print setup

### ISSUE THREAD

**Issue by MHGray** [TaxwareSupport/Issue-Reports#737]
**Client Name:**  
Ed

**Client ID:**  
11073

**Description:**  
If no forms are set to print in print setup, Misc schedules still prints

**Steps to Reproduce:**  
Use Client data provided and Print settings file provided

**Data Location:**
R:\Matt\MiscSchedulePrint

**Comment by DodgerDave** [comment]
Fixed 2-4.
