### ISSUE TITLE
1040 - NJ Bank info - State information not carrying over

### ISSUE THREAD

**Issue by twchrs** [TaxwareSupport/Issue-Reports#738]
**Client Name:**  
Lali

**Client ID:**  
99079

**Description:**  
The deposit information for New jersey is not showing up on the bank information for direct deposit or debit form.

**Steps to Reproduce:**  
Go to form print - Worksheets - Check line 23 Bank information for Direct deposit or debit. State information is missing.

**Data Location:**
X:\Dave\99079

**Comment by DodgerDave** [comment]
Fixed 2-4.
