### ISSUE TITLE
Corp - CA- Payment Amount

### ISSUE THREAD

**Issue by twsal** [TaxwareSupport/Issue-Reports#739]
Peggy

94031

Return keeps getting an validation error asking for an amount paid with extension, with or without the amounts added to the lines

![image](https://user-images.githubusercontent.com/44677096/73703328-5f8edb00-46a4-11ea-9630-57b690ab191f.png)

R:\Sal\peggy 94031\TX58

**Comment by MyNameIsDonovan** [comment]
Fixed
