### ISSUE TITLE
Master Tax Menu - Error When opening a Message

### ISSUE THREAD

**Issue by TWCatherine** [TaxwareSupport/Issue-Reports#74]
![image](https://user-images.githubusercontent.com/44300732/51053048-632d5c80-158d-11e9-87d4-363ba0565886.png)

Master Tax Menu, selected the most recent message and opened it to read. Went to close it and got this error.  Could not close the error without "End Task" option to close out the whole menu.

**Comment by TWCatherine** [comment]
When you go back in and do the same thing there are no errors. So only on the first time it seems.

**Comment by MHGray** [comment]
Seems to be fixed
