### ISSUE TITLE
Wintax- QBI- reject

### ISSUE THREAD

**Issue by twsal** [TaxwareSupport/Issue-Reports#740]
Sam 

99081-1

Client is getting this error for this return, they dont have any business k1s, but they do have 199a dividends.

![Capture](https://user-images.githubusercontent.com/44677096/73704534-3b34fd80-46a8-11ea-8d34-5c67210f1d53.PNG)

R:\Sal\sam 99081-1

**Comment by MyNameIsDonovan** [comment]
This should be fixed in the next update. It looks like they do qualify for QBI, but it wasn't being included because there were no qualifying "items"
