### ISSUE TITLE
W2 mouse free does not work properly 

### ISSUE THREAD

**Issue by TwZach** [TaxwareSupport/Issue-Reports#75]
**Client Name:**  

**Client ID:**  

**Description:**  
Cannot shift tab back from Medicare wages and tips inside of W2.
**Reproduce:**  

**Data Location:**

**Comment by MHGray** [comment]
From mouse free you also can't get into line [13] Social Security Wages at all (with the autocalculate default on at least) Assuming the autocalc or the W2 had incorrect numbers there it would be frustrating for a mouse free only user.
