### ISSUE TITLE
Wintax - MA sch sc is not generating in the xml causing a reject

### ISSUE THREAD

**Issue by TwZach** [TaxwareSupport/Issue-Reports#753]
**Client Name:**  
missy

**Client ID:**  
2450

**Description:**  
The clients return gets rejected for not having the sch sc, but the cms does show in the xml. what is the trigger to get it to show. client believes it is filled out.
![image](https://user-images.githubusercontent.com/45858181/73861025-53646400-47f1-11ea-94d0-350af820cf8b.png)
**Steps to Reproduce:**  
open client data -> MA -> credits -> sch sc

**Data Location:**
R:\Zac\client data\1040nextgen\2450cltdta

**Comment by DodgerDave** [comment]
Fixed 2-5.
