### ISSUE TITLE
19Wintax - 8995-A - Reject saying there's multiple 8995-A

### ISSUE THREAD

**Issue by twchrs** [TaxwareSupport/Issue-Reports#760]
**Client Name:**  
Joe

**Client ID:**  
9913

**Description:**  
Reject stating that there is two form 8995-A on the return but there is only 1.

**Steps to Reproduce:**  
I have included the xml and reject for the return.

**Data Location:**
X:\Dave\9913 Joe

**Comment by MyNameIsDonovan** [comment]
should be fixed in the next update
