### ISSUE TITLE
Wintax - MFJ/MFS Compare - Form 2441 gets removed from current return when comparing

### ISSUE THREAD

**Issue by MHGray** [TaxwareSupport/Issue-Reports#761]
**Client Name:**  
Donna

**Client ID:**  
6350

**Description:**  
When using the MFJ/MFS Compare tool, if the current client has a 2441 the comparison tool removes it. Then if they click no, they don't want to do the separation, it does not put that info back in.

**Steps to Reproduce:**  
Use Data Provided -> See there is a 2441 -> Do MFJ compare and click no on all pop-ups -> See the 2441 has been removed

**Data Location:**
R:\Matt\MFJCompare2441

**Comment by DodgerDave** [comment]
Fixed 2-6.
