### ISSUE TITLE
Entities - Most entity programs are not updating the client.db3 database correctly

### ISSUE THREAD

**Issue by MHGray** [TaxwareSupport/Issue-Reports#762]
**Client Name:**  
Bay

**Client ID:**  
2690-1

**Description:**  
Things like balance due, refund amt, State Balance Due, State Refund Amt and others in the client.db3 database are not being updated correctly from the return. This causes an issue on the default letters and slips sheets where that information is not displayed.

**Comment by twsal** [comment]
When running a reconstruct, it will bring up the numbers, but as you leave the page and go back into it, the numbers are gone again

**Comment by MyNameIsDonovan** [comment]
This should be fixed in the current update
