### ISSUE TITLE
Wintax - American opportunity credit is not showing 

### ISSUE THREAD

**Issue by TwZach** [TaxwareSupport/Issue-Reports#767]
**Client Name:**  
john

**Client ID:**  
21620

**Description:**  
The american opportunity credit is not showing up for the client though everything appears to be filled out correctly

**Steps to Reproduce:**  
Open client data -> 

**Data Location:**
R:\Zac\client data\1040nextgen\21620cltdta

**Comment by DodgerDave** [comment]
Works correctly.
