### ISSUE TITLE
Wintax - CA - If print option Mask SSNs is checked, SSN on 8453 should not be masked

### ISSUE THREAD

**Issue by MHGray** [TaxwareSupport/Issue-Reports#768]
**Client Name:**  
Message Boards

**Client ID:**  
Message Boards

**Description:**  
![image](https://user-images.githubusercontent.com/8196735/74039537-de229b80-4976-11ea-8480-6ba9de9763f3.png)

**Comment by DodgerDave** [comment]
Fixed 2-7.
