### ISSUE TITLE
Wintax - CA - Incorrect Withdrawal Dates and Typo

### ISSUE THREAD

**Issue by MHGray** [TaxwareSupport/Issue-Reports#769]
**Client Name:**  
Ticket 24217

**Client ID:**  
Ticket 24217

**Description:**  
Withdrawal dates on CA direct debit are showing last years date, Also Withdrawal on line [20] is misspelled.
![image](https://user-images.githubusercontent.com/8196735/74041384-67879d00-497a-11ea-86cc-ad75f4ef3d47.png)

**Steps to Reproduce:**  
CA -> Direct Debt

**Comment by DodgerDave** [comment]
Fixed 2-7.
