### ISSUE TITLE
Wintax - NY- Disabled box not checking

### ISSUE THREAD

**Issue by twsal** [TaxwareSupport/Issue-Reports#770]
Pete

7850

On the form IT-216 for claim for child and dependent care credit, the person with disability box, is not checking, on the form nor on the program xml, causing a reject, for this return.

![Capture](https://user-images.githubusercontent.com/44677096/74047930-01087c00-4986-11ea-81a1-79be96ae292e.PNG)

R:\Sal\pete 7850

**Comment by DodgerDave** [comment]
Fixed carry from Fed.  You could always manually check the box and it would show on print and XML.
