### ISSUE TITLE
Corp - CA - Transmitting causes error, unsure cause

### ISSUE THREAD

**Issue by MHGray** [TaxwareSupport/Issue-Reports#771]
**Client Name:**  
Mark

**Client ID:**  
99005

**Description:**  
On this particular return, trying to transmit the CA return won't go through even though validation clears. Gives Error ~ "Cannot create request" something like that.

**Data Location:**
R:\Matt\CACorpEFileTransmit

**Comment by MyNameIsDonovan** [comment]
fixed
