### ISSUE TITLE
Wintax - Return keeps setting status to Qualifying Widower when it should be single

### ISSUE THREAD

**Issue by MHGray** [TaxwareSupport/Issue-Reports#772]
**Client Name:**  
Fely

**Client ID:**  
20003

**Description:**  
Client has return that keeps reverting status to Qualifying Widower when it should be single. Might be tied to 1040NR cause it is happening on several 1040NR returns. Tried setting it to single but as soon as you go through to the summary menu it switches back to qualifying widower.

**Steps to Reproduce:**  
Use Data Provided -> Change Status to Single -> Click [03] Summary Menu -> Click [40] Basic Information -> Status is back to qualifying widower.

**Data Location:**
R:\Matt\1040NRQualifyingWidower

**Comment by DodgerDave** [comment]
Fixed 2-7.
