### ISSUE TITLE
Wintax - 8962 line 4 poverty line is not calculating correctly

### ISSUE THREAD

**Issue by TwZach** [TaxwareSupport/Issue-Reports#775]
**Client Name:**  
Shirley

**Client ID:**  
21167

**Description:**  
For the 8962 line 4 the calculation for the poverty line of a family size greater than 8 is not calculating correctly. it supposed to be 4320*additional members above 8.
![image](https://user-images.githubusercontent.com/45858181/74055740-70d23300-4995-11ea-912e-70abf56e69e6.png)
![image](https://user-images.githubusercontent.com/45858181/74055870-b3940b00-4995-11ea-9dec-cedf29b4dbac.png)

**Steps to Reproduce:**  
open client data -> 8962 -> preview -> line 4
8962 instructions page 6
**Data Location:**
https://www.irs.gov/pub/irs-pdf/i8962.pdf
R:\Zac\client data\1040nextgen\21176cltdta

**Comment by DodgerDave** [comment]
On 2-7 fixed it plus fixed for Alaska and Hawaii
