### ISSUE TITLE
Wintax - 8995 - Phase in reduction being calculated and causing a validation error

### ISSUE THREAD

**Issue by MHGray** [TaxwareSupport/Issue-Reports#778]
**Client Name:**  
Matthew

**Client ID:**  
87125-1

**Description:**  
QBI calculation is causing a validation error on this return. I think it is to do with the Schedule F and the DPAD portion, but it is calculating the phase in reduction when it shouldn't be.

**Steps to Reproduce:**  
Use Data Provided -> Try to clear Validity errors

**Data Location:**
R:\Matt\8995APhaseInForLowIncome

**Comment by MyNameIsDonovan** [comment]
This should be fixed in next update. Will need to go into return to call calc
