### ISSUE TITLE
Scorp - New York -> when preview return program shuts down, due to form 579ct

### ISSUE THREAD

**Issue by TwZach** [TaxwareSupport/Issue-Reports#779]
**Client Name:**  
Waqar

**Client ID:**  
213102

**Description:**  
When trying to print an scorp return with NY the program just shuts down, previewing individual forms all work except for the 579ct which is what is causing the program to crash.

**Steps to Reproduce:**  
open client -> add NY return -> print -> preview return -> state forms -> NY 579CT 
**Data Location:**

**Comment by twJorge** [comment]
Fixed.
