### ISSUE TITLE
19Individual - Schedule A - Mortgage insurance premiums not carrying to interest

### ISSUE THREAD

**Issue by twchrs** [TaxwareSupport/Issue-Reports#780]
**Client Name:**  
Shannon

**Client ID:**  
21190

**Description:**  
Mortgage insurance premiums from schedule A not carrying over to interest.

**Steps to Reproduce:**  
Go to forms and schedules- Schedule A- Interest line 46 not carrying to interest amount.
![image](https://user-images.githubusercontent.com/58183787/74076993-0f2fba00-49d1-11ea-9d29-ac61f2f9cf8e.png)

**Data Location:**
X:\Dave\21190 Shannon

**Comment by DodgerDave** [comment]
MIP not allowed because AGI is too high.
