### ISSUE TITLE
Wintax - CA - 3552 checking student or disabled does not work

### ISSUE THREAD

**Issue by TwZach** [TaxwareSupport/Issue-Reports#781]
**Client Name:**  
2690-1

**Client ID:**  
behram

**Description:**  
If you select that a qualifying person is either a full time student or disable. neither of them populate anything on the print out nor do they mark them as checked in the xml. 

**Steps to Reproduce:**  
open client -> CA -> basic info -> 3552 info -> check full-time student or disabled -> preview -> nothing is checked -> check xml both are marked as false

**Data Location:**

**Comment by DodgerDave** [comment]
Form 3532 works correctly after all.
