### ISSUE TITLE
Wintax -> NY -> Validation is not working getting an empty path error

### ISSUE THREAD

**Issue by TwZach** [TaxwareSupport/Issue-Reports#787]
**Client Name:**  
emy

**Client ID:**  
213102

**Description:**  
When trying to validate the NY return an error pops up saying the path can't be empty, seems to not be creating the xml properly.

**Steps to Reproduce:**  
open client data -> validate NY

**Data Location:**
R:\Zac\client data\1040nextgen\213102cltdta

**Comment by DodgerDave** [comment]
User needs to fix messed up DOB in Fed EIC and NY EIC (IT-215).  Patch will fix problem on IT-214 where a member of household shows on IT-214 in spot reserved for age 65 or over.
