### ISSUE TITLE
Ccorp - CA - Validation Error

### ISSUE THREAD

**Issue by twsal** [TaxwareSupport/Issue-Reports#788]
Elaine

24010

When entering NOL 3805Q and filling out the form, its giving an issue when validating, saying it's missing the curent year NOL and and NOL deduction. 

![image](https://user-images.githubusercontent.com/44677096/74175248-45945180-4bea-11ea-838c-564d50ac03dc.png)

R:\Sal\elaine 24010

**Comment by MyNameIsDonovan** [comment]
should be fixed
