### ISSUE TITLE
Wintax - 2555 - Validation Error on Foreign Employer Address

### ISSUE THREAD

**Issue by MHGray** [TaxwareSupport/Issue-Reports#79]
**Client Name:**  
Bill

**Client ID:**  
21046

**Description:**  
![image](https://user-images.githubusercontent.com/8196735/51150623-00052980-181c-11e9-9a70-94365261240c.png)
![image](https://user-images.githubusercontent.com/8196735/51150632-0b585500-181c-11e9-9ad4-1835d1e59bcb.png)
![image](https://user-images.githubusercontent.com/8196735/51150638-1c08cb00-181c-11e9-9404-5344fbe03a67.png)

**Reproduce:**  
Use Data Provided

**Data Location:**
R;/Matt/2555ForeignAddress

**Comment by MyNameIsDonovan** [comment]
fixed, will have to reinput stuff
