### ISSUE TITLE
Wintax - VA - VA K1 info with no withholding causes validation error

### ISSUE THREAD

**Issue by MHGray** [TaxwareSupport/Issue-Reports#791]
**Client Name:**  
Latoya

**Client ID:**  
21573-8

**Description:**  
![image](https://user-images.githubusercontent.com/8196735/74189146-bba5b200-4c04-11ea-9722-ba83fc379191.png)

**Steps to Reproduce:**  
Use Data Provided

**Data Location:**
R:\Matt\VAVK1Witholding

**Comment by DodgerDave** [comment]
VA withholding is a mandatory field in the VA K1.  Delete the VA K1.  VA doesn't want to see it if there is no VA w/h.
