### ISSUE TITLE
Wintax - CA - 3596 due diligence boxes aren't being checked

### ISSUE THREAD

**Issue by TwZach** [TaxwareSupport/Issue-Reports#796]
**Client Name:**  
Behran

**Client ID:**  
2690-1

**Description:**  
The 3596 is not checking all the due diligence lines from the fed. line 9a for EIC specifically is not checked
![image](https://user-images.githubusercontent.com/45858181/74268716-2e726400-4cbd-11ea-9e30-f2785276abd2.png)
![image](https://user-images.githubusercontent.com/45858181/74268814-5b267b80-4cbd-11ea-86ad-dffdc11411cd.png)
**Steps to Reproduce:**  
open client data -> form print -> ca -> 3596 -> foms and schedules -> due dilignce

**Data Location:**
R:\Zac\client data\1040nextgen\2690-1cltdta

**Comment by DodgerDave** [comment]
Fixed 2-11.
