### ISSUE TITLE
2019 Wintax - AZ - Reject for Qualifying Charitable Deductions

### ISSUE THREAD

**Issue by twgenie** [TaxwareSupport/Issue-Reports#797]
**Client Name:**  
Alicia

**Client ID:**  
21734

**Description:**  
AZ is rejecting Qualifying Charitable deductions because calc is off. Screenshot of form below and reject is attached.

![image](https://user-images.githubusercontent.com/46978780/74278657-6b932200-4cce-11ea-8788-0e1cb1c5ce3b.png)

**Data Location:**
R:\Genie\Client Data\21734

**Comment by DodgerDave** [comment]
Fixed 2-11.
