### ISSUE TITLE
Wintax - MA - Reject on Schedule B

### ISSUE THREAD

**Issue by twsal** [TaxwareSupport/Issue-Reports#799]
Nicole

94031

The interest and dividends amounts are coming out equal from Schedule B, but continue to reject 
![Capture](https://user-images.githubusercontent.com/44677096/74285598-13165180-4cdb-11ea-9849-2e5b16925cf0.PNG)

R:\Sal\nicole 94031

**Comment by DodgerDave** [comment]
Fixed 2-11.
