### ISSUE TITLE
Individual - Legacy - Tax Planning pulls in complete and locked as complete and locked.

### ISSUE THREAD

**Issue by MHGray** [TaxwareSupport/Issue-Reports#8]
**Client Name:**  
Keith

**Client ID:**  
9993

**Description:**  
When pulling in an existing client as a tax planning client, if there return is set to complete and locked, then it is pulled over as complete and locked. This means you can't edit any of the planning numbers and breaks certain calculations.

**Reproduce:**  
Create a return with $40,000 for state taxes in the Schedule A -> Set return to complete and locked -> Carry to tax planning -> It will pull in the $40k to schedule A which would normally be pushed down to the $10k limit, but because it is complete and locked will not update.

**Comment by DodgerDave** [comment]
Fixed on 6-29-18
