### ISSUE TITLE
wintax - Billing adjustments are printing twice

### ISSUE THREAD

**Issue by TwZach** [TaxwareSupport/Issue-Reports#800]
**Client Name:**  
ruby

**Client ID:**  
25006

**Description:**  
If you put an adjustment in to billing defaults, then preview a return the default is shown twice.

**Steps to Reproduce:**  
enter billing adjustment -> create return -> billing -> preview

**Data Location:**

**Comment by MyNameIsDonovan** [comment]
Fixed
