### ISSUE TITLE
19Individual - CA - 3506

### ISSUE THREAD

**Issue by twchrs** [TaxwareSupport/Issue-Reports#801]
**Client Name:**  
Greg

**Client ID:**  
6830

**Description:**  
California form 3506 line 28 issue

**Steps to Reproduce:**  
Go to State of california credits and form 3506 then preview line 28 might not be populating correctly.

**Data Location:**
R:\DAVE\6830 Greg

**Comment by DodgerDave** [comment]
They aren't eligible for child care credit because federal AGI is more then $100,000.  Form 3506 won't be part of the return.
