### ISSUE TITLE
Fiduciary - CA - Cannot create XML on CA validation

### ISSUE THREAD

**Issue by MHGray** [TaxwareSupport/Issue-Reports#803]
**Client Name:**  
Mo

**Client ID:**  
22025

**Description:**  
![image](https://user-images.githubusercontent.com/8196735/74461812-fba6a800-4e43-11ea-9579-7e19d6bbb7b7.png)

**Steps to Reproduce:**  
Validate CA on data provided

**Data Location:**
R:\Matt\CAFiducXMLError

**Comment by MyNameIsDonovan** [comment]
I cant reproduce this
