### ISSUE TITLE
19Individual - Virginia  - Validation error

### ISSUE THREAD

**Issue by twchrs** [TaxwareSupport/Issue-Reports#812]
**Client Name:**  
Sussane

**Client ID:**  
10593

**Description:**  
Virginia not allowing to have federal witholding.
![image](https://user-images.githubusercontent.com/58183787/74485932-b77dcc80-4e70-11ea-9e22-dd6092d4d773.png)
![image](https://user-images.githubusercontent.com/58183787/74485958-c49abb80-4e70-11ea-92ea-a99d4f2a4919.png)

**Steps to Reproduce:**  
Go to forms and schedules line 84, then line 5, go into 1099G.

**Data Location:**
X:\Dave\10593 Susanne

**Comment by DodgerDave** [comment]
Fixed 2-13.
