### ISSUE TITLE
Wintax - VA - Amount due on Summary screen doesn't match return

### ISSUE THREAD

**Issue by MHGray** [TaxwareSupport/Issue-Reports#815]
**Client Name:**  
Maria

**Client ID:**  
7510-1

**Description:**  
Virginia amount due on the summary menu (and client letters) isn't matching the virginia amount due on the return or in the state section. I think it might be related to the Use Tax on VA, but I'm not 100% on what is causing it
![image](https://user-images.githubusercontent.com/8196735/74551363-e6934d00-4f07-11ea-9883-268f541f3952.png)
![image](https://user-images.githubusercontent.com/8196735/74551396-f14de200-4f07-11ea-94a4-61752bd49afa.png)

**Steps to Reproduce:**  
Use Data Provided

**Data Location:**
R:\Matt\VAUseTax

**Comment by DodgerDave** [comment]
Fixed 2-14.
