### ISSUE TITLE
SCorp - CA - Validation Error

### ISSUE THREAD

**Issue by twsal** [TaxwareSupport/Issue-Reports#816]
Ana

21905

The return is running into a validation error, not accepting (none) as an option for California ID number not applicable input, even with a valid CA ID.

![image](https://user-images.githubusercontent.com/44677096/74560571-b2298c00-4f1b-11ea-96da-8aec5bbd57c6.png)
![image](https://user-images.githubusercontent.com/44677096/74562156-0bdf8580-4f1f-11ea-86c7-9730dae2a6a9.png)

R:\Sal\ana

**Comment by MyNameIsDonovan** [comment]
added an option to remove their answer in next update
