### ISSUE TITLE
2019 C Corp- California - Validation Error

### ISSUE THREAD

**Issue by twgenie** [TaxwareSupport/Issue-Reports#817]
**Client Name:**  
Nam

**Client ID:**  
23024

**Description:**  
Client is getting a validation error for payments. Looks like there is a missing "/" in the element RefundOrAmountDue.

![image](https://user-images.githubusercontent.com/46978780/74566523-7ea12e80-4f28-11ea-8505-2383edb648ed.png)
![image](https://user-images.githubusercontent.com/46978780/74566543-911b6800-4f28-11ea-9aa3-4e7f331aa1d6.png)

**Data Location:**
R:\Genie\Client Data\23024

**Comment by MyNameIsDonovan** [comment]
fixed
