### ISSUE TITLE
19Individual - 1040-NR - Date print error

### ISSUE THREAD

**Issue by twchrs** [TaxwareSupport/Issue-Reports#819]
**Client Name:**  
Veronica 

**Client ID:**  
21673

**Description:**  
On 1040NR date is not printing correctly.

**Steps to Reproduce:**  
Go to summary- preview return -scroll down to page 12
![image](https://user-images.githubusercontent.com/58183787/74579241-0ea59f00-4f4e-11ea-924a-776e623b4de7.png)

**Data Location:**
X:\Dave\21673 Veronica

**Comment by DodgerDave** [comment]
Fixed 2-18.
