### ISSUE TITLE
1041 - FED - Xml Reject

### ISSUE THREAD

**Issue by twsal** [TaxwareSupport/Issue-Reports#820]
Bill

21046

When transmitting the fed return for 1041, they are getting this reject 

![image](https://user-images.githubusercontent.com/44677096/74593721-25e29c00-4fe3-11ea-8009-0fa8ac5dcd4a.png)

R:\Sal\bill 21046\tx201

**Comment by MyNameIsDonovan** [comment]
Figured it out, issue with sending fed and CA at the same time. fixed in an update
