### ISSUE TITLE
Wintax - QBI- Not able to overwrite

### ISSUE THREAD

**Issue by twsal** [TaxwareSupport/Issue-Reports#824]
John

87125-1

Client is getting a negative carry from prior year, they it shouldn't be there. When trying to overwrite the amount it will recalculate with the same number, but under the overwrite color.

**Steps to Reproduce:**  
![image](https://user-images.githubusercontent.com/44677096/74695129-b073f880-51a7-11ea-8a90-8b43fadfcce6.png)

![image](https://user-images.githubusercontent.com/44677096/74695140-b8cc3380-51a7-11ea-9d18-5213da808684.png)

R:\Sal\john 87125-1\Qbi not able to overwrite, on the deduction input

**Comment by MyNameIsDonovan** [comment]
fixed, overwrite was not working correctly
