### ISSUE TITLE
Wintax - QBI- DPAD negative carry

### ISSUE THREAD

**Issue by twsal** [TaxwareSupport/Issue-Reports#825]
John

87125-1

Keeps getting rejected every time there is a negative amount on line 38, under the QBI preview form.

![image](https://user-images.githubusercontent.com/44677096/74695443-de0d7180-51a8-11ea-9393-b03a4c42854b.png)

R:\Sal\john 87125-1\Keeps getting rejected when line line 38, has a negitive number

**Comment by MyNameIsDonovan** [comment]
changed the calc to 0 out 39 if negative. Hopefully that fixes it
