### ISSUE TITLE
19Individual - Pennsylvania - State direct deposit not carrying over to return

### ISSUE THREAD

**Issue by twchrs** [TaxwareSupport/Issue-Reports#827]
**Client Name:**  
Toai

**Client ID:**  

21622
**Description:**  
Pennsylvania direct deposit not carrying over to direct deposit or direct debit info on complete return.

**Steps to Reproduce:**  
Go to summary then preview return and scroll down to page 38 Pennsylvania direct deposit not carrying over.

**Data Location:**
R:\Chris\21622

**Comment by DodgerDave** [comment]
Fixed 2-20.

**Comment by DodgerDave** [comment]
User will need to go into PA direct debit to get it to work.
