### ISSUE TITLE
19Individual - California  - California 3532 not getting attached 

### ISSUE THREAD

**Issue by twchrs** [TaxwareSupport/Issue-Reports#828]
**Client Name:**  
Connie 

**Client ID:**  
99068

**Description:**  
When filling the california return it seems that the California form 3532 is not getting attached.

**Steps to Reproduce:**  
XML and reject are in the data folder 

**Data Location:**
R:\Chris\99068

**Comment by DodgerDave** [comment]
User needs to input the relationship of the qualifying person in the 3532.  Once that is done the 3532 will be included in the XML.
