### ISSUE TITLE
Partnership - NY-579-CT - Trying to print NY-579-CT causes program to crash

### ISSUE THREAD

**Issue by MHGray** [TaxwareSupport/Issue-Reports#829]
**Client Name:**  
Joe

**Client ID:**  
7850

**Description:**  
Trying to print the NY-579-CT (E-File Signature Page) causes partnership to crash.

**Steps to Reproduce:**  
Preview return with NY-579-CT or the form specifically

**Comment by twJorge** [comment]
Fixed.
