### ISSUE TITLE
Wintax - DE - Federal itemized deductions do not carry to DE Schedule A

### ISSUE THREAD

**Issue by MHGray** [TaxwareSupport/Issue-Reports#832]
**Client Name:**  
Brenda

**Client ID:**  
87133

**Description:**  
![image](https://user-images.githubusercontent.com/8196735/74948356-11225180-53b1-11ea-9088-d5d53d5c9365.png)
![image](https://user-images.githubusercontent.com/8196735/74948378-1aabb980-53b1-11ea-8959-2bc0cb6c1b3f.png)

**Steps to Reproduce:**  
Go into DE Schedule A -> None of the amounts from the federal Sch A are here

**Data Location:**
R:\Matt\DelawareSchA

**Comment by MyNameIsDonovan** [comment]
fixed
