### ISSUE TITLE
Wintax - QBI - 8995 form 

### ISSUE THREAD

**Issue by MHGray** [TaxwareSupport/Issue-Reports#833]
**Client Name:**  
Message Boards

**Client ID:**  
Message Boards

**Description:**  
8995 doesn't print if only 199a dividends are input. Efile is okay.

**Steps to Reproduce:**  
Go to Schedule B -> Input 199A Dividends -> Preview Return -> No 8995 included

**Comment by MyNameIsDonovan** [comment]
fixed
