### ISSUE TITLE
wintax - SCH J - tax rates for line 8 and 12 don't seem to be correct

### ISSUE THREAD

**Issue by TwZach** [TaxwareSupport/Issue-Reports#834]
**Client Name:**  
John

**Client ID:**  
87125-1

**Description:**  
The tax based of the 2016 and 2017 rates seem to be not working correctly, while the input has 2018 inputs the tax is zero and when we take it off it shows a tax of $31. The tax rates in the instructions seems to show a 33% tax
![image](https://user-images.githubusercontent.com/45858181/74956547-213f2e80-53bb-11ea-8544-7e81ad02c09a.png)
![image](https://user-images.githubusercontent.com/45858181/74956459-fb198e80-53ba-11ea-8823-251be4d776ab.png)
**Steps to Reproduce:**  
open client data -> Sch J -> Preview

**Data Location:**
https://www.irs.gov/pub/irs-pdf/i1040sj.pdf
R:\Zac\client data\1040nextgen\87125-1cltdta

**Comment by DodgerDave** [comment]
Fixed 2-21.
