### ISSUE TITLE
Wintax - WI - County Validation Error

### ISSUE THREAD

**Issue by twsal** [TaxwareSupport/Issue-Reports#838]
Steve

9913

When running a validation check on the state, it keeps flagging the county and the school code for this return. When trying to access the code box, WICounty.db3 does not exist comes out as well as the school district code

![image](https://user-images.githubusercontent.com/44677096/74979979-85c2b380-53e4-11ea-93c1-5df1433ecd4f.png)

![image](https://user-images.githubusercontent.com/44677096/74982400-e6ec8600-53e8-11ea-926b-dade045ed4dd.png)

R:\Sal\Steve 9913

**Comment by DodgerDave** [comment]
Fixed 2-21.
