### ISSUE TITLE
Client is getting an error when recalling prior, and sch E can't recall prior

### ISSUE THREAD

**Issue by TwZach** [TaxwareSupport/Issue-Reports#84]
**Client Name:**  
Eric
**Client ID:**  
96054
**Description:**  
When recalling the client from a prior year there is a cannot read beyond end of stream error. The error comes up a number of times, and when in the return the sch e cannot recall the prior year.
**Reproduce:**  

**Data Location:**
R:\Zac\2017clientdata\96054clientdata

**Comment by MyNameIsDonovan** [comment]
Fixed in the next patch
