### ISSUE TITLE
19Individual - Utah - Calculation error

### ISSUE THREAD

**Issue by twchrs** [TaxwareSupport/Issue-Reports#841]
**Client Name:**  
21344

**Client ID:**  
Lonnie 

**Description:**  
On Utah return line 6 is not calculating correctly.

**Steps to Reproduce:**  
Go into UT then preview return Line 6 not adding line 4 and 5.
![image](https://user-images.githubusercontent.com/58183787/74993875-435b9f80-5401-11ea-9303-fc5f44e9ae24.png)

**Data Location:**
R:\Chris\21344 Lonnie

**Comment by DodgerDave** [comment]
When you make any changes to the federal return you must go into the UT return so it can recalculate. This will fix it.
