### ISSUE TITLE
19Individual - CA - Calculation error

### ISSUE THREAD

**Issue by twchrs** [TaxwareSupport/Issue-Reports#843]
**Client Name:**  
Charles 

**Client ID:**  
20167

**Description:**  
CAMiscellanous deduction amount not calculating correctly.

**Steps to Reproduce:**  
![image](https://user-images.githubusercontent.com/58183787/74996758-4eb2c900-5409-11ea-8979-c17509ab9f5c.png)
Reject inside data

**Data Location:**
R:\Chris\20167 Charles

**Comment by DodgerDave** [comment]
They must have made a change to the federal AGI and they didn't go back into CA so it could recalculate.  I went into CA and it calculated the right amount on line 25.
