### ISSUE TITLE
Wintax - MT - Sch. Refund Calculation Reject

### ISSUE THREAD

**Issue by twsal** [TaxwareSupport/Issue-Reports#844]
Cassy

26009

Client is getting a reject on this return due to the error on calculations for the refund

**Steps to Reproduce:**  
![image](https://user-images.githubusercontent.com/44677096/75053418-18675f00-5486-11ea-84c2-d784002ba695.png)

R:\Sal\cassy 26009

**Comment by twJorge** [comment]
Fixed.
