### ISSUE TITLE
Wintax - AL- Amended box 

### ISSUE THREAD

**Issue by twsal** [TaxwareSupport/Issue-Reports#846]
Cheryl

601-86

Amended Box is not working for Alabama

![image](https://user-images.githubusercontent.com/44677096/75067120-35f5f200-54a1-11ea-9209-d57627805e6b.png)
![image](https://user-images.githubusercontent.com/44677096/75067198-5d4cbf00-54a1-11ea-8a82-1a5142b1ebf8.png)

**Data Location:**

**Comment by twJorge** [comment]
Fixed
