### ISSUE TITLE
2019 Wintax - Louisiana - 2019 Standard Deduction is incorrent

### ISSUE THREAD

**Issue by twgenie** [TaxwareSupport/Issue-Reports#850]
**Client Name:**  
Whittney

**Client ID:**  
213104

**Description:**  
Louisiana is using 24,000 as the standard deduction but it should be 24,400.

Return was accepted and the state sent the client a letter after they adjusted the return.

![image](https://user-images.githubusercontent.com/46978780/75075601-094ad600-54b3-11ea-9ceb-ba476fa5b64c.png)

**Steps to Reproduce:**  

**Data Location:**
R:\Genie\Client Data\213104\Client 2

**Comment by twJorge** [comment]
Fixed.
