### ISSUE TITLE
Wintax - UT - reject for turition deduction not carrying

### ISSUE THREAD

**Issue by TwZach** [TaxwareSupport/Issue-Reports#854]
**Client Name:**  
Craig
**Client ID:**  
21315

**Description:**  
Client is getting a reject that says the TI does not match, due to the Tuition credit not carrying to state.
![image](https://user-images.githubusercontent.com/45858181/75097238-2c31c480-555d-11ea-9e4b-0ff8226de74b.png)

**Steps to Reproduce:**  
open client data -> state -> preview -> page 1 lines 9 and page 3 34B don't match

**Data Location:**
R:\Zac\client data\1040nextgen\21315cltdta

**Comment by DodgerDave** [comment]
Fixed 2-24.
