### ISSUE TITLE
Wintax - CA - Tax from tax table coming up incorrect

### ISSUE THREAD

**Issue by MHGray** [TaxwareSupport/Issue-Reports#855]
**Client Name:**  
Maria

**Client ID:**  
20138

**Description:**  
On this client Tax from Tax Table is off by $1. 
![image](https://user-images.githubusercontent.com/8196735/75182523-7188fa00-56f5-11ea-86b4-391b8e5c9801.png)

![image](https://user-images.githubusercontent.com/8196735/75182451-4acac380-56f5-11ea-952f-a64038888ed4.png)

**Steps to Reproduce:**  
Use Data Provided

**Data Location:**
R:\Matt\CATaxTable

**Comment by DodgerDave** [comment]
Fixed 2-25.
