### ISSUE TITLE
Wintax - MT - 2/3 Farming income

### ISSUE THREAD

**Issue by MHGray** [TaxwareSupport/Issue-Reports#856]
**Client Name:**  
Casey

**Client ID:**  
26009

**Description:**  
This checkbox is checked in print, but it does not force the print of this form and the indicator for t is not showing up in the E-File record. Client is getting letters back from the state saying they owe interest/penalties because this is not being transmitted.
![image](https://user-images.githubusercontent.com/8196735/75188287-bb2b1200-5700-11ea-8e33-95d17dc8fc2f.png)
![image](https://user-images.githubusercontent.com/8196735/75188348-d269ff80-5700-11ea-9504-fa3b2627a5e7.png)

**Steps to Reproduce:**  
See Data to see it isn't showing up in XML

**Data Location:**
R:\Matt\MTFarmerRancher

**Comment by twJorge** [comment]
Fixed
