### ISSUE TITLE
Wintax - VA - Sch A Line 5a carries to line 18 as sales tax 

### ISSUE THREAD

**Issue by TwZach** [TaxwareSupport/Issue-Reports#860]
**Client Name:**  
Message board

**Client ID:**  
message board

**Description:**  
VA Sch A line 5a carries to line 18, client says that it should only carry when income tax not sales tax
Client wants a definitive answer and as the instructions are severely vague, may need to ask VA. 
**Steps to Reproduce:**  

**Data Location:**

**Comment by DodgerDave** [comment]
User is right, I fixed it on 2-26.
