### ISSUE TITLE
Partnership - NY - NY-204-LL not calculating fee correctly

### ISSUE THREAD

**Issue by MHGray** [TaxwareSupport/Issue-Reports#861]
**Client Name:**  
Message Boards

**Client ID:**  
Message Boards

**Description:**  
![image](https://user-images.githubusercontent.com/8196735/75269482-d30c9f80-57ad-11ea-9d27-da5af646dbbb.png)
![image](https://user-images.githubusercontent.com/8196735/75272700-3f3dd200-57b3-11ea-9c75-ef1a176ce387.png)

**Steps to Reproduce:**  
Try to get it to produce a different fee

**Comment by twJorge** [comment]
Fixed. Was not calculating correctly for LLC, LLP was fine.
