### ISSUE TITLE
Wintax - WI - Schedule OS line 33 is not carrying from form 1npr

### ISSUE THREAD

**Issue by TwZach** [TaxwareSupport/Issue-Reports#864]
**Client Name:**  
Joe

**Client ID:**  
9913

**Description:**  
Sch OS line 33 in WI says to carry amounts from these spots. one spot line 46 on form 1NPR has an amount but it does not seem to carry.
![image](https://user-images.githubusercontent.com/45858181/75297215-1bdf4b00-57e4-11ea-9896-0ecfb628f9ef.png)
![image](https://user-images.githubusercontent.com/45858181/75297385-96a86600-57e4-11ea-888d-e791f69f5148.png)

**Steps to Reproduce:**  
open client data -> WI -> Preview -> credits -> line 10 SCH OS -> Preview

**Data Location:**
R:\Zac\client data\1040nextgen\9913cltdta

**Comment by DodgerDave** [comment]
Fixed 2-26.
