### ISSUE TITLE
Wintax - NY - NYC Rate Reduction not calculating

### ISSUE THREAD

**Issue by MHGray** [TaxwareSupport/Issue-Reports#865]
**Client Name:**  
Message Boards

**Client ID:**  
Message Boards

**Description:**  
Line 69a of the IT 201 not calculating even though box C is filled out and they meet other requirements. 
![image](https://user-images.githubusercontent.com/8196735/75457726-ad100800-5931-11ea-9037-ea2bfccdd2ce.png)
![image](https://user-images.githubusercontent.com/8196735/75457784-be591480-5931-11ea-9812-05c00c0b2ff1.png)

**Steps to Reproduce:**  
Use Data Provided

**Data Location:**
R:\Matt\NYRateReduction

**Comment by DodgerDave** [comment]
Fixed 3-3.
