### ISSUE TITLE
John - NJ - Nonresident other income description

### ISSUE THREAD

**Issue by twsal** [TaxwareSupport/Issue-Reports#867]
John

327-86

Under the nonresident data, the other income description input (line 12) is not staying on the return, causing a validation error.

![image](https://user-images.githubusercontent.com/44677096/75475776-37fefb80-594e-11ea-990c-bdfd2d707dce.png)
![image](https://user-images.githubusercontent.com/44677096/75477035-7f868700-5950-11ea-9ff8-15438c23f20c.png)

R:\Sal\John 327-86

**Comment by DodgerDave** [comment]
Fixed 2-27.
