### ISSUE TITLE
Wintax - CA - 3506 validity errors when Qual Expenses get eaten by first dep

### ISSUE THREAD

**Issue by MHGray** [TaxwareSupport/Issue-Reports#869]
**Client Name:**  
Tana

**Client ID:**  
213160

**Description:**  
![image](https://user-images.githubusercontent.com/8196735/75490870-ce8ce600-5969-11ea-8f9b-d664077b2805.png)
![image](https://user-images.githubusercontent.com/8196735/75491406-c97c6680-596a-11ea-93fa-42ecf29e0f66.png)
![image](https://user-images.githubusercontent.com/8196735/75490935-e82e2d80-5969-11ea-9605-7cad2f2d5b59.png)
![image](https://user-images.githubusercontent.com/8196735/75491016-11e75480-596a-11ea-97fe-223139655890.png)

**Steps to Reproduce:**  
Use Data Provided

**Data Location:**
R:\Matt\CA3506MultipleDependentsVE

**Comment by DodgerDave** [comment]
Fixed 3-3.
