### ISSUE TITLE
Wintax - Capital Loss Carryover Worksheet Print - In Print Setup no line for this worksheet

### ISSUE THREAD

**Issue by MHGray** [TaxwareSupport/Issue-Reports#872]
**Client Name:**  
Message Boards -> 1040 -> Fed -> CORTEZ

**Client ID:**  
CORTEZ

**Description:**  
There is no print setup line for the this worksheet. Please add.

![image](https://user-images.githubusercontent.com/8196735/75565609-1f9ce880-5a03-11ea-993b-0bba03e4443c.png)

**Comment by MyNameIsDonovan** [comment]
worksheet is tied to the schedule
