### ISSUE TITLE
Wintax - CO - Nonresident return Validation for missing fed 1040

### ISSUE THREAD

**Issue by MHGray** [TaxwareSupport/Issue-Reports#876]
**Client Name:**  
Jim

**Client ID:**  
88172

**Description:**  
![image](https://user-images.githubusercontent.com/8196735/75691765-5c621d00-5c59-11ea-9d49-45cb04a7ec6e.png)
![image](https://user-images.githubusercontent.com/8196735/75691828-71d74700-5c59-11ea-8d4e-64df8de81427.png)
Looks like the fed forms element is being put in empty when it should either not be put in at all or should be carrying some sort of information over.

**Steps to Reproduce:**  
Use Data Provided

**Data Location:**
R:\Mindy\88172

**Comment by twJorge** [comment]
Fixed.
