### ISSUE TITLE
Wintax - 8801 - Line [13] not carrying from prior year

### ISSUE THREAD

**Issue by MHGray** [TaxwareSupport/Issue-Reports#878]
**Client Name:**  
Brenda

**Client ID:**  
87133

**Description:**  
Line [13] on this input should be carrying from prior year (usually from the same place as line [12]) But it doesn't.
![image](https://user-images.githubusercontent.com/8196735/75789880-3acb6900-5d1f-11ea-8ef5-e604e59bfb5a.png)

**Steps to Reproduce:**  
Use 18 data provided to carry into 19

**Data Location:**
R:\Matt\8801Line13Carryover

**Comment by DodgerDave** [comment]
Done 3-3.
