### ISSUE TITLE
Wintax - W7 - Acceptance Agent's Info should be remembered

### ISSUE THREAD

**Issue by MHGray** [TaxwareSupport/Issue-Reports#88]
**Client Name:**  
Enrique

**Client ID:**  
22722

**Description:**  
In legacy, when entering W7 Acceptance Agent's Info, the program remembers the information entered from w7 to w7. In NextGen this information isn't remembered.
![image](https://user-images.githubusercontent.com/8196735/51352420-5ebbe480-1a62-11e9-9c23-25290b574cb6.png)

**Reproduce:**  
Make W7. Add info on lines [27] -[33].-> Add another W7 -> [27] - [33] is missing.

**Comment by DodgerDave** [comment]
Fixed 3-21
