### ISSUE TITLE
Fiduc- Sch E is carrying to the QBI amount even when the check box in unchecked

### ISSUE THREAD

**Issue by TwZach** [TaxwareSupport/Issue-Reports#881]
**Client Name:**  
Bob

**Client ID:**  
12703

**Description:**  
The sch E amount caries to the SCH K QBI information even when you uncheck the box that asks if it qualifies for QBI

**Steps to Reproduce:**  
Open client -> Sch E -> input income -> line 16 is unchecked -> sch K -> line 61 has that amount

**Data Location:**

**Comment by MyNameIsDonovan** [comment]
fixed
