### ISSUE TITLE
Partnership - CA568 - 568 in the states used line is pointing to the 565 return, not the 568 return

### ISSUE THREAD

**Issue by MHGray** [TaxwareSupport/Issue-Reports#884]
**Client Name:**  
---

**Client ID:**  
---

**Description:**  
Title explains it
![image](https://user-images.githubusercontent.com/8196735/75823651-fe1b6400-5d56-11ea-9806-0693142243d3.png)

**Steps to Reproduce:**  
Have a 568 -> Double click on it from states used list -> Welcome to the 565

**Comment by MyNameIsDonovan** [comment]
fixed for going into and deleting
