### ISSUE TITLE
Wintax - CA - Military Pay field doesn't hold

### ISSUE THREAD

**Issue by MHGray** [TaxwareSupport/Issue-Reports#885]
**Client Name:**  
Lupita

**Client ID:**  
21196

**Description:**  
In the basic information, line [09] Military Pay doesn't hold. You can put it in but as soon as you leave it disappears.

**Steps to Reproduce:**  
Use Data Provided -> Enter amount in CA Basic Info on line [09] Military Pay -> Press Okay and then go back to basic information

**Data Location:**
R:\Matt\CAMilitaryPay

**Comment by DodgerDave** [comment]
Fixed 3-3.
