### ISSUE TITLE
SCorp 2019- Illinois - Validation Error

### ISSUE THREAD

**Issue by twgenie** [TaxwareSupport/Issue-Reports#888]
**Client Name:**  
Dale

**Client ID:**  
21330

**Description:**  
SCrop is still saying that Illinois is a paper file only state. See error below.

![image](https://user-images.githubusercontent.com/46978780/75922990-ff14ca00-5e18-11ea-91e3-16c23496dda1.png)

**Comment by twJorge** [comment]
Fixed.
