### ISSUE TITLE
Wintax - MT - Subtractions aren't calculating correctly

### ISSUE THREAD

**Issue by MHGray** [TaxwareSupport/Issue-Reports#889]
**Client Name:**  
Casey

**Client ID:**  
26009

**Description:**  
![image](https://user-images.githubusercontent.com/8196735/75923655-6717e000-5e1a-11ea-87dc-acc3572adeb0.png)

**Steps to Reproduce:**  
Use data provided -> Preview Subtractions form

**Data Location:**
R:\Matt\MTSSIssue

**Comment by twJorge** [comment]
Fixed.
