### ISSUE TITLE
Wintax - MT - Page 6 for Social Security Adjustments not calculating

### ISSUE THREAD

**Issue by MHGray** [TaxwareSupport/Issue-Reports#890]
**Client Name:**  
Casey

**Client ID:**  
26009

**Description:**  
![image](https://user-images.githubusercontent.com/8196735/75923879-cd046780-5e1a-11ea-9c82-5f4b526a189c.png)
![image](https://user-images.githubusercontent.com/8196735/75923917-e1486480-5e1a-11ea-8637-c883b67bfee1.png)

**Steps to Reproduce:**  
Use Data Provided -> Preview page 6 -> Line 1 isn't filling anything out

**Data Location:**
R:\Matt\MTSSIssue

**Comment by twJorge** [comment]
Fixed.
