### ISSUE TITLE
Partnership 2019 - Illinois - Non-Ordinary Income Validation Error

### ISSUE THREAD

**Issue by twgenie** [TaxwareSupport/Issue-Reports#891]
**Client Name:**  
Dale

**Client ID:**  
21330

**Description:**  
When client has only non-ordinary income the validation error below shows up. 

![image](https://user-images.githubusercontent.com/46978780/75924147-47cd8280-5e1b-11ea-8d0b-34e4e80042fb.png)

**Steps to Reproduce:**  
1. Put in rental income on the federal side.
2. Carry to Illinois.
3. Validate

**Comment by twJorge** [comment]
Fixed.
