### ISSUE TITLE
Wintax - MT - Application of overpayment of estimates causes validation error

### ISSUE THREAD

**Issue by MHGray** [TaxwareSupport/Issue-Reports#892]
**Client Name:**  
Casey

**Client ID:**  
26009

**Description:**  
The following validation occurs when they try to apply refund to estimates for next year
![image](https://user-images.githubusercontent.com/8196735/75924308-8f540e80-5e1b-11ea-9e72-c55869de2e01.png)

**Steps to Reproduce:**  
Use Data Provided

**Data Location:**
R:\Matt\MTEstimatesOverpayment

**Comment by twJorge** [comment]
Fixed.
