### ISSUE TITLE
Wintax - Virginia - 2018 and 2019 have different taxes though returns seem identical

### ISSUE THREAD

**Issue by TwZach** [TaxwareSupport/Issue-Reports#894]
**Client Name:**  
Vaden

**Client ID:**  
10593

**Description:**  
The client has tax in the 2019 year though they have less taxable income than in the prior year. Client says they have never had tax. and that the instructions have not changed this year.

**Steps to Reproduce:**  
open client data -> preview VA return line 15 and 16

**Data Location:**
R:\Zac\client data\1040nextgen\10593cltdta\18
R:\Zac\client data\1040nextgen\10593cltdta\19

**Comment by DodgerDave** [comment]
Virginia AGI is higher than in 2018 and it is no longer below the "no tax" threshold.
