### ISSUE TITLE
Partnership - IL - Reject caused from schedule B not calculating correctly

### ISSUE THREAD

**Issue by MHGray** [TaxwareSupport/Issue-Reports#895]
**Client Name:**  
Dale

**Client ID:**  
21330

**Description:**  
IL Replacement Tax Dectucted addback from Income line [12] doesn't carry to the schedule K line [25] automatically. Even after manually carrying it, it doesn't add into the calculation for the Section B.
![image](https://user-images.githubusercontent.com/8196735/76006460-5c645600-5ec1-11ea-9c4d-af03f63c0f46.png)
![image](https://user-images.githubusercontent.com/8196735/76006650-a9e0c300-5ec1-11ea-9fc0-daf45e223e50.png)
Because of this, this reject is caused
![image](https://user-images.githubusercontent.com/8196735/76006733-c846be80-5ec1-11ea-9c29-6aeace658e7e.png)

**Steps to Reproduce:**  
Use Data Provided

**Data Location:**
R:\Matt\IL1065SectionB

**Comment by twJorge** [comment]
Not an issue. Client removed auto allocate on Sch-K1s. Line [69] in Sch-K can also be manually changed.
