### ISSUE TITLE
Wintax - CA - Schedule X not putting refund amount on XML causing reject

### ISSUE THREAD

**Issue by MHGray** [TaxwareSupport/Issue-Reports#899]
**Client Name:**  
My

**Client ID:**  
29027

**Description:**  
XML missing the refund line causing the following error:
![image](https://user-images.githubusercontent.com/8196735/76131293-c87ab300-5fc2-11ea-98ca-d1e81a7550e9.png)
Seems to be missing this line:
![image](https://user-images.githubusercontent.com/8196735/76131283-be58b480-5fc2-11ea-8b12-d7438345a711.png)

**Steps to Reproduce:**  
Use Data Provided -> Check CA XML

**Data Location:**
R:\Matt\CASchXRefundMissing

**Comment by DodgerDave** [comment]
Fixed 3-9.
