### ISSUE TITLE
NextGen/Depr - Crashes after ~30 minutes in Depr

### ISSUE THREAD

**Issue by MHGray** [TaxwareSupport/Issue-Reports#9]
**Client Name:**  
Joe Nalley  

**Client ID:**  
21634  

**Description:**  
Same as the old bug with going into legacy states for too long and NextGen crashing upon closing out of it, only for Depr. Should be fixed anywhere there is an access depr button like Schedule C, Schedule E, Line Input, Forms and Schedules, and Schedule F. There might be others, but those are the big ones.  

**Reproduce:**  
Use access depr from any place in next gen and leave depr open for about an hour. Close out of depr and it will _probably_ crash.

**Comment by MyNameIsDonovan** [comment]
Ive added this in for 18
