### ISSUE TITLE
1099misc input

### ISSUE THREAD

**Issue by twgreg** [TaxwareSupport/Issue-Reports#90]
**Client Name:**  

Cynthia

**Client ID:**  
21421

**Description:**  
1099 input.
She says she needs the option to make the recipient an EIN instead of just the taxpayer or spouse.

**Reproduce:**  
I get the same options, even in past years. I'm not sure if this is even necessary, but she says she needs it.

**Data Location:**

**Comment by MHGray** [comment]
If it should go to an EIN it would need to be something a partnership or K-1 Gets and then it would come in on the k-1. The 1099 also aren't actually transmitted with the return so this is something that doesn't need to exist.
