### ISSUE TITLE
19Individual - 5329 - Line calculation 

### ISSUE THREAD

**Issue by twchrs** [TaxwareSupport/Issue-Reports#900]
**Client Name:**  
Karen

**Client ID:**  
2118-2

**Description:**  
Spouse 5329 Line 49 not calculating.

**Steps to Reproduce:**  
Go into Spouses form 5329 Line 49 not calculating.

**Data Location:**
R:\Chris\21118-2 Karen Form 5329

**Comment by DodgerDave** [comment]
User was missing input for value of HSA on last day of 2019.
