### ISSUE TITLE
2019 1120S- IL - XML isn't updating

### ISSUE THREAD

**Issue by twgenie** [TaxwareSupport/Issue-Reports#901]
**Client Name:**  
Ron

**Client ID:**  
99081

**Description:**  
The XML isn't updating the return after putting information into Illinois unless you leave the return and go back into the return.

**Steps to Reproduce:**  
Use data below.

**Data Location:**
R:\Genie\Client Data\99081

**Comment by twJorge** [comment]
Fixed.
