### ISSUE TITLE
Wintax - Form 8863 - Foreign address throws internal validity error but no way to enter state and ZIP

### ISSUE THREAD

**Issue by MHGray** [TaxwareSupport/Issue-Reports#902]
**Client Name:**  
Sea

**Client ID:**  
496-86

**Description:**  
Getting this error because 8863 information is foreign and can't enter ZIP and State. The State might be able to be entered as EN for England, but the postcode has letters in it and the zip code field on the 8863 input does not accept letters even if the foreign checkbox is checked.
![image](https://user-images.githubusercontent.com/8196735/76232102-749ae480-61e3-11ea-9792-5274223a2a9d.png)

Recommend removing that internal validation error if the address is marked foreign as well as removing the letter restriction in the zip code box if the address is foreign. 

**Steps to Reproduce:**  
Use Data Provided -> Validate

**Data Location:**
R:\Matt\Foreign8863

**Comment by DodgerDave** [comment]
Fixed 3-10.
