### ISSUE TITLE
Wintax- 8863 - client is not receiving the AOP and institution info is deleting

### ISSUE THREAD

**Issue by TwZach** [TaxwareSupport/Issue-Reports#907]
**Client Name:**  
John

**Client ID:**  
21620

**Description:**  
Client is not receiving the AOP, even when everything seems filled out. The 8863 does not show on the forms used. And when you exit the return the institution information seems to have disappeared. 

**Steps to Reproduce:**  
open client data -> forms and schedules -> 8863 -> institution info -> input info -> ok -> forms used does not show 8863 -> exit return -> go back into return -> 8863 institution info -> it's blank.

**Data Location:**
R:\Zac\client data\1040nextgen\21620cltdta

**Comment by DodgerDave** [comment]
Taxpayer is being claimed as a dependent so they can't take American Opportunity credit.
