### ISSUE TITLE
Idaho starts out with a $300 overpayment

### ISSUE THREAD

**Issue by TwZach** [TaxwareSupport/Issue-Reports#91]
**Client Name:**  
Dennis
**Client ID:**  
5370
**Description:**  
When starting a Idaho return it automatically gives a 300 payment to the client. It does not go away until you exit return and reenter Idaho.
**Reproduce:**  
Start new return, go to state input for Idaho, payment of 300 is there.
**Data Location:**

**Comment by MHGray** [comment]
This is the Idaho Grocery credit. They get ~$100 per person in payment to make up for sales tax on groceries bought during the year.
