### ISSUE TITLE
Wintax - OH - Schedule Credit

### ISSUE THREAD

**Issue by twsal** [TaxwareSupport/Issue-Reports#911]
Randall

572-86

Client is reporting for the return, under the Ohio schedule of credits, line 2 and line 4, should not be carrying over. They should not qualify for the these two credit due to the income.

![image](https://user-images.githubusercontent.com/44677096/76474836-23911900-63ba-11ea-9613-b60d17ac08d5.png)

R:\Sal\Randall 572-86

**Comment by twJorge** [comment]
Fixed.

**Comment by MHGray** [comment]
Client says that your Ohio fix wasn't entirely correct. According to instructions this file should be able to take both the retirement credit and the senior credit, but it isn't calculating those.

![image](https://user-images.githubusercontent.com/8196735/77175081-463cc500-6a7f-11ea-8675-d6e16c9fbc2c.png)
![image](https://user-images.githubusercontent.com/8196735/77175094-4a68e280-6a7f-11ea-9331-e03b362a3127.png)
![image](https://user-images.githubusercontent.com/8196735/77175142-5b195880-6a7f-11ea-8880-11ca069485b8.png)
![image](https://user-images.githubusercontent.com/8196735/77175507-fc081380-6a7f-11ea-9a75-9e7117faf7b6.png)

**Data Location**
R:\Matt\OHSeniorRetirement
