### ISSUE TITLE
Wintax - 8814 - Form is causing a validation error

### ISSUE THREAD

**Issue by MHGray** [TaxwareSupport/Issue-Reports#916]
**Client Name:**  
Kinh

**Client ID:**  
21056

**Description:**  
![image](https://user-images.githubusercontent.com/8196735/76565126-2b5ac700-6467-11ea-8abe-3a193e570315.png)
Validation error, looks like it needs 1 thing or another, but both is breaking it.
![image](https://user-images.githubusercontent.com/8196735/76565152-39104c80-6467-11ea-9fd0-0d5b43f4a3e1.png)

**Steps to Reproduce:**  
Use Data Provided -> Validate

**Data Location:**
R:\Matt\8814Validation

**Comment by DodgerDave** [comment]
Fixed 3-12.
