### ISSUE TITLE
19Partnership  - Mississippi K1 - Marking SCorp 

### ISSUE THREAD

**Issue by twchrs** [TaxwareSupport/Issue-Reports#917]
**Client Name:**  
Jeremy 

**Client ID:**  
5980

**Description:**  
S corporation getting marked instead of partnership. Box D owner partner SSN or FEIN going on box E 

**Steps to Reproduce:**  
Preview Mississippi K1 

**Data Location:**
R:\Chris\5980 Jeremy

**Comment by DodgerDave** [comment]
Fixed 3-13.
