### ISSUE TITLE
Arkansas returns only preview non-resident

### ISSUE THREAD

**Issue by TwZach** [TaxwareSupport/Issue-Reports#92]
**Client Name:**  
Tom
**Client ID:**  
20005
**Description:**  
Arkansas returns only preview non-resident, then it changes the residency status of the return to blank
**Reproduce:**  
yes, open return create arkansas return, check residency status, preview, check residency again.
**Data Location:**

**Comment by MHGray** [comment]
Seems to be Fixed.
