### ISSUE TITLE
19Wintax  - CA - Calculation error 

### ISSUE THREAD

**Issue by twchrs** [TaxwareSupport/Issue-Reports#920]
**Client Name:**  
Charles 

**Client ID:**  
20167

**Description:**  
Calculation error 

**Steps to Reproduce:**  
Reject inside folder 

**Data Location:**
C:\Users\User\Desktop\20167 Charles

**Comment by DodgerDave** [comment]
If making a change to the federal AGI, you must go back into CA to recalculate.
