### ISSUE TITLE
Wintax - AL - NR validation error when fed has rental income/loss but none for AL

### ISSUE THREAD

**Issue by MHGray** [TaxwareSupport/Issue-Reports#922]
**Client Name:**  
Steve

**Client ID:**  
9913

**Description:**  
Validation error says they are missing a state code but there is no input for a state for this particular field. Not sure where to enter it.
![image](https://user-images.githubusercontent.com/8196735/76909086-8164ab80-6867-11ea-85c0-f64e352794f9.png)

**Steps to Reproduce:**  
Use Data Provided -> Validate -> Info seems correct on NR portion

**Data Location:**
R:\Matt\ALNR

**Comment by twJorge** [comment]
Input is already there. Validation uses poorly worded "State" for value. This value is the income received in Alabama for net profit or loss. Found in schedule E.
