### ISSUE TITLE
Wintax - MT - Validation error when inputting Contractor's Credit

### ISSUE THREAD

**Issue by MHGray** [TaxwareSupport/Issue-Reports#924]
**Client Name:**  
Casey

**Client ID:**  
26009

**Description:**  
Validation error on MT when inputting the Contractor's receipts credit. Whether the multiple CGR box is checked yes or no they still receive the same validation error. Looks like MT wants an ENUM value instead of a 0 or 1.
![image](https://user-images.githubusercontent.com/8196735/77006224-50e04880-691f-11ea-94f9-1e70ba2465d4.png)
![image](https://user-images.githubusercontent.com/8196735/77006272-6eadad80-691f-11ea-8fd5-1f01df0f9bb9.png)

**Steps to Reproduce:**  
Use Data Provided -> Validate

**Data Location:**
R:\Matt\MTContractorCredit

**Comment by twJorge** [comment]
Fixed.
