### ISSUE TITLE
Wintax - IA - Residency status does not update til you leave and return

### ISSUE THREAD

**Issue by MHGray** [TaxwareSupport/Issue-Reports#925]
**Client Name:**  
Message Boards

**Client ID:**  
Message Boards

**Description:**  
In IA Basic Info, lines [04] & [05] Residency Status do not update when you select them from the box until you leave the basic information and return. It is pretty confusing if you are trying to change the status.

**Steps to Reproduce:**  
IA -> [01] Basic Info -> [04] Taxpayer Residency -> Select Non resident -> [04] doesn't change.

**Comment by MyNameIsDonovan** [comment]
Agreed. Fixed.
