### ISSUE TITLE
Fiduc - 8995- QBI Not Generating

### ISSUE THREAD

**Issue by twsal** [TaxwareSupport/Issue-Reports#927]
Bob

112703

The return seems to not generate the 8995 information, from the Schedule E.

![image](https://user-images.githubusercontent.com/44677096/77117642-ab48da00-69ef-11ea-8d9e-ffe1aad0d674.png)

R:\Sal\bob112703

**Comment by MyNameIsDonovan** [comment]
this should be fixed now
