### ISSUE TITLE
Wintax2018 - CA - Amounts on column c

### ISSUE THREAD

**Issue by twsal** [TaxwareSupport/Issue-Reports#929]
Mike

21002

Client is stating the amounts shown on part C for the Sch CA, should be zero. It is currently showing 159,960, but should be zero, going by him. I looked at the Sch E, he does seem to have a lot of overwrites for the deprecation but for the fed, not sure if that is causing this amount to carry over to the state. The amount there does come out to the same shown on the state return.

![Capture](https://user-images.githubusercontent.com/44677096/77189943-9b83d100-6a95-11ea-95a8-82776b0e0bfc.JPG)

R:\Sal\21002 mike
**Data Location:**

**Comment by DodgerDave** [comment]
Since there was no CA depreciation, this is correct. The user must have forgotten to calculate state depreciation in Depreciation program.
