### ISSUE TITLE
Wintax - CA- Validation Error for 593 Form

### ISSUE THREAD

**Issue by twsal** [TaxwareSupport/Issue-Reports#931]
Karen

90157

On the CA 593 form, it seems to have validation error when entering a county input. We tried entering different counties, but still comes up with an error.

![image](https://user-images.githubusercontent.com/44677096/77340045-f7469800-6ce9-11ea-97b9-33859f957735.png)
![image](https://user-images.githubusercontent.com/44677096/77339995-e39b3180-6ce9-11ea-9c92-134b57af9eed.png)

R:\Sal\KAREN 90157

**Comment by DodgerDave** [comment]
Schema won't accept county name in all caps.
