### ISSUE TITLE
Wintax- CO - Part Year 

### ISSUE THREAD

**Issue by twsal** [TaxwareSupport/Issue-Reports#932]
Myron

10203

Client is reporting line 34 for the part year form is miscalculating the percent incorrect. Stating the decimal is on the wrong placement.

**Steps to Reproduce:**  
![image](https://user-images.githubusercontent.com/44677096/77441825-1b1be380-6da7-11ea-839a-cd1bca940d56.png)

R:\Sal\Myron 10203

**Comment by twJorge** [comment]
Fixed.
