### ISSUE TITLE
Wintax - CA - 5805 is causing an XMl error when ever you input waiver amount

### ISSUE THREAD

**Issue by TwZach** [TaxwareSupport/Issue-Reports#934]
**Client Name:**  
JOhn

**Client ID:**  
29014

**Description:**  
When you enter a waiver amount on the 5805 the CA xml stops working

**Steps to Reproduce:**  
open client data -> other state data -> 5805 -> Waiver amount -> Validate state -> Take Waiver amount out validate 

**Data Location:**
R:\Zac\client data\1040nextgen\29014cltdta

**Comment by DodgerDave** [comment]
Fixed 3-24.
