### ISSUE TITLE
Filing status single is not marking on form PTS

### ISSUE THREAD

**Issue by TwZach** [TaxwareSupport/Issue-Reports#95]
**Client Name:**  
Debbie
**Client ID:**  
21157
**Description:**  
In a Missouri return if filing status single is selected then no box is checked under filing status on form MO-PTS.
**Reproduce:**  
open client -> open MO -> set filing status to single -> preview form PTS -> check box is blank.

note that this does not occur for married filing joint or separate.  
**Data Location:**

**Comment by MHGray** [comment]
Seems to be fixed
