### ISSUE TITLE
Wintax - 1116 - No place to put the less than $300 foreign income credit

### ISSUE THREAD

**Issue by MHGray** [TaxwareSupport/Issue-Reports#96]
**Client Name:**  
Nid

**Client ID:**  
21486

**Description:**  
In legacy you could input the 1116 amount if it is less than 300 (600 for joint) in the box under the 1116 list. NextGen doesn't have anyware I can see to put that. If they have less than 300 for the credit and some other stipulations, they are allowed to put the credit on the 1040 without having to fill out the 1116. Instructions on page 1 bottom of column 2.

![image](https://user-images.githubusercontent.com/8196735/51497943-946e0f80-1d79-11e9-824f-f464edbe07fe.png)
Can't type in that greyed out box above

**Comment by DodgerDave** [comment]
Fixed 1-28.  Input for this is on Schedule B screen
