### ISSUE TITLE
2018 Wintax -> NJ -> Automatically assigning NJ1040X even after Clearing all NJ Forms/Data

### ISSUE THREAD

**Issue by twnathan** [TaxwareSupport/Issue-Reports#97]
**Client Name:**  
FELIX OLIVERO

**Client ID:**  
21119

**Description:**  
![image](https://user-images.githubusercontent.com/44508876/51498351-03983380-1d7b-11e9-9a8b-2e5fe85635f4.png)

Client has started a return for a NJ resident, but is receiving the schema error above. I have saved the client data and XML file as well (see Data Location). Clearing/zeroing out all NJ forms/schedules/info does not remove the error.

**Reproduce:**  
Reproduced on Tech computer -- simply changing a client to resident of NJ and opening the NJ return portion, then exiting, generated the error.

**Data Location:**
R:\Nathan\21119 FELIX OLVERO

**Comment by DodgerDave** [comment]
Fixed 1-21-19
